### ISSUE TITLE
Excited to see this in progress!

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/glTF-Blender-Exporter#1]
As a dev on the original blendergltf project, I'm looking forward to contributing to this! I hope the work happens in public so I can keep an eye on it, and help with issues/testing/dev. Is this under development yet?

**Comment by McNopper** [comment]
This glTF Blender exporter will be a pure glTF 2.0 exporter. It will be open source and accessible right from start. So it will be possible to test and give feedback right from the beginning and during the development of the project.

As soon as all legal documents are signed, this repository will be populated.

So, as soon as the first lines of code are submitted, we are looking forward to your contribution!

**Comment by UX3D-nopper** [comment]
Uploaded first developer version. Please note, this is all in early stage.
