### ISSUE TITLE
Blender can't export model

### ISSUE THREAD

**Issue by jgwinner** [KhronosGroup/glTF-Blender-Exporter#102]
### Description

I import a free file from here: https://www.sharecg.com/v/76031/browse/5/3D-Model/Free-Hedges 

via FBX import.

I then export it with code pulled today from git. (I checked to make sure it was up to date).

I get these errors, seemingly no matter what export options I choose.

```
location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\ad
dons\blendergltf-master\__init__.py", line 370, in execute
    gltf = export_gltf(data, settings)
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\ad
dons\blendergltf-master\blendergltf.py", line 1592, in export_gltf
    state['output']['animations'] = export_animations(state, scene_delta.get('ac
tions', []))
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\ad
dons\blendergltf-master\blendergltf.py", line 1442, in export_animations
    export_active(regular_objects)
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\ad
dons\blendergltf-master\blendergltf.py", line 1425, in export_active
    if obj.animation_data.action:
AttributeError: 'NoneType' object has no attribute 'action'
```

### Steps to reproduce

Download https://www.sharecg.com/v/76031/browse/5/3D-Model/Free-Hedges 

I tried 'long' and 'longround'.

(redistrution rights are allowed, so I'm attaching here).
[Free Hedges.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1369169/Free.Hedges.zip)

Import Long as an FBX.

Select the hedge, and export as GLTF. Options are:

![gltfbugoptions](https://user-images.githubusercontent.com/10425170/31348073-4a3544aa-acd3-11e7-8744-c24b625d9e9c.png)

Generates error:

```
Traceback (most recent call last):
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blendergltf-master\__init__.py", line 370, in execute
    gltf = export_gltf(data, settings)
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blendergltf-master\blendergltf.py", line 1592, in export_gltf
    state['output']['animations'] = export_animations(state, scene_delta.get('actions', []))
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blendergltf-master\blendergltf.py", line 1442, in export_animations
    export_active(regular_objects)
  File "C:\Users\John\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blendergltf-master\blendergltf.py", line 1425, in export_active
    if obj.animation_data.action:
AttributeError: 'NoneType' object has no attribute 'action'

location: <unknown location>:-1
```

(I tried other versions; I also inserted a keying set, but still got errors; although after adding a keying set to the object and to the camera I still got errors).

I DID get it to export by adding a keying set to both the object, one or two keyframes, and the camera, with these options:

![gltfokoptions](https://user-images.githubusercontent.com/10425170/31348604-0b8dd8d2-acd5-11e7-9bda-1a2c47c69e96.png)

I then deleted the original FBX, and imported "Long". I then exported (without creating any keying sets or objects) and it exported fine.

### Possible cause

It seems like the camera needs a single keyframe and a location keying set.

Forgive me if I've uploaded this twice, I created the issue late last night and couldn't find it this morning.

== John ==

**Comment by donmccurdy** [comment]
I think you have the other Blender exporter: https://github.com/Kupoman/blendergltf 🙃

Note that even if you have both installed, choosing either glTF export option still sends you to the same place, so you have to uninstall one of the exporters. I'm not sure if that's a Blender limitation, or if the exporters are somehow incompatible.

**Comment by jgwinner** [comment]
Yep, you're right! 

Ah! Which also explains why I couldn't find the bug! I posted it in the other group.

SO sorry. I got email from THIS group this morning and didn't notice which exporter I was using :) 

I'll close this one.

== John ==
