### ISSUE TITLE
Failure report : Blender -> glTF -> SketchFab

### ISSUE THREAD

**Issue by grondilu** [KhronosGroup/glTF-Blender-Exporter#104]
Hello,

so I've tried to convert [this blender model](https://grondilu.github.io/oolite.blend) which I've made from the FOSS game [oolite](http://www.oolite.org).  Blender renders it fine, but then when I submit the glTF files to sketchfab, I don't get a satisfactory result :

https://skfb.ly/69tLQ

The geometry is fine, but the materials are either absent or incomplete.

Other attempts with different viewers (listed in the Khronos README for glTF) were not good either.

**Comment by UX3D-nopper** [comment]
To get exactly the same materials, specific requirements have to be fulfiled:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md
Also, please cross check if this is a Sketchfab import problem.
