### ISSUE TITLE
Trying to use the alpha channel as an emissive layer

### ISSUE THREAD

**Issue by grondilu** [KhronosGroup/glTF-Blender-Exporter#106]
Hello,

So I have this model:

![cobra mk3 in blender](https://i.imgur.com/fTg2t7D.png)

after the export I don't see the emissive layer that I had in the rendering in blender :
 
![glTF import](https://i.imgur.com/V7JKKXC.jpg)

What am I doing wrong?

Also notice that I had to use two input nodes using the same texture (those two different instances I think).  I've tried to use the same one that would feed the glTF Metallic Roughness node in both the basic color and emissive inputs, but that did not work for some reason.

Thanks for any help

**Comment by UX3D-nopper** [comment]
You need to convert the alpha channel to a RGB image. The RGB image needs to go into Emissive, and not EmissiveFactor.
