### ISSUE TITLE
Axis orientation for exported scenes

### ISSUE THREAD

**Issue by 4DA** [KhronosGroup/glTF-Blender-Exporter#107]
Is my understanding correct that plugin exports meshes with YZ coordinates flipped?
Is there a possibility to specify **forward** and **up** axes like that is possible with OBJ exporter?

Thanks.

**Comment by UX3D-nopper** [comment]
At this point of time, no, this is not possible. But with some effort this could be added.

**Comment by donmccurdy** [comment]
Also note there's some [discussion of defining a preferred forward/up convention](https://github.com/KhronosGroup/glTF/issues/1043) for the glTF format, in which case importers will expect that. If that is decided the exporter will be consistent of course. :)

**Comment by emackey** [comment]
This issue should probably stay open as an `enhancement` request.
