### ISSUE TITLE
Empties in Scene hierarchy that don't match Dope Sheet layer order result in incorrect animation driver mapping

### ISSUE THREAD

**Issue by mattg73** [KhronosGroup/glTF-Blender-Exporter#108]
Hi 

Another issue we've encountered somewhat related to #100: 

If empties are used in a scene to support multiple object transforms being animated through a single parent empty then, on export, the gLTF file displays the wrong keyframe controls driving the wrong scene object.

This seems to be because empties are not reflected by default in the Dope Sheet timeline, and even if Ghost mode is enabled (displaying invisible objects in the dopesheet), the hierarchical ordering of layers is not preserved. This results in incorrect animation driver mappings.

A workaround is to use a completely flat scene hierarchy but this is obviously not an ideal solution for complex scenes

**Comment by UX3D-nopper** [comment]
Can you please provide a simple example?

**Comment by mattg73** [comment]
Sure, here's a .blend and .glb...

[gltf_Empties_Test.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1418765/gltf_Empties_Test.zip)

Animation order is inverted between blender and glb. Although the specific sequencing seems to be related to the order in the scene hierarchy compared to the order in the dope sheet editor

**Comment by UX3D-nopper** [comment]
Okay got it. Is is related to the dope sheet problem. We will wait, until the main problem is solved.

**Comment by mattg73** [comment]
Thanks, is there an issue number for that? I'd be interested to learn the broader context

**Comment by UX3D-nopper** [comment]
It's this thread:
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/39

**Comment by mattg73** [comment]
👍
