### ISSUE TITLE
Animated joints not attached to a skin are not exported.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#109]
I have three input (COLLADA) files from mixamo.com:

- [robot.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1423901/robot.zip) (T-Pose)
- [robot@shoved.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1423902/robot.shoved.zip) (animation clip, no mesh)
- [robot@stand.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1423903/robot.stand.zip) (animation clip, no mesh)

The first file, containing the mesh and skeleton, exports to glTF correctly. I'd like to export the second two models, containing only animated skeletons, as well. They load correctly in blender:

![008c287a-e63e-433b-b2c6-0c028f5bdbd3-63478-00007b56dab119fe](https://user-images.githubusercontent.com/1848368/32130919-a1469a46-bb56-11e7-81c8-efd5b1be828a.gif)
[robot@stand.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1423905/robot.stand.blend.zip)

After exporting the "stand" clip, I find animation entries that presumably contain animation data, targeting node `-1`, but none of the bones are there:

[robot@stand.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1423907/robot.stand.gltf.zip)

![screen shot 2017-10-27 at 8 38 43 pm](https://user-images.githubusercontent.com/1848368/32130928-dafa95d0-bb56-11e7-8f7a-f3cddcaecac7.png)

Perhaps bones are not exported from the Blender exporter if they are not attached to a mesh?

The end-goal here is to have 1 mesh and N animations in glTF form, without duplicating more data than necessary. I'm attempting this workaround, similar to what is often done with FBX and Unity, to get multiple animations exported correctly. #39 would be another way of accomplishing the same goal.

Thanks!

**Comment by mattdw** [comment]
My workaround here is just to delete all verts from any meshes (leaving empty geometry); that makes for a slightly cluttered scene graph, but it's allowing us to export individual animations without duplicating the meshes.

**Comment by dantoye** [comment]
In my workflow, there is no skin, either. I'm trying to export the Armature, with its child bones and NLA actions, which exist in one file, and the meshes, with their vertex groups, in another. My intent is for the vertex groups of the meshes to line up with the bones in the armature on the import side.

( @donmccurdy is there any chance of a more direct communication line here? Are you in discord or slack? I'm having a million issues with this exporter right now, this is just one... )

**Comment by donmccurdy** [comment]
We have a glTF Gitter channel: https://gitter.im/KhronosGroup/glTF

I'll be off and on but others may be able to help. :)

**Comment by lexaknyazev** [comment]
@donmccurdy 
>  is there anything in the spec to say whether a node can reference a skin without also referencing a mesh?

Seems like it's [forbidden by the schema](https://github.com/KhronosGroup/glTF/blob/2fff547b66851959d9e4d704e6cc8391e41b2726/specification/2.0/schema/node.schema.json#L85-L88).

**Comment by donmccurdy** [comment]
Appears to be fixed in the new exporter :) https://github.com/KhronosGroup/glTF-Blender-IO
