### ISSUE TITLE
Over sized file when exporting with embedded textures

### ISSUE THREAD

**Issue by source83** [KhronosGroup/glTF-Blender-Exporter#11]
When exporting with embedded textures of a model gave me a 55MB sized file.
When exporting and copying the textures gave a total of 7-8MB including the model itself witch alone was 500-600kbyte.

**Comment by donmccurdy** [comment]
@source83 could you try using the binary `.glb` export option? When exporting ASCII `.gltf`, images are Base64 encoded, and this does significantly increase their size.

**Comment by lexaknyazev** [comment]
Base64 encodes each 3 bytes as 4, so it could give only 33% size increase. Looks like a bug.

**Comment by UX3D-nopper** [comment]
Can you please provide an example where this happens?
Could not reproduce with included e.g. 01_textured_sphere.

**Comment by UX3D-nopper** [comment]
What also could happened, that former. non-used images are exported.
Of course, this is just speculation and the Blender sample file to test would be perfect.

**Comment by stevenvergenz** [comment]
Is it possible that the embedded textures are being stored uncompressed? That would contribute significantly to bulk.

**Comment by McNopper** [comment]
Code is used from 'blender-thumbnailer.py', which is Blender internal:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scripts/addons/io_scene_gltf2/gltf2_create.py
And code seems okay. Let's see, if we can get a reproducable example.

**Comment by lexaknyazev** [comment]
@McNopper 
That code uses only zlib compression on raw pixel data. However, typical PNG encoders perform scanline filtering before zlib. 

Could exporter use [Blender PNG encoder](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scripts/addons/io_scene_gltf2/gltf2_generate.py#L1361) for all storage modes?

**Comment by McNopper** [comment]
This would be optimal but the encoder is not "public" accessible. When we optimze the exporter, I will revisit this problem again.
Let's see if I can somehow reproduce this and we can get access to this Blender file.

**Comment by source83** [comment]
@donmccurdy do you want me to upload a file that has this problem ?
No problem, just want to verify that it's what you need from me.

**Comment by UX3D-nopper** [comment]
Best would be to get the Blender file plus the assets

**Comment by source83** [comment]
Is this good enough ?
[Beta model](https://jvr.junkonet.org/Beta.7z)

**Comment by UX3D-nopper** [comment]
Yes, this is perfect. It is always good, if we have an example to reproduce the problem.

But you said you do get 55 MB, but the current exports - glb and embedded gltf - do create a reasonable size ~9MB and ~12 MB. If we can use a better PNG encoder, the size will shrink as well. So, for this, we already have a solution, which is not added to the exporter yet.

But as far as I understood, the 55MB case does not occur anymore, right?

**Comment by source83** [comment]
this is not the same file, this is a different file, sorry.

**Comment by source83** [comment]
Well, the fbx file is almost 6mb smaller than the gltf file is when including the same amount of data. why is this ?

**Comment by UX3D-nopper** [comment]
FBX and Collada are exchange formats. glTF is a transmission format.
So why can a glTF file be larger than a FBX file?
In exchange formats, e.g. a flat shaded cube can be described with 8 vertices, 6 normals and if triangulated, with 2 * 3 * 6 indices for the vertices and for each triangle 2 * 3 * 1 indices for the normals. That is compact and small but for a modern GPU and API, this data has to be converted to a GPU "friendly" vertex buffer:
Each vertex has its normal, texture coordinate, collor and so on.
When loading a FBX or COLLDA file, the loader or engine is doing this for you. Drawback is, that these loaders can get complicated, when more features come in. Also, this has a negative impact on load time.

With glTF, this "unfolding" of vertex data has already happened. The data stored in a glTF file can be used 1:1 - if there are no allignemt issues - by the GPU.

You can try this out:
Create a sphere and triangulate it in advance before exporting. Remove all cameras and lights that just really this spehere is exported.
Now export it once flat and smooth shaded. The flat shaded sphere is much larger than the smooth shaded one. Why? For the smooth shaded sphere, no extra data needs to be created. For the flat shaded - yes.

So, is the larger glTF file acceptable? For now, yes. Also, for the future, glTF will contain a vertex compressor. So, as soon as this is available, the binary file for glTF will shrink as well.
