### ISSUE TITLE
Exporter writes a zero-length tangent vector

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-Exporter#110]
I'm attempting to update a few models in KhronosGroup/glTF-Sample-Models#130.  One of them, the `DamagedHelmet` model, exports from Blender and fails in the glTF Validator with a zero-length tangent vector.

Here's the Blender file:  [DamagedHelmet.blend](https://github.com/KhronosGroup/glTF-Sample-Models/blob/10baf54c334136d9db1ef98a4c5c283436b92c14/sourceModels/DamagedHelmet/DamagedHelmet.blend)

You can export glTF or glb versions.  The validator fails both with this message:

> #/accessors/3: Accessor element at index `11043` is not of unit length: `0.0`.

Accessor 3 in this case is the `TANGENT` vector collection, and it appears that one of them has been exported with zero length.

/cc @UX3D-nopper @lexaknyazev

**Comment by lexaknyazev** [comment]
@emackey 
I'm looking into this.

**Comment by lexaknyazev** [comment]
Error message should be adjusted a bit, but the exported model contains zero-length tangent vector
`[0.0, 0.0, -0.0, 1.0]`.

**Comment by emackey** [comment]
I presume the official Khronos Blender exporter should be expected to not produce such vectors?  Or is this some problem with the model itself?  I tried re-generating the normal vectors to no avail, and Blender does not have a user-option to re-generate the tangent vectors.

**Comment by lexaknyazev** [comment]
Tangents come from Blender's engine:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/5ffd6efa0bc1378fe681253ea397c3250b94f26c/scripts/addons/io_scene_gltf2/gltf2_extract.py#L372-L377

Exporter just adds the fourth component to them:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/5ffd6efa0bc1378fe681253ea397c3250b94f26c/scripts/addons/io_scene_gltf2/gltf2_extract.py#L41-L45

**Comment by emackey** [comment]
I see.  What's the correct solution here?  Should the exporter be checking each one for zero length?  What should it do if it finds a zero-length tangent?

**Comment by lexaknyazev** [comment]
Ideally, I think we should identify what kind of geometry produces this issue. 
For now, exporter could verify unit vectors for all-zeros and print something to console.

**Comment by emackey** [comment]
I dream of a day when VSCode shows you a mesh wireframe and points to the vertex that offended the validator...

But until then, I'll just hazard a guess.  It's possible that there are degenerate triangles in UV space that are not degenerate in XYZ space.  This isn't necessarily an error, but it results in some "stretched" imagery on the triangle in question and maybe makes the tangents impossible to calculate.  There's no perfect answer as to what to do with a normal map in this case, but it may well have been the artist's intention to stretch the base map across the triangle in this manner.

**Comment by lexaknyazev** [comment]
> I dream of a day when VSCode shows you a mesh wireframe and points to the vertex that offended the validator...

What kind of validation output would be needed to implement this?

**Comment by emackey** [comment]
> What kind of validation output would be needed to implement this?

Moving that topic to AnalyticalGraphicsInc/gltf-vscode#43.

Since this issue is in the Blender-Exporter repo, we'll keep it on the topic of how the exporter should react to Blender's calculation of zero-length tangents.

**Comment by UX3D-nopper** [comment]
Added a warning output here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/0089f3198b74ffb9491a953873c1214c4b3cfe10

I close this ticket, as in this case a 3D artist has to fix the 3D model.
