### ISSUE TITLE
unexpected export exporting cameras

### ISSUE THREAD

**Issue by Friksel** [KhronosGroup/glTF-Blender-Exporter#113]
Using the latest version of the exporter to export a blender scene to gltf result in unexpected camera export. Cameras suddenly live in a scene as a child of an object instead of living directly in the scene root.  

I know blender has the behaviour of having a camera inside some kind of group, but this should be flattened in the gltf export, like other blender exporters do too. The gltf export also has some strange double names according to cameras. And names like 'correction-[cameraname]' not expected to be in the export (and making the file bigger?). So something seems to be off here.

**problems using the exported gltf in threejs**
Unfortunately this export raises problems loading the gltf scene with cameras in threejs using their gltf loader. At first I thought it could be a problem of the loader (https://github.com/mrdoob/three.js/issues/12656), but after some tests and comparison with other gltf files (also by the Khronous group) it shows the problem has something to do with the export. 

**The blend file and the gltf export I get from the exporter:**
[gltftest.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1475623/gltftest.zip)

**Different export compared to the Khronousegroup example files**
Looking at the gltf v2 Cameras example by Khronousgroup here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cameras/glTF this is a totally different export. These examples are working fine, can be loaded with cameras as expected in threejs and loaded in the gltfviewer here: https://gltf-viewer.donmccurdy.com/
But the blender exports can't.

**steps to reproduce**
Opening blender --> creating a new default scene --> only change the name of the object, camera and light and the color of the cube --> export to gltf using the exporter:
The exported camera now lives inside an Object instead of directly in the root and there is some strange unwanted/unexpected naming with 'Correction-[cameraname]' in the export:
<img width="329" alt="32845745-606d1a44-c9da-11e7-9c99-272f592e69b6" src="https://user-images.githubusercontent.com/3089978/32850340-23fe51ba-ca32-11e7-8495-d837d1133c77.png">

**Comment by UX3D-nopper** [comment]
To make it short, the additonal node is required to convert from the default direction of the camera to the default direction in glTF.

Also, this is a valid glTF file;
```


{
    "uri": "test.gltf",
    "mimeType": "model/gltf+json",
    "validatorVersion": "2.0.0-dev.1.2",
    "validatedAt": "2017-11-15T17:31:28.191Z",
    "issues": {
        "numErrors": 0,
        "numWarnings": 0,
        "numInfos": 1,
        "numHints": 0,
        "messages": [
            {
                "code": "NODE_EMPTY",
                "message": "Empty node encountered.",
                "severity": 2,
                "pointer": "/nodes/3"
            }
        ],
        "truncated": false
    },
    "info": {
        "version": "2.0",
        "generator": "Khronos Blender glTF 2.0 exporter",
        "resources": [
            {
                "pointer": "/buffers/0",
                "mimeType": "application/gltf-buffer",
                "storage": "external",
                "uri": "test.bin",
                "byteLength": 612
            }
        ],
        "hasAnimations": false,
        "hasMaterials": true,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": false,
        "hasDefaultScene": true,
        "primitivesCount": 1,
        "maxAttributesUsed": 2
    }
}


```

**Comment by donmccurdy** [comment]
Here are the nodes exported:

```
{
    "camera" : 0, 
    "name" : "Correction_mainCam", 
    "rotation" : [
        -0.7071067690849304, 
        -0.0, 
        0.0, 
        0.7071067690849304
    ]
}, 
{
    "children" : [
        1
    ], 
    "name" : "mainCam", 
    "rotation" : [
        0.483536034822464, 
        0.33687159419059753, 
        -0.20870360732078552, 
        0.7804827094078064
    ], 
    "translation" : [
        7.481131553649902, 
        5.34366512298584, 
        6.5076398849487305
    ]
}, 
```

Is it not possible to apply the rotation of the `Correction_*` node to its parent instead?

**Comment by UX3D-nopper** [comment]
Correct, plus if this node has a mesh or other nodes as a child, it is getting complicated and in some cases not "solvable".

**Comment by donmccurdy** [comment]
Good points. @Friksel I think the summary here is that Blender's default camera orientation is somewhat different than glTF's, and correcting that requires this extra node. It will be necessary to check `node.isCamera` in three.js as described in the other thread, or make manual changes to the model.

**Comment by Friksel** [comment]
@UX3D-nopper thanks for your quick response. Using children[0] of the node with the cameraname returns the camera and it seems to work well for the main part. So I'm using it that way for now. As far as I can tell by converting a project from using a threejs objectloader to this loader there is a difference in camera-perspective using this loader compared to the threejs object-loader though. Using the same blender-scene/camera. But I'll have to dive into it. Could be something inside my code or maybe something inside the object-loader or the threejs blender exporter that is different. At least cameras are working and glTF is a big step forward, especially looking at performance. Great format and very well documented!
