### ISSUE TITLE
Exporting doesn't finish and loads forever

### ISSUE THREAD

**Issue by lovemoebius** [KhronosGroup/glTF-Blender-Exporter#114]
I tried exporting a model with 60k faces, around 60 morph targets and something like 20 materials.
I left my pc there for an hour but the export never finished. It stopped on the folder view like it usually does when exporting is taking a long time.
This was with the default settings.

Is it supposed to take this long or is there something wrong?

I'm running Blender 2.78, don't know if that matters.

**Comment by lovemoebius** [comment]
Deleting all the morph targets reduces the wait to literally zero so it's definitely that, however I do need morph targets,

**Comment by UX3D-nopper** [comment]
Providing this Blender model would help to investigate this.

**Comment by lovemoebius** [comment]
Here's the model sorry for the late response.
It's originally an MMD model and was the only complex free model with morph targets and rigging I could find online.

http://creativiii.com//threejs/testing-model.blend

**Comment by huhtanen** [comment]
Part of the problem appears that the exporter is requesting recalculation of vertex/polygon normals for *every* loop index of every polygon. That is, generating *all* normals for every loop index, which I guess results in O(n^2) execution time where N is vertex count.

The main loop is this:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/3626c366d0b39419c164d2728bec936f1bc9e2fe/scripts/addons/io_scene_gltf2/gltf2_extract.py#L503

and the normals are calculated by following two lines within the loop
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/3626c366d0b39419c164d2728bec936f1bc9e2fe/scripts/addons/io_scene_gltf2/gltf2_extract.py#L690
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/3626c366d0b39419c164d2728bec936f1bc9e2fe/scripts/addons/io_scene_gltf2/gltf2_extract.py#L687

I made a quick hack where I calculated the normals once for every shape key, cached them, and used them later without recalculation in place of the above two lines. After this exporting was about 100x faster for our model (around 4000 vertices, and tens of shape keys).

**Comment by UX3D-nopper** [comment]
Instead of making a hack, could you please provide a proper implementation and provide your fix with a pull request?

**Comment by huhtanen** [comment]
> could you please provide a proper implementation and provide your fix with a pull request?

How about this: #152

**Comment by donmccurdy** [comment]
Code has been substantially refactored in glTF-Blender-IO, and it appears there have been some performance improvements. I think we can consider this closed, and open new issues if problems are found.
