### ISSUE TITLE
glTF-Blender-Exporter  Error (2.79)

### ISSUE THREAD

**Issue by YiYo97** [KhronosGroup/glTF-Blender-Exporter#116]
![gltferrorcry](https://user-images.githubusercontent.com/33850627/33050130-11e19474-ce42-11e7-8925-e27c9eeafa4f.PNG)
I can't export! :'(

**Comment by donmccurdy** [comment]
@YiYo97 it looks like you are using [a different glTF Blender Exporter](https://github.com/kupoman/blendergltf/). You'll also want to include the source file for debugging.

**Comment by Kupoman** [comment]
@YiYo97 As @donmccurdy pointed out, it looks like you are using the blendergltf exporter instead of this one. It also looks like you are using a version older than 1.1.1. Version 1.1.1 included a fix for this problem in Blender 2.79.
