### ISSUE TITLE
Developer docs for how to edit, debug, etc?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#117]
The developer docs describe how the code is structured, but don't mention how you actually set up the project for editing. Is it possible to inspect state during export, rather than using trial and error? Are there particular developer tools recommended for debugging?

Thanks!

**Comment by UX3D-nopper** [comment]
We are using Eclipse plus PyDev: http://www.pydev.org/
Project files are included in this repo.

**Comment by donmccurdy** [comment]
I think it's helpful to explain how to contribute to an open source project. As in, do you clone the entire repository into a certain folder? Link the folder into Blender in a particular way? Do you need to restart Blender or re-link the project after making changes?

This would be useful info for would-be contributors if documented in the repository somewhere.

**Comment by UX3D-nopper** [comment]
Debugging Blender from Eclipse
https://wiki.blender.org/index.php/Dev:Doc/Tools/Debugging/Python_Eclipse
