### ISSUE TITLE
feature request: save settings

### ISSUE THREAD

**Issue by Friksel** [KhronosGroup/glTF-Blender-Exporter#119]
After creating a new file in Blender or opening an existing file, exporter-settings are being reset back to defaults. It would be nice to be able to save these for the currently opened blender file instead of having to check and change the settings after switching files / open-closing blender. Would it be possible to add a button in the exporter to save the exporter-settings for the current .blend-file?

**Comment by UX3D-nopper** [comment]
See here https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/13

**Comment by Friksel** [comment]
@UX3D-nopper That would be a great improvement, however what I meant maybe was a little bit different: I wish we could save the settings inside the blend file. Threejs exporter does that and it's really convenient, speeds up the workflow and prevents mistakes, while switching blend files all day. So it would be excelent if the presets could be stored inside the blend file!

**Comment by pjoe** [comment]
I'm also missing this from the old threejs exporter. I think you should re-open this issue as it is not the same as presets. Support for both would of course be nice.

**Comment by pjoe** [comment]
Will take a look for how difficult this is to implement ... starting to really bug me :)

**Comment by Friksel** [comment]
Nice! Well done guys! :)
