### ISSUE TITLE
Create an initial release / tag for stable versions in order to use in pipelines

### ISSUE THREAD

**Issue by Aadjou** [KhronosGroup/glTF-Blender-Exporter#120]
First of all, thanks for the great work.

We want to use the gltf export addon in our automated command-line application that is rendering things with blender.
To set up the process, we currently load the addon directly from the source from the master branch.
For versioning and stability of our process, it would be fantastic to have github releases or tags for each stable version. 

Also, the download of the addon is quite long because of all the samples that are in the repository. Would it be possible to somehow split the examples from the actual addon?

Thank you

**Comment by UX3D-nopper** [comment]
The exporter is going to be integrated into Blender 2.80 by default, so versioning etc. will happen in the future by Blender.
As soon there is another stable version, it will be tagged like the first one.

**Comment by Aadjou** [comment]
awesome, thanks for the reply.

**Comment by donmccurdy** [comment]
Resolved in https://github.com/KhronosGroup/glTF-Blender-IO, and Blender 2.8.
