### ISSUE TITLE
Exporter doesn't export all materials

### ISSUE THREAD

**Issue by Stajin** [KhronosGroup/glTF-Blender-Exporter#121]
I made a simple object in Blender, put four different materials on it (literally just colours, no textures), all nodes are the same bar the colour used, two materials show up, two show as blank white, it seems the exporter ignores them?

The material seems to be in the file, it renders in Blender correctly.

[Here's the file](https://drive.google.com/open?id=1sAtoVjRglgjyj4o35CTp3lyllEO3r1xF)

**Comment by donmccurdy** [comment]
Could you attach the `.blend` file?

Note the [user documentation about materials](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md) — for best results with glTF 2.0 use the provided Cycles nodes to create materials. But in theory other materials should be converted to PBR automatically where possible.

**Comment by Stajin** [comment]
[Here's the blend file](https://drive.google.com/open?id=1CY7JtwgB1WMDMzqiw8OIbII4reFTWxeZ), it's a quickly thrown together low poly test file I was using to have a look at the Godot 3 engine.

As a side note, I noticed on import in Godot it shows two materials as white even though in the blend they're brown(ish).

**Comment by donmccurdy** [comment]
Result in three.js:

![screen shot 2017-11-27 at 9 57 26 am](https://user-images.githubusercontent.com/1848368/33281346-c1a77588-d359-11e7-871b-3641d473b013.png)

^is that the same as Godot?

I don't see materials in Blender... not sure if the file is in a weird state or i'm doing something incorrectly. Will leave that to @UX3D-nopper to comment.

**Comment by Stajin** [comment]
Yes. I have set four materials on it, all four materials are in the file (both files), if you grep the glb file for "wood" you'll see two entries, light wood and dark wood. In blender these are both brown. In Godot they show up as white (but can be changed to the correct colours), in a viewer it shows as you have it.

[This](https://drive.google.com/open?id=1Vuh6kd_JnUa71NiyO50mBtRK5q9UooFa) is how it shows in Blender, you can see the four materials on the right. All four materials are identical besides the colour.

If you're using a Blender version < 2.79 it may not load correctly.

**Comment by donmccurdy** [comment]
Oh I see — with the screenshot above you have assigned the `BaseColor` property a brown color, but it should be assigned to `BaseColorFactor`.  The red and blue materials are assigned correctly. The `BaseColor` property is for textures. (We have plans to improve this situation in the future).

**Comment by Stajin** [comment]
Ah, I see, another case of PEBKAC!
I'll close the issue. Thanks for the help!

**Comment by donmccurdy** [comment]
@UX3D-nopper what needs to be done for Principled BSDF support? Do we think that will be in place when the exporter ships with Blender, or will there still be glTF PBR nodes required? (Is that a question for Mike?)

If the glTF nodes will be around a bit longer, perhaps we could label it `BaseColorTexture` to clarify.

**Comment by UX3D-nopper** [comment]
Mainly in the generate_materials function, one need to examine, if the Principled BSDF node is present. If yes, glTF similar node properties like "Base Color" or "Metallic" need to be scanned, if an incoming link does exist. If not, the value is "Base Color Factor" or "Metallic Factor". If the input link is a texture, "Base Color" and "Metallic" need to be set to the associated image/texture.
