### ISSUE TITLE
Add developer/contributor notes to documentation

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-Exporter#123]
Some good information for potential contributors to this plugin was posted in https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/117#issuecomment-345963828 and https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/117#issuecomment-348821356.

This info shouldn't just sit in a closed issue, it should be added to the project documentation here.

**Comment by UX3D-nopper** [comment]
Added here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/46391f58b3a16b1834569bb1941622fe792b4dfd
Everybody is encouraged to enhace the documentation as well.

**Comment by donmccurdy** [comment]
Related — is it possible to have edit the addon and re-export from Blender without, restarting Blender? I'd read that F8 was supposed to reload addons, but it doesn't seem to be picking up changes for me.
