### ISSUE TITLE
THREE.WebGLRenderer.render: camera is not an instance of THREE.Camera.

### ISSUE THREAD

**Issue by Halocom** [KhronosGroup/glTF-Blender-Exporter#125]
Hello,
i created a scene in Blender and export all in a gltf file. Inside my JS file, i load the gltf, and i want to assign the imported camera instead of the defaultCamera, but when i assign my existing camera with the imported one, the console show this error : "THREE.WebGLRenderer.render: camera is not an instance of THREE.Camera."
```javascript
var camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );
var gltf_loader = new THREE.GLTFLoader();
gltf_loader.load("/my_scene.gltf",
    function ( gltf ) {
        scene.add(gltf.scene);
        camera = gltf.cameras[0]; // --> Error !
// or...
        camera = gltf.scene.children[2]; // (2 is the index of the camera of course) --> Error !
// or...
        camera = scene.getObjectByName("Camera"); // --> Error !        `
    },
    function ( xhr ) {
        console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );
    },
    function ( error ) {
        console.log( 'An error happened' );
    }
);
```
Is it a bug or is it someting i did wrong ?

**Comment by donmccurdy** [comment]
@Halocom could you include a file, either the `.blend` or `.gltf`? You can drag .ZIP archives into github comments.

Also, when viewing the model on https://gltf-viewer.donmccurdy.com/, does a "Cameras" section appear in the dropdown on the right?

**Comment by Halocom** [comment]
@donmccurdy hello, thank you for your quick reply ;-)
Here is a zip file with all files for testing.
[switch camera.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1536704/switch.camera.zip)

**Comment by Halocom** [comment]
@donmccurdy Hello, here is a zip file with all files for testing ;-) 
[switch.camera.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1536719/switch.camera.zip)

**Comment by donmccurdy** [comment]
The model looks correct to me. If you open it in the viewer you can select that camera from the list, and the JS console shows the camera as well, named "Correction_Camera". 

<img width="311" alt="screen shot 2017-12-06 at 12 10 04 pm" src="https://user-images.githubusercontent.com/1848368/33683048-71ecda48-da7e-11e7-910b-20708c018d7e.png">

In your demo, this gets rid of the errors for me:

```js
scene.add(gltf.scene);

camera = gltf.cameras[0];

glTF_loaded();
```

I still don't see the result on screen, but there are no lights and could be other issues with the demo setup?

**Comment by Halocom** [comment]
@donmccurdy Thank you for your reply, yes it works with camera = gltf.cameras[0]; (after a few time of waiting, for letting the app completely loaded, i used setTimeout() it saw it works fine ;-) the camera switch correctly ).
[switch.camera2.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1537067/switch.camera2.zip)


> I still don't see the result on screen, but there are no lights
Can i use this thread for asking you why there are "Lamp" and "Lamp001" in my scene and why are they exported as type:Object3D and not as type:SpotLight ?
I tried to change the type on the fly but it's not enough, have you a good way for doing exported Blender lights work when importing glTF ? Thank you for your advices about lights ;-)

**Comment by donmccurdy** [comment]
Support for lights in glTF 2.0 is not finished yet: that extension to the format isn't done. Lights are experimental in this exporter and not yet implemented in THREE.GLTFLoader.

**Comment by Halocom** [comment]
@donmccurdy Thank you very much for your reactivity and infos, this thread can be set to "closed" ;-) Bye
