### ISSUE TITLE
Possible to show warnings during/after BSDF export?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#126]
When BSDF materials are used, the mesh is written with a `-1` material:

```json
{
    "attributes" : {
        "NORMAL" : 2, 
        "POSITION" : 1
    }, 
    "indices" : 0, 
    "material" : -1
}
```

I understand we can't support BSDF materials currently, but this is likely to be a surprise for users, and viewers will not show helpful errors in this case... would it be possible to show warnings or fail altogether when attempting to export BSDF materials?

**Comment by donmccurdy** [comment]
Context: Attempting to answer [this question on SO](https://stackoverflow.com/questions/47667153/blender-export-to-json-for-three-js-missing-materials?noredirect=1#comment82294906_47667153).

**Comment by UX3D-nopper** [comment]
Hmm, I clasify this as a bug. WIll take care about it.

**Comment by UX3D-nopper** [comment]
Fixed here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/c7b79be3c9a95cbcaff01a107daf5b1e28685ab5

**Comment by donmccurdy** [comment]
Thanks!
