### ISSUE TITLE
Shape Keys animation export bug ?

### ISSUE THREAD

**Issue by courgeon** [KhronosGroup/glTF-Blender-Exporter#129]
Hi

Maybe i missed something, or maybe there is a bug when exporting key shape based animation.

Here what i did.
1- Create a simple cube (only object in the scene)
2- add a single Shape keys (basis + Key1)
3 - Add a simple animation with 3 key frame containing only a "Value (Key 1)" 

The Dope Sheet contains 4 lines : DopeSheet Summary > Cube > Key > Value (Key 1)

The animation is simple, key value is 0 on first frame, 1 on second, 0 on last frame. The animation works in blender.

Then I export the GLTF 2.0 file.

        "animations" : [
        {
            "channels" : [
                {
                    "sampler" : 0, 
                    "target" : {
                        "node" : 0, 
                        "path" : "weights"
                    }
                }
            ], 
            "samplers" : [
                {
                    "input" : 9, 
                    "interpolation" : "CUBICSPLINE", 
                    "output" : 10
                }
            ]
        }
    ],

I expect an animation with an input accessor containing 3 value, it's the case 

        {
            "bufferView" : 9, 
            "componentType" : 5126, 
            "count" : 3, 
            "max" : [
                1.625
            ], 
            "min" : [
                0.0
            ], 
            "type" : "SCALAR"
        }, 

I also expect a output accessor with three values : But i get 9 !

        {
            "bufferView" : 10, 
            "componentType" : 5126, 
            "count" : 9, 
            "max" : [
                1.0
            ], 
            "min" : [
                0.0
            ], 
            "type" : "SCALAR"
        }

Parsing the bin give me : 

    timing array length : 3
    frame values array length : 9
    @0  /      0    0    0
    @0,7916667  /      0    1    0
    @1,625  /      0    0    0

Did i miss something ? Or it is a bug ?

Thanks

**Comment by donmccurdy** [comment]
@courgeon I believe that's the correct result, glTF defines CUBICSPLINE `output` values as:

```
[ inTangent1, splineVertex1, outTangent1, inTangent2, splineVertex2, ... ]
```

So you will have N*3 `output` values, where N is the number of `input` values.

If you'd like to test this, support will be added in three.js and https://gltf-viewer.donmccurdy.com/ fairly soon: https://github.com/mrdoob/three.js/pull/12885/files

**Comment by courgeon** [comment]
I see. So far I've only tested my gltf importer with official chronos morph target test files. Both (cube and sphere) uses linear interpolation, with only one value per frame. 

Thanks for the quick reply :)

Best
