### ISSUE TITLE
Presets support

### ISSUE THREAD

**Issue by feiss** [KhronosGroup/glTF-Blender-Exporter#13]
Saving current exporter settings to presets is quite convenient and much needed in production. Example in collada exporter:

![image](https://user-images.githubusercontent.com/359872/27326309-672cbcca-55ab-11e7-8be1-b207536932e6.png)

**Comment by UX3D-nopper** [comment]
Good idea. We will probably do this, as soon as all features are implemented.

**Comment by donmccurdy** [comment]
Fixed in glTF-Blender-IO.
