### ISSUE TITLE
Add area lights to PBR lights extension

### ISSUE THREAD

**Issue by tehbelinda** [KhronosGroup/glTF-Blender-Exporter#136]
I've been experimenting with exporting the area lights in my scenes, but am having some issues with the unit conversion for strength. According to Blender docs, strength is measured in Watts, except for sun/mesh lights which use Watts/m^2
https://docs.blender.org/manual/en/dev/render/cycles/nodes/types/shaders/emission.html

Is there a standard unit I should be using for the GLTF format? My end goal is to get this scene into Three.js.

Intensity in Three.js is measured in Lumens https://github.com/mrdoob/three.js/issues/6259, further evidence is in https://github.com/mrdoob/three.js/pull/6255 that intensity is in lumens when physicalFalloff is set to true. However converting from Watts -> Lumens would give pretty high values for intensity. 

Here is my PR for adding area lights to the exporter: https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/135. So far I've left the raw strength value as is which gives me this (Blender Cycles on the left, ThreeJS on the right):

![areatest](https://user-images.githubusercontent.com/644574/34182443-218e151a-e4cb-11e7-9817-d53e3ce2646f.jpg)

**Comment by donmccurdy** [comment]
Hi @tehbelinda — the KHR_lights extension is currently a draft document and completely experimental, there is no decision (yet) of the standard units in the glTF spec for example. I think your suggestion of adding area light is worth considering though, could you write that in the discussion of the extension? Discussions are happening here: https://github.com/KhronosGroup/glTF/issues/945

**Comment by donmccurdy** [comment]
Closing this issue out, as the upcoming KHR_lights extension does not yet cover area lights. I expect there may be more advanced lighting extensions later, e.g. perhaps related to Adobe Dimension. Would encourage you to provide roadmap feedback on the glTF repository if this is still something you're interested in. Thanks!
