### ISSUE TITLE
Add ability to specify Forward axis

### ISSUE THREAD

**Issue by MrJustreborn** [KhronosGroup/glTF-Blender-Exporter#138]
In other exporters you're able to set Forward AND Up axis.
It's useful when working between different Programms.
![bildschirmfoto_2017-12-28_10-28-24](https://user-images.githubusercontent.com/11594586/34406535-eb9e3822-ebb9-11e7-81c3-3efb9dad0448.png)

**Comment by donmccurdy** [comment]
The glTF format defines forward as +Z and up as +Y, so any correctly-implemented loader should be assuming that’s what the file contains and converting to the expected orientation for its own program... my preference would be to not support different forward axes, and actually to remove the choice of Up axes. I think the odds are actually better this way of having consistent results when moving files between different programs.

**Comment by MrJustreborn** [comment]
Oh okay, that makes sense.
