### ISSUE TITLE
Some primitives cause failed export

### ISSUE THREAD

**Issue by Hezkore** [KhronosGroup/glTF-Blender-Exporter#139]
If I just add, for example, a _cylinder_ to my blender scene, then try to export to gLTF 2.0, the resulting model doesn't open in any application.

Sometimes, adding a _cube_ to an existing scene will cause it to no longer export.

Here's an example of it happening in Blender 2.79 with the latest gLTF 2.0 Exporter:
![GIF - Export Problem](https://user-images.githubusercontent.com/1727541/34425152-bd769e24-ec29-11e7-8370-ebe1a1e621ab.gif)

As you can see, the _cylinder_ just won't open, but when exporting a _cube_; it does work.
I've tried to open the model with lots of different applications and they all fail.

Here's a model with the issue, it's a simple _cylinder_.
[test.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1592258/test.zip)

**Comment by lexaknyazev** [comment]
The exported file passes validation and renders fine in Babylon and three.js:
![image](https://user-images.githubusercontent.com/3479527/34433207-396809f6-ec97-11e7-8b8f-babc442efd36.png)

![image](https://user-images.githubusercontent.com/3479527/34433211-42dee20c-ec97-11e7-846a-1922e7da3188.png)

@bghgary @sbtron Could you check with Windows tools?

**Comment by donmccurdy** [comment]
@Hezkore what different applications are you trying to open the file in when it fails?

**Comment by Hezkore** [comment]
Every application that comes with Win10 (3 different)
And another viewer I've forgot the name of (I'll report back once I'm home again)
Also a 'online' viewer for gLTF.
I also tried loading it with the coding language I use called Monkey 2, but gLTF support is new there.

**Comment by donmccurdy** [comment]
Ok thanks. The file is working correctly on https://gltf-viewer.donmccurdy.com/ as well, so most likely the issues are in these programs, or perhaps they don't support glTF yet.

**Comment by emackey** [comment]
@Hezkore The Win 10 applications mostly deal with GLB files (the bundled glTF files) directly, not the un-bundled glTF+bin combo.  The exporter has an option for that, try that instead.

**Comment by Hezkore** [comment]
They all claim to support gLTF, but I guess not fully heh.
"Qtek viewer" was the name of one of them.
And I've tried GLB as well, but same result.

I reported the issue on Monkey 2, a fix has since been pushed and it now loads the model.
In Monkey 2's case the fix was apparently "[added] support for ubyte indices."

So I guess my issue is resolved!

**Comment by bghgary** [comment]
@lexaknyazev 
> @bghgary @sbtron Could you check with Windows tools?

Most of the Windows apps don't support ubyte yet but they will once the support makes it through the rings.

3D Builder crashes when ubyte array has values greater than 127. This will be fixed in the next update.

We will also add some unit test models to [glTF-Asset-Generator](https://github.com/bghgary/glTF-Asset-Generator) that specifically test the boundaries of unsigned/signed.

**Comment by emackey** [comment]
No actions for the Blender exporter to take here then?  Can we close this?

**Comment by donmccurdy** [comment]
I think so. If there's a place to report bugs on the Windows apps that would be helpful to know though. :)

**Comment by Hezkore** [comment]
I think there's a "feedback hub" on the Windows 10 store.
Might just be if you're part of the Microsoft developer program, not sure.
