### ISSUE TITLE
.glb export not working

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/glTF-Blender-Exporter#14]
I seem to be getting this error

![image](https://user-images.githubusercontent.com/967499/27360886-b93a2d7c-55d8-11e7-8cf0-f63306dfdbb9.png)

Is it expected to work yet?

**Comment by UX3D-nopper** [comment]
Yes, GLB export is working.
Code was broken after adding/fixing the buffer allignment issue.
GLB export is fixed here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/e7e035b6231f1edbe16c586a099574d86265e7c7
