### ISSUE TITLE
Batch export support

### ISSUE THREAD

**Issue by swiftcoder** [KhronosGroup/glTF-Blender-Exporter#141]
It would be nice if the Blender glTF exporter supported a batch mode, where each separate object/group is exported to a separate file.

The default Blender FBX exporter supports this, and it is a great time saver for 3D tiles or other such cases where it is more convenient to edit a set of related objects as a single Blender document.

**Comment by donmccurdy** [comment]
Development has moved to the new repository (https://github.com/KhronosGroup/glTF-Blender-IO) which is included in Blender 2.8. Batch export is possible by scripting (see https://blender.stackexchange.com/questions/5382/export-multiple-objects-to-obj) but I don't think we will add a dedicated feature for it. Or at least not yet, until the exporter is more stable.
