### ISSUE TITLE
Apply Modifiers should maybe skip the armature modifier

### ISSUE THREAD

**Issue by Nehon** [KhronosGroup/glTF-Blender-Exporter#142]
This is more an enhancement. I've been caught several times by this issue.
When you check the Apply Modifiers, the armature modifier will be applied too.
If you have an animation with a selected frame, the mesh will be exported with the pose applied. This will result in wrong skinning as the mesh does not match the bind pose.
It's all logical and expected, but it kind of ruin the option when you have a rigged model with animations.
Most often you will have a mirror modifier that it's nice to apply, else you'll have only half the mesh exported, but you don't want the armature to be applied to have proper skinning.
So you have to apply the mirror manually and export without the "Apply modifers", which is too bad because you loose the ability to go back on this part of the model.
Another work around is to disable the armature modifier before exporting. It works.... but you have to remembrer it every time you export and that's frustrating when you work with iterations...

**Comment by donmccurdy** [comment]
Looks like the FBX exporter just skips armature modifiers, even when "Apply Modifiers" is selected. Maybe we should do the same...

**Comment by donmccurdy** [comment]
Fixed in new import/exporter, https://github.com/KhronosGroup/glTF-Blender-IO.
