### ISSUE TITLE
Dark models and different results in viewers

### ISSUE THREAD

**Issue by tkazik** [KhronosGroup/glTF-Blender-Exporter#143]
Hi

I recently wanted to switch all my models to the 2.0 version and no longer use the obj2gltf pipeline. The export runs fine, however I am running into some weird color/darkness issues with the newly exported models. Generally, all models now look darker and also quite different in the viewers:

![donmc](https://user-images.githubusercontent.com/15689124/34523520-2944a9bc-f098-11e7-8603-d944623b5b56.png)
![babylon](https://user-images.githubusercontent.com/15689124/34523525-2b33e8c8-f098-11e7-9cda-aa72a9f1da53.png)
![virtualgis](https://user-images.githubusercontent.com/15689124/34523528-2e2d3c50-f098-11e7-9a93-190ecfa59ba8.png)

Using the pipeline, the model looks much brighter:
![virtualgis_obj2gltf](https://user-images.githubusercontent.com/15689124/34523547-3b93049c-f098-11e7-88f5-430ed67c0984.png)

Here you also find the model
[G6000.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1600555/G6000.zip)

I greatly appreciate any hints or inputs! Thank you very much

**Comment by UX3D-nopper** [comment]
At first, the main issue causing the difference is, that all scenes probably are using a different environment map for lighting.
Furthermore, we also noticed, that the different web viewers are slightly interpreting the PBR parameters differently. This also results in a different visual output.

As this is no issue with the exporter, I close this issue. If you want to continue this discussion, I recommend the discussion on thhe glTF specifcation GitHub repository.

**Comment by donmccurdy** [comment]
Normal that lighting may vary, but if different web viewers are interpreting PBR materials differently that would be a bug in the viewers, yes? What differences did you find?

**Comment by UX3D-nopper** [comment]
From a quick investigation, three.js has the biggest difference - especially with metallic materials.
If you e.g. use Substance Painter and/or Blender with the same environment, in three.js (and other glTF 2.0 renderer) the ouzput should look to 99% the same. Please try it out with the provided field.hdr environment texture.

**Comment by emackey** [comment]
> From a quick investigation, three.js has the biggest difference

@donmccurdy This may warrent its own issue, likely in one of the ThreeJS repos.  Take a look at the MetalRoughSpheres especially, in the gltf-test demos or in VSCode.  Babylon, Substance Painter, and Blender are all mostly in agreement that mirror-like reflections only happen at the smoothest end of the roughness scale, but ThreeJS shows somewhat clear reflections even at mid to high roughness values.  This makes most PBR models I've seen look a lot smoother and shinier in ThreeJS than in other engines, and might be considered a possible bug.

**Comment by donmccurdy** [comment]
✅ https://github.com/mrdoob/three.js/issues/13107

**Comment by McNopper** [comment]
Very good reference:
https://www.allegorithmic.com/pbr-guide
