### ISSUE TITLE
Add ability to use a separate roughness and metalness map in the principled node.

### ISSUE THREAD

**Issue by nonfatmatt** [KhronosGroup/glTF-Blender-Exporter#144]
Right now the glTF exporter takes a lot of extra work to use when used with the Substance suite and game engines like Godot because it doesn't allow for a separate grayscale roughess and metalness map.  Substance by default exports 2 maps for roughness / metalness and I find myself having to combine them into the red/green channels of a new texture in Gimp/Krita/PS.  I'm not sure if it would break with the glTF format or not, but it just seems better to follow convention of other software and allow for separate maps instead of requiring a non-trivial amount of work when authoring / using textures with glTF.

**Comment by donmccurdy** [comment]
> Substance by default exports 2 maps for roughness / metalness and I find myself having to combine them into the red/green channels of a new texture in Gimp/Krita/PS...

It would be a good enhancement for the exporter to automatically merge these maps, I agree.

> I'm not sure if it would break with the glTF format or not...

The glTF format does require that the maps be merged in the final asset, but there's no reason authors should need to do that manually, it's reasonable to expect exporters and converters to do it. What issue are you seeing with Godot? Once the glTF file is created with a packed roughness/metalness map, Godot should be able to work with that or else it's a bug in their glTF support.

**Comment by nonfatmatt** [comment]
At this point, how hard would it to be to append this to the glTF standard? It seems to be a format that is designed with simplicity in mind, so having an extra step every time something is exported seems to be counterintuitive.

**Comment by donmccurdy** [comment]
Keep in mind that unlike COLLADA or FBX, glTF is a runtime transmission format. Packing textures together improves performance significantly, and the top priority is simplicity and efficiency for loading and rendering. So since textures should be packed, we want that work to be done by the authoring tool and not at rendering time by the client. 

> ...so having an extra step every time something is exported seems to be counterintuitive.

There should not be any extra step for users, any glTF exporter should merge maps during export. Support for the principled node in glTF-Blender-Exporter is still a work in progress (you may want to use the glTF metal/rough nodes included with the exporter, meanwhile) but eventually merging metal/rough maps will happen automatically.

**Comment by nonfatmatt** [comment]
Ok, that that makes things clearer. 

I tried two scenarios today with Godot 3.

1) exporting a combined (roughness / metallic in blue / green channels) map using the 'proper' pin on the glTF shader

2) connecting gray scale roughness and metalness maps into the roughness / metalness factor pins on below the pin that takes the combined map

Godot handled case 1 fairly well.  However, it seems that there are two possible ways for the channels in the combined map to be interpreted.  The first set of documentation I read for glTF indicated that metalness went into the red channel while the roughness went into the green channel.  However, now it seems that the docs have been updated to say that metalness goes into green and roughness into blue.  So, this seems to be an error on the part of Godot.  However, I'm not sure which version of the documentation is correct. If you could tell me which variation is correct I can open up an issue over at the Godot side.

Case 2 might be a good way to handle a workflow using separate metalness / roughness maps using the logic that if maps are plugged into the metalness and roughness pins then they should be either a) combined in the final output or b) pulled into the engine as separate maps.  I tend to like case b) as it lets the map be edited separately without the need to re-export.

Another issue I ran into is that for some reason the Blender exporter auto converts textures into .png files and copies them to the export directory.  While I like the fact that it automatically copies textures, I was using .tga files, so I would like the format to be consistent because Godot automatically reconverts .png files leading to time and quality loss.  I'm not sure if I should open a separate issue about this.

Either way, good job on the exporter, it's a lot easier to use than the nightmare that is .fbx.

**Comment by emackey** [comment]
Couple of comments:

* It's roughness in G, metalness in B, [specified here](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessmetallicroughnesstexture).  This was done to leave the R channel available in case users wanted to store the occlusion map there to save space.

* Substance added support for exporting to glTF format.  If you select this during the export process, Substance will automatically combine the maps together in the appropriate way, occlusion-roughness-metallic.  If you don't have a new enough version of Substance, you can [configure this export manually like this](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md#substance-painter).

* TGA images are not supported in glTF.  Only JPG and PNG are allowed without some kind of extension.  Still it would be nice to have the option, particularly for JPG files, to not decode and re-encode the images during the export.

**Comment by oparisy** [comment]
Out of curiosity: are there plans in Blender 2.8 to upgrade texture painting to modern, PBR standards and ease such authoring? Especially since it seems to me some common choices for textures channels organization start to emerge due to existing authoring tools and "consuming" engines?

**Comment by donmccurdy** [comment]
I believe this has been fixed in the new importer/exporter: https://github.com/KhronosGroup/glTF-Blender-IO.
