### ISSUE TITLE
Custom Properties support

### ISSUE THREAD

**Issue by feiss** [KhronosGroup/glTF-Blender-Exporter#15]
Another useful feature could be to export object's _Custom Properties_ metadata. This could be stored in the [node.extras](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#nodeextras) glTF2 field.

(Sorry for keep asking stuff, I just don't see this in the readme features table, and maybe is something you didn't think of)

**Comment by UX3D-nopper** [comment]
No, please keep asking stuff! I just forgot it :-) We will add it.

**Comment by UX3D-nopper** [comment]
Available since:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/0835c60fffb153a0c4563c35ab72044bc5830d37

**Comment by feiss** [comment]
That was fast, thanks! :+1:
