### ISSUE TITLE
Skeletal meshes + animation Actions support in the nearest future ?

### ISSUE THREAD

**Issue by motorsep** [KhronosGroup/glTF-Blender-Exporter#150]
I am wondering if this exporter will support skeletal meshes + animation Actions in the nearest future (for Blender 2.79).

Thanks beforehand

**Comment by donmccurdy** [comment]
Hi @motorsep — skeletal meshes / skinning are supported now. Animation actions can be used, but only one will be exported. Later we plan to support multiple actions per mesh: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/112

This may be helpful: https://www.donmccurdy.com/2017/11/06/creating-animated-gltf-characters-with-mixamo-and-blender/

**Comment by oparisy** [comment]
I take this opportunity to ask for a clarification.

My understanding is that the issue with respect to exporting (multiple) Blender animations to glTF is that some of them are subject to interpretation, especially in the NLA context.

In this regard, how do exporters to other formats fare? What choices did they make?

More generally, why are animations a sore point while geometries or materials as an example seem defined without ambiguities?

I reckon that this is as much an historical as a technical question... But indeed I lack this perspective.

Regards,
Olivier.

**Comment by oparisy** [comment]
I re-read #39 and see that this was explained there at length (the NLA part especially). I was wondering if an issue was raised at Blender with respect to the nondeterministic NLA behavior?

**Comment by donmccurdy** [comment]
I'm not sure if an issue has been raised with Blender before. About other formats, FBX does not allow multiple animations to my understanding, so typically you'd export the model and each animation to separate files. COLLADA does allow multiple animations, but there are differences in how it represents them vs Blender. Even within Blender, it is not always obvious how actions/armatures/objects are interlinked, so this presents a challenge for any export format, and the formats need to work with other tools beyond Blender too, of course.

Anyway, we do hope it this will be fixed in the near future — multiple actions at least, I'm not sure how NLA will be handled yet.

**Comment by motorsep** [comment]
Not quite true about FBX. I create bunch of Actions (which is a standard
workflow) and export to FBX. When I bring FBX into UE4 or Unity, I get
skeletal mesh and multiple individual animations, as expected.

**Comment by motorsep** [comment]
@donmccurdy I can provide FBX (and corresponding .blend file) with multiple animations, if that would be of any help.

**Comment by motorsep** [comment]
Here is a video showing me exporting from Blender and importing into UE4 (so that export/import settings are known).

https://www.youtube.com/watch?v=tHbaQeopVTM

Scene was setup in Blender 2.79 official release and represents classic workflow of an animator (one anim per Action), FBX exporter is Blender's official and FBX output hasn't been fiddled with. Everything is out of the box, so to speak.

ZIP file contains FBX and .blend files:
[FBX_multi_anim_export_sample.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1662388/FBX_multi_anim_export_sample.zip)

**Comment by donmccurdy** [comment]
Here's another example, from Sketchfab:

[lain-20_blender.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1765627/lain-20_blender.zip)
[lain_20_gltf.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1765628/lain_20_gltf.zip)

Original: https://sketchfab.com/models/bf255be16da34df08d48abb5443a6706, by woopoodle. File contains two NLA tracks that should be exported as two glTF actions, but aren't working in the Blender exporter currently.

**Comment by motorsep** [comment]
Well, from game dev perspective NLA isn't even necessary when it comes to animating for game engines (both Unreal and Unity have powerful tools to create new animations using imported animations). 

Perhaps, initially, only support export of multiple Actions?

Do you happen to have an ETA for this feature ?
