### ISSUE TITLE
Blender Models exported with glTF have 3x the polygons inside of THREEJS editor.

### ISSUE THREAD

**Issue by Chase-Reid** [KhronosGroup/glTF-Blender-Exporter#151]
### STEPS:
1. Examine current tri count for current model (ex. 2,560)
2. Export Blender model (File > Export > glTF 2.0(.glb) )
3. Navigate to THREEJS (https://threejs.org/) and launch the editor
4. Import the exported .GLB blender model
5. Examine the current tri count inside of THREEJS editor (ex. 7,680)

### RESULT:
.GLB blender model has 3x the originals polys

As per above, when I attempt to import any model exported with .GLB results in 3x the polys. Ill drop some screenshots for sanity sake. Im specifically exporting .GLB.

Specs:
Windows 10
Blender v2.79
Latest glTF-Blender-Exporter

![blendertris](https://user-images.githubusercontent.com/26173435/35179532-ffac0760-fd50-11e7-8ab2-04caf962e15c.PNG)
![threejstripletris](https://user-images.githubusercontent.com/26173435/35179533-0274665e-fd51-11e7-92e5-5aded717cde0.PNG)

**Comment by donmccurdy** [comment]
I think the threejs editor is calculating this incorrectly. Creating a simple torus (1152 tris) in Blender I get the same result (editor shows 3x triangles as Blender) but inspecting the geometry after loading into https://gltf-viewer.donmccurdy.com/ (also using threejs) shows:

<img width="454" alt="screen shot 2018-01-19 at 9 47 36 pm" src="https://user-images.githubusercontent.com/1848368/35180322-9e69aef0-fd62-11e7-80a8-dec65123705e.png">

That is, there are 3456 indices in `geometry.index`, but that's only 1152 triangles as expected.

From inspector code: 

https://github.com/mrdoob/three.js/blob/e5ebbfa3c34e0e436231be3a8bf527f838a4b7ce/editor/js/Viewport.Info.js#L49-L68

... looks like it's triple-counting.

**Comment by donmccurdy** [comment]
Oh, do note though that your _vertex_ count could increase on export, e.g. when smoothing is turned off. If that's an issue we can probably change the behavior... but triangle count should be stable.

**Comment by donmccurdy** [comment]
Should be fixed in next three.js editor release.

**Comment by Chase-Reid** [comment]
Thanks for addressing this issue. Its good to know im not the only one experiencing this issue. I look forward to the next release!
