### ISSUE TITLE
Must uncheck "Convert Z up to Y up" for use with three.js

### ISSUE THREAD

**Issue by Octavector** [KhronosGroup/glTF-Blender-Exporter#154]
Tested on Windows Firefox and Mac Chrome.

I have provided all working files and examples (including Blender file) here:

[https://waistcoat.it/movecamera.zip](https://waistcoat.it/movecamera.zip)

When exporting as .glb, if the "Convert Z up to Y up" is left checked, the camera animates correctly but traverses in the wrong direction (to the left). If unchecked, the camera moves forwards in the correct direction.

In the zip are two glb files:
1. movecamera-convertZchecked.glb
2. movecamera-convertZNOTchecked.glb

Simply swap the two filename references in the gltf.js file to see the results. The only change between these two files is the unchecking of the "Convert Z up to Y up" option.

**Comment by donmccurdy** [comment]
Thanks for the details!

I'm getting odd results here... opening the demo to `movecamera-convertZchecked.glb` I see nothing but a blue background, while `movecamera-convertZNOTchecked.glb` shows the right result.

I can drag _either_ file into http://gltf-viewer.donmccurdy.com/ and the result looks correct to me after selecting *Cameras* -> "Camera". (this is three.js r89, and some fixes to cubic spline interpolation are on three.js dev branch, so this wouldn't necessarily match your demo)

I also have a [glTF quicklook plugin](https://github.com/magicien/GLTFQuickLook), when opening _either_ model in that, the camera goes way off to the left... I'm not sure how release-ready that quicklook plugin is, but in any case something is a bit off here..

**Comment by Lightnet** [comment]
Is there way to have option to setup those axis? Up and forward that depend which application that support default that different from way it setup. Example Godot Engine 3.0 which to work but it face other direction.

**Comment by donmccurdy** [comment]
@Lightnet in glTF, +Y should always be up and +Z should always be forward. Anything else is an invalid glTF file, and the goal here is that Godot Engine should know what to expect and import correctly on their end. If that's not the case, you may want to file a bug with Godot.

The issue here is that the Blender exporter (or Blender itself) are not properly able to convert from Blender's coordinate system to glTF's.

**Comment by donmccurdy** [comment]
Confirmed I get the same result in threejs and BabylonJS, so I think this is an exporter issue.

**Comment by donmccurdy** [comment]
This isn't quite exact in the new exporter (https://github.com/KhronosGroup/glTF-Blender-IO/) but the result does match regardless of +Y/+Z settings, and it seems much closer. I think the remaining issue might have to do with camera perspective, and arguably that should be overridden in threeJS with the actual viewport size.

Closing for now but feel free to reopen in the new repo if things don't seem right.
