### ISSUE TITLE
Exporting rigged meshes does not produce expected result

### ISSUE THREAD

**Issue by mwmwmw** [KhronosGroup/glTF-Blender-Exporter#155]
Unrigged... Everything looks fine (well, 'fine' with some z-fighting and issues I'll solve later).
![image](https://user-images.githubusercontent.com/889851/35287955-c9aea028-0020-11e8-8663-2707580b798d.png)

As soon as I attach a simple armature and parent some objects, things get weird. The head, torso, and hips have all been attached to a bone.
![image](https://user-images.githubusercontent.com/889851/35288105-1adb0ce8-0021-11e8-9da9-28ef0a568795.png)

I have other rigged other meshes with multiple objects and they seem to work. I have tried to rig this from scratch a few times now trying different approaches... and as soon as I add an armature things go crazy. 

At first, I thought it was some deltas or origin offsets, but I normalized everything (Control-A) and I have other versions where I didn't do that. No matter what... adding an armature with a single bone, knocks the objects they're parented to into weird positions. 

I have included all my exports and source files if you want to take a look. Everything looks fine in Blender and the GLTF viewer says there are no issues. Not sure what I might be doing wrong so if you have any insight into what might be causing this. 

The .GLB files
[Skeleton.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1656832/Skeleton.zip)

Blender source files
[SkeletonBlends.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1656837/SkeletonBlends.zip)

I'm on Blender 2.79 and I pulled latest from the exporter this morning.

**Comment by donmccurdy** [comment]
I think the issue you've run into is discussed here: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/74. Currently the way to work around that is:

> ...to create joints and weights for this mesh and give full weight to the bone it is assigned to.

Hopefully this can happen automatically in the future.

**Comment by mwmwmw** [comment]
Ohh, I see. 

The bone needs a vertex group to control that object and can't just be assigned to a node/object. That makes sense as to why my mesh-only rigs work fine. 

Yes, it's working. Thank you. 

This was the last thing I needed to finish a blog post that documents the entire process of creating a 2D character, animating it in Blender, then exporting it to GLTF.

**Comment by donmccurdy** [comment]
Awesome, glad it's working :)
