### ISSUE TITLE
Exporting LOD groups for static (non-skeletal) meshes - possible ?

### ISSUE THREAD

**Issue by motorsep** [KhronosGroup/glTF-Blender-Exporter#156]
Until recently Maya was the only app that supported LOD groups export into FBX (afaik):

https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Maya/files/GUID-90307993-D898-4BFA-9E5E-D7F96EFAFAAD-htm.html

Then eventually someone figured out LOD groups support for Blender FBX exporter (via Empty and parenting/naming):

https://forums.unrealengine.com/community/community-content-tools-and-tutorials/119508-cyaoeu-s-bag-of-blender-tricks?146531-cyaoeu-s-bag-of-Blender-tricks=&viewfull=1

I am wondering if something similar can be added to glTF exporter, assuming glTF format supports such thing as several LODs per object.

Thanks beforehand

**Comment by donmccurdy** [comment]
The glTF format doesn't have a concept of LODs built in, although I expect that will come with an extension eventually. Microsoft has designed such an extension, although it's (currently) not meant for broader use. Once a viable extension exists, I hope support could be added to this Blender exporter. See: https://github.com/KhronosGroup/glTF/issues/1045

**Comment by donmccurdy** [comment]
Going to close this issue, as we cannot implement here until the extension exists for glTF. Feel free to chime in on https://github.com/KhronosGroup/glTF/issues/1045 to give feedback on this. :)
