### ISSUE TITLE
Error when exporting skinned mesh

### ISSUE THREAD

**Issue by Arcnor** [KhronosGroup/glTF-Blender-Exporter#16]
With the attached file, I'm getting the following error:

![boxskinned_blend](https://user-images.githubusercontent.com/28616/27467689-dbf40cc4-5827-11e7-8d5e-ed61c2da5665.jpg)

I might have done something wrong in Blender, as I'm still a beginner, but I guess the plugin should not explode no matter what :D

[BoxSkinned.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1096825/BoxSkinned.blend.zip)

**Comment by UX3D-nopper** [comment]
No, it should not crash. Having a look at it.
Thank you for filing the bug plus providing the example file.

**Comment by capitalknew** [comment]
I have same issue with any model export (Rigged Chess, Sponza).
![2017-06-23](https://user-images.githubusercontent.com/28119043/27482234-3b9e263e-5853-11e7-961b-a8dd9244476e.png)

**Comment by UX3D-nopper** [comment]
Can you guys please try out this commit:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/2b6f43a2e2209cce944a68a18bf8f97e3329f82f

**Comment by UX3D-nopper** [comment]
Also, for the BoxSkinned, you need first to apply manuallly the subdivision surface modifier - unless you tesselate automotically your model.

**Comment by capitalknew** [comment]
Sponza export error, I also tried export chess model but no materials. 
![2017-06-23 1](https://user-images.githubusercontent.com/28119043/27483252-3134f4ee-5857-11e7-9206-8c18d528d52c.png)

**Comment by UX3D-nopper** [comment]
Regarding the materials, you need to enable experimental blinn phong. Otherwise, as no PBR node is used, no material is exported. This is correct behaviour.

**Comment by UX3D-nopper** [comment]
Can you pls attach exactly this Sponza test file?

**Comment by capitalknew** [comment]
Sponza model https://filebin.net/1lp67xuw6an749wt

**Comment by UX3D-nopper** [comment]
Thx, but I need exackty this Blend file.
The reason for the crash is, that Blender is in some state and cant execute the command.

**Comment by capitalknew** [comment]
I tried this Sponza blend https://github.com/SaschaWillems/VulkanSponza
Not works Blinn-Phong export.

**Comment by UX3D-nopper** [comment]
On my side, I can export the model, with BlinnPhong (the glTF is in the ZIP file);
[sponza.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1097914/sponza.zip)

Can you please send me exactly the Blend file, which is causing the crash?

**Comment by capitalknew** [comment]
This is PBR (techniqually), but I can't export. No .max support by Blender, not export .fbx to .gltf.
![2017-06-23 2](https://user-images.githubusercontent.com/28119043/27484318-68494c7e-585b-11e7-9989-b4aa6c01b8a8.png)


https://www.cgtrader.com/3d-models/sports/game/pbr-chess-set

**Comment by UX3D-nopper** [comment]
The reason, why it does not export, that you manage to bring Blender in some state, where this crash occurs. If you send me this or a similar file, where exactly this crash occurs, would be great.

Regarding PBR, you need to create the cylces material nodes. All te required textures (metallic roughness and so on) should be included.

**Comment by UX3D-nopper** [comment]
We will write a tutorial and documentation, on how to do this. But I cannot explain on how to do this right now.

**Comment by capitalknew** [comment]
I sent sponza.obj, I tried to resave to ".blend" when import this Sponza. Don't know why, sometimes exports, sometimes not.

**Comment by UX3D-nopper** [comment]
Okay, I close this bug - but do open another one regarding the other crash.

**Comment by UX3D-nopper** [comment]
See https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/17

**Comment by Arcnor** [comment]
Thank you!
