### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by AhmedSalih3d** [KhronosGroup/glTF-Blender-Exporter#161]
I am new to scripts and github and I don't understand where to get the file I need to put into my Scripts/Addon folder - I am at this link

https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/scripts

What do I need to do from here?

Sorry for bothering.

**Comment by AhmedSalih3d** [comment]
Found this video, should work now.

https://www.youtube.com/watch?v=2aByUxuL40s

**Comment by donmccurdy** [comment]
Thanks for letting us known, @AhmedSalih3d — I've made some updates to the [installation instructions here](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/scripts). If anything is still unclear, please feel free to suggest improvements. :)
