### ISSUE TITLE
I can't check the add-on

### ISSUE THREAD

**Issue by Raamyy** [KhronosGroup/glTF-Blender-Exporter#162]
I changed Blender scripts folder to D:\glTF-Blender-Exporter\scripts And it appeared in the Add-on tab , but the problem is that I can't check the box i have clicked it and no change happens.

And i tried to type
``` bpy.ops.wm.addon_enable(module="io_scene_gltf2")```
 in the console and the feedback is:
```
addon not found: 'io_scene_gltf2'
{'CANCELLED'}
```
I hope somebody helps,
Thanks in Advance.

**Comment by donmccurdy** [comment]
Same issue here, on macOS. I've been installing by copying the folder into the original scripts/addons directory. Symlinks also didn't work.

**Comment by arkanoid87** [comment]
Same here

copied the io_scene_gltf2 folder in ~/.blender/scripts (also tried ~/blender/scripts) but the entry does not appear in the add-ons list after adding /Users/<uname>/.blender/scripts/ to the File tab.

OSX 10.11.6
Blender 2.79

**Comment by Vinc3r** [comment]
If you remove your io_scene_gltf2 copy-pasted folder, then [make a zip of the exporter](https://i.imgur.com/ojl6CnL.png), and try to install it through the classic [Install Add-on from File](https://i.imgur.com/2Ws8kHT.png), is the issue still here?

**Comment by donmccurdy** [comment]
@arkanoid87 on macOS, the folder where `io_scene_gltf2` should be placed should be something like:

```
/Applications/blender.app/Contents/Resources/2.78/scripts/addons/
```

**Comment by Raamyy** [comment]
I closed and reopened the program many times and suddenly it was checked.
Thanks !

**Comment by moll** [comment]
For others experiencing this or a related "Cannot find module" issue --- try restarting Blender after copying the extension to ~/.config/blender/2.79/scripts/addons. I assume Blender's not including its addons directory for Python to find somehow without a restart.

**Comment by donmccurdy** [comment]
Resolved in https://github.com/KhronosGroup/glTF-Blender-IO.
