### ISSUE TITLE
Seem like there is a problem viewing the models created with this plugin through facebook on mobile

### ISSUE THREAD

**Issue by D1ll1ng** [KhronosGroup/glTF-Blender-Exporter#165]
Seem like there is a problem viewing the models created with this plugin through facebook on mobile,
i used another website to convert my 3d file and then i worked fine.

**Comment by emackey** [comment]
Facebook imposes a number of limits on upload, listed here:

https://developers.facebook.com/docs/sharing/3d-posts/asset-requirements

Please check your model to make sure it stays within these limits.  I've used this exporter and uploaded the result to Facebook, so I don't think there are any changes needed here.

**Comment by donmccurdy** [comment]
Also see: https://github.com/mrdoob/three.js/issues/13397

There are certain bugs on the Facebook mobile viewer, which they're fixing soon. If you create a file with this plugin and see errors when dragging it into [the Khronos validator](http://github.khronos.org/glTF-Validator/), or [Facebook's validator](https://developers.facebook.com/tools/3d/validation) (which should be largely the same) that would indicate a problem with this plugin. If so, please post your source `.blend` file if possible (you can drag .ZIP files into GitHub comments).
