### ISSUE TITLE
 problem with emissive node when exporting gltf2 !? 

### ISSUE THREAD

**Issue by emrum** [KhronosGroup/glTF-Blender-Exporter#170]
reporting 
problem with emissive node when exporting gltf2  !? 
----
additional note: 
emissive-factor-input of gtlf2 emissive-node wants a color (RGB), not a value (0..1)
that doesnt appear appropriate. 

-----------------------------------------------
Traceback (most recent call last):
  File ".config/blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 328, in execute
    return gltf2_export.save(self, context, export_settings)
  File .config/blender/2.79/scripts/addons/io_scene_gltf2/gltf2_export.py", line 84, in save
    generate_glTF(operator, context, export_settings, glTF)
  File ".config/blender/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2904, in generate_glTF
    generate_materials(operator, context, export_settings, glTF)
  File ".config/blender/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2457, in generate_materials
    emissiveFactor = get_vec3(blender_node.inputs['EmissiveFactor'].default_value, [0.0, 0.0, 0.0])

KeyError: 'bpy_prop_collection[key]: key "EmissiveFactor" not found'

**Comment by donmccurdy** [comment]
Could you share your `.blend` file reproducing this issue, or take a screenshot of the node graph? You can drag a .ZIP or images into GitHub comments.

> emissive-factor-input of gtlf2 emissive-node wants a color (RGB), not a value (0..1)

EmissiveFactor has separate r/g/b channels in glTF 2.0. You can use this as a plain emissive color, and it also multiplies against the emissive texture (if any).
