### ISSUE TITLE
request: disable image export 

### ISSUE THREAD

**Issue by emrum** [KhronosGroup/glTF-Blender-Exporter#171]
GLTF2 exporter 
writes images to directory. 
I am missing an option to disable this slow feature.

**Comment by emackey** [comment]
There's another use for this, too:  Sometimes the source images are JPG files or pre-existing PNG files that the author doesn't want to decode and re-encode.  This is especially true for images that have been connected to the custom Cycles node, as those images must already exist on disk and don't need to be rewritten.

It's especially bad when this exporter reads in a JPG, decodes it, and then re-encodes as PNG for either re-writing to disk or embedding in GLB.  The result has the disadvantages of both JPG artifacts and PNG's large size in the same file.

It would be nice to have the option to keep (in the case of glTF) or embed (in the case of GLB) the pre-existing image files verbatim.

**Comment by emackey** [comment]
Also talked about in #124.

**Comment by donmccurdy** [comment]
Fix in progress: https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/181
