### ISSUE TITLE
Export Camera - Position is reseted to 0,0,0

### ISSUE THREAD

**Issue by Halocom** [KhronosGroup/glTF-Blender-Exporter#173]
Hello, 
when choose "Export cameras" and view the node imported in Three.js, i see the location of the camera is lost, it's reseted to location 0,0,0
;-)

**Comment by emackey** [comment]
I think you may have to take extra steps in ThreeJS to place its camera where the glTF camera node is.

I don't think there are any changes needed to this exporter to be able to export a camera node, so I'm closing this for now.
