### ISSUE TITLE
Node materials

### ISSUE THREAD

**Issue by gravit22** [KhronosGroup/glTF-Blender-Exporter#175]
Is there any possibility that this addon will support nodes like color ramps or noise?

**Comment by donmccurdy** [comment]
So far as I can tell, nodes it's not possible to just get values out of nodes, as they're computed for every sample/pixel during rendering in Blender. See this [question on SO](https://blender.stackexchange.com/questions/101929/getting-the-actual-not-default-value-of-a-node-socket-that-is-linked-to-anothe?noredirect=1) for details. One workaround might be to bake the result to an image and then use the result as an image texture.

If anyone knows other options, that do not require re-implementing each node's behavior in Python, I would be curious. :)

**Comment by donmccurdy** [comment]
It doesn't seem like we can support arbitrary nodes, unless Blender has a Python API for baking the output of particular subtrees to their values. But we will try to add support for some additional nodes, like Principled BSDF and texture/UV transforms, tracked in other issues.
