### ISSUE TITLE
Using UE4-style occlusion/roughness/metallic

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#18]
I'm fumbling my way through Blender here, so hopefully this isn't a silly mistake, but it doesn't seem to be possible to do UE4-style packed occlusion/roughness/metallic textures. I've tried two approaches:

### Duplicate texture

Here, I bring in two duplicate Image Textures and use one for Occlusion, the other for MetallicRoughness. The exporter throws an error in this case.

![occlusionroughnessmetallicv1](https://user-images.githubusercontent.com/1848368/27512615-8ec306c4-58fb-11e7-8c83-67a871309f6f.JPG)

![error](https://user-images.githubusercontent.com/1848368/27512622-01010966-58fc-11e7-8999-c66b522c9085.JPG)

If I *really* duplicate the texture (make a copy of the image file, not just two nodes referencing the same image, then this works as expected, but with duplicate resources of course.

### Separate and combine channels

I separate channels and re-combine green/blue for roughness/metallic. The export is successful, but both occlusion and roughness/metallic are omitted from the glTF.

![occlusionroughnessmetallicv2](https://user-images.githubusercontent.com/1848368/27512616-952cb9c4-58fb-11e7-8be6-253df43c472d.JPG)

> ^I wired occlusion to the wrong pin here, but you get the idea.. 🙃 

Source files:

[boombox2_phong1_OcclusionRoughnessMetallic.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1100053/boombox2_phong1_OcclusionRoughnessMetallic.zip)

**Comment by McNopper** [comment]
First at all, this is the proper solution;
![grafik](https://user-images.githubusercontent.com/3677213/27514272-178a810a-5986-11e7-8db4-3d4fabf7eddf.png)
The channel splitting is happening inside the node group.

Let me check the crash, as this should not occur.

**Comment by UX3D-nopper** [comment]
There was a bug in the exporter, when the images are duplicated.
This fixes the problem:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/8fe6eb94c31f4bb1883841275beaccfc2cc78c77

In general, all the color channel splitting is happening inside the node group. Texture nodes have directly be attached to the node group. Any node graphs are not allowed, even the result looks correct in Blender.

BTW: I have Blender Python code, which is generating from a generic cycles node tree GLSL code. But this would not be glTF 2.0.

**Comment by UX3D-nopper** [comment]
Forgot to say thank you :-)

**Comment by donmccurdy** [comment]
Awesome, I was making it too hard for myself. :) Thanks!

**Comment by ByTheQuietLake** [comment]
Hello, Thanks for clearing some confusions! it has been a while but it would be nice to include the part about splitting the channels internally in the documentation and the part about how to link the occlusion/roughness/metallic to their respective nodes as  the current documentation does not state that and is a bit unclear.

**Comment by donmccurdy** [comment]
That sounds good to me, @ByTheQuietLake — do you have time to send a PR editing the documentation however makes sense to you?

**Comment by ByTheQuietLake** [comment]
@donmccurdy Sorry it took a while but I just send PR as you asked. #157
