### ISSUE TITLE
Multiple Add-on's with the same name Found

### ISSUE THREAD

**Issue by DarthMoulByte** [KhronosGroup/glTF-Blender-Exporter#183]
i follow exactly your install instructions, but ...!!!!
what is wrong ?, sorry but your instructions ase no clear, or I committed a mistake, but that it would be difficult to happen to me, i have 2 years with blender and 1 year making my own Add-on's

![2018-03-31_15-40-09](https://user-images.githubusercontent.com/24207840/38167864-0a493ee0-34fb-11e8-8d1a-14acfdb100fb.png)

**Comment by McNopper** [comment]
Think one export script is located inside the Blender install, one in your private script folder - in this case the master branch.

**Comment by donmccurdy** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO is shipping with Blender 2.8 Beta now.
