### ISSUE TITLE
Shapekeys animation export bug when keyframes are different

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-Exporter#187]
Hello,

Got a bug when : 
- There is at least 2 shapekeys
- There is animation on this shapekeys
- keyframes are different for each shapekeys.

Example : sk_ko.blend, with following keys : 
- 1 and 10 for shapekey "Key 1"
- 1 and 5 for shapekey "Key 2"

No bug exporting sk_ko, with following keys : 
- 1 and 10 for shapekey "Key 1"
- 1 and 10 for shapekey "Key 2"

In attachment : 
- file sk_ok.blend (in .zip)
- file sk_ko.blend (in .zip)
- screenshot of python error

[sk_bug.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1886108/sk_bug.zip)

![sk_bug](https://user-images.githubusercontent.com/1696020/38452129-271ebb2e-3a3e-11e8-86e6-736c6626da7a.png)

**Comment by julienduroure** [comment]
I started investigate it, and this is linked to function animate_get_interpolation (file gltf2_animate.py)

Currently, we only check that every fcurves have same number of keyframes, but didn't check if for a given keyframe, there is also a keyframe on other fcurves for the same frame. 
If it's not the case, we have to set interpolation to "CONVERSION_NEEDED".

This bug is not linked to shapekeys, because this can also happened on any transform, for example: 
- Location X: keyframes on frames 1 & 10
- Location Y: keyframes on frames 10 & 20
- No keyframes on Z ( or exactly 2 keyframes)

**Comment by donmccurdy** [comment]
Closing - both are exporting without errors in https://github.com/KhronosGroup/glTF-Blender-IO.
