### ISSUE TITLE
gltf Object exported from blender doesn't animate

### ISSUE THREAD

**Issue by shikharka** [KhronosGroup/glTF-Blender-Exporter#189]
I created an animated gltf Object and exported from blender.
But exported object doesn't animate. Moreover animating elements got disoriented
Have attached exported file and blender file for reference
I am not sure if it's an exporter issue or am doing something wrong

[animatedObj.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1889841/animatedObj.zip)

**Comment by julienduroure** [comment]
Hello,
Your cylinders are parented to a BezierCurve, and the addon didn't export BezierCurve data (exports it as non mesh node).
Evaluation time animation are not exported too.

Notes :
Curve --> This is something that eventually could be added, using algo that create mesh data from curves
Evaluation time --> Should be investigated, don't know how this can be easily converted to transform animation

**Comment by shikharka** [comment]
Is there any ongoing work to fix this?
