### ISSUE TITLE
Alpha settings

### ISSUE THREAD

**Issue by proteamer** [KhronosGroup/glTF-Blender-Exporter#19]
Hello,

![gltf_material_node_part](https://user-images.githubusercontent.com/1376014/27518934-45616f4a-59f3-11e7-95f8-51f91a1abf45.png)
Could you please explain how should alpha settings work?

I tried to change `Alpha` parameter and it led to changes rendered image in blender as I expected. However, material in exported glTF file always has **1.0** alpha in `pbrMetallicRoughness`:
```
        {
            "name" : "gray-color", 
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.25192031264305115, 
                    0.25192031264305115, 
                    0.25192031264305115, 
                    1.0
                ], 
                "metallicFactor" : 0.04025423526763916, 
                "roughnessFactor" : 0.5932203531265259
            }
        }
```

Additional note: If I set alpha directly in baseColorFactor then alpha value is exported as expected. It looks confusing because `baseColorFactor` alpha doesn't apply to rendered image in blender.

**Comment by UX3D-nopper** [comment]
Will write the documentation for it and close this ticket, as soon this is done.

**Comment by UX3D-nopper** [comment]
Okay, added documentation on how to use alpha:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/1da627761f4e3d02c307040a63d8aff87183992e
Please let me know, if there are any further questions.

**Comment by Darker** [comment]
@UX3D-nopper I still don't understand how to make glass-like transparent object. Could you please make an example (screenshot of correct node setup) in the documentation? I tried all kinds of combination without effect (the node is rendered white in gltf)
