### ISSUE TITLE
Clarify placeholder in license

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#191]
We should clarify owner of the license — LICENSE.txt currently contains:

```
Copyright [yyyy] [name of copyright owner]
```

**Comment by emackey** [comment]
@Khronoswebmaster Do you know the correct copyright string to add?

**Comment by Khronoswebmaster** [comment]
If it is to be Khronos then I believe `Copyright (c) 2018 The Khronos Group.` Also waiting for confirmation on the need for the Khronos CLA added to this repository, which I believe we do need.

**Comment by donmccurdy** [comment]
Realized I misread; the [LICENSE.txt](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/LICENSE.txt) in this repository contains the complete license along with an appendix at the end entitled "How to apply the Apache License to your work." and the placeholder text is within that section. Is it considered incorrect to include the full license, and only that bottom section should be in this repository? In any case I assume a license holder's name should appear somewhere.

**Comment by outofcontrol** [comment]
The full Apache license as you have it is correct. The text at the bottom is intended for those that clone this repository. In addition, a Click Through for the Apache 2.0 license has been added to this repository. You will note that the current PRs now require the submitter to accept the license before these PRs can be merged. Simplest way to get the contributor to sign is to comment in each PR asking them to come back and sign.

**Comment by donmccurdy** [comment]
Thanks! I think this is resolved.
