### ISSUE TITLE
Support option to output interleaved attributes

### ISSUE THREAD

**Issue by ale64bit** [KhronosGroup/glTF-Blender-Exporter#192]
Not sure how it works internally at the moment, but it seems the output GLBs always have non-interleaved vertex attributes. It would be nice to support (through a flag or checkbox in export options, etc) interleaved vertex attributes, which can result in better performance in certain cases.

**Comment by donmccurdy** [comment]
Currently I think this would be best left for a separate optimization tool, as it may add complexity to this exporter.
