### ISSUE TITLE
Draco extension

### ISSUE THREAD

**Issue by soadzoor** [KhronosGroup/glTF-Blender-Exporter#195]
Is it possible to implement the KHR_draco_geometry_compression extension to the blender exporter? That would be awesome!

**Comment by lexaknyazev** [comment]
Since the Draco encoder is written in C++, such integration would require wrapping it as a Python extension module, or loading it dynamically through `ctypes`.

Other way of getting compressed assets from Blender could be to encourage integration with cmd-line external pipeline tools.

/cc @donmccurdy @McNopper

**Comment by donmccurdy** [comment]
If someone has bandwidth to spend on this, I’d vote to create a generic glTF-glTF+Draco tool first. Maybe glTF-Pipeline or glTF-Toolkit are logical places for that, but a stand-alone lib could even be easier. There is also a JS Draco encoder.

**Comment by donmccurdy** [comment]
Related: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/327

**Comment by emackey** [comment]
Would like to get Draco added to VSCode too: https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/103.

I know there's some ongoing gltf-pipeline work by @FrankGalligan in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/353.

**Comment by soadzoor** [comment]
FYI: The draco branch is merged into the 2.0 branch on the [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/tree/2.0), and it works well ;)

**Comment by EtagiBI** [comment]
Are there any news / plans regarding Draco support?

**Comment by emackey** [comment]
Yes, it's under development now in the [glTF-Blender-IO](https://github.com/KhronosGroup/glTF-Blender-IO) repo, [Compression milestone](https://github.com/KhronosGroup/glTF-Blender-IO/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22MS+VII+-+Compression+%26+Maintenance%22)

This repo (glTF-Blender-Exporter) was combined with Julian's Importer, and the combined project was renamed to glTF-Blender-IO.
