### ISSUE TITLE
Skinned animation output depends on frame selected

### ISSUE THREAD

**Issue by Arcnor** [KhronosGroup/glTF-Blender-Exporter#20]
Related to #16 and using the same example file, I've found that depending on the frame you have selected on the editor when doing the export, your final file will look incorrect. If you select the frame 0, everything is fine. If you select the frame 60 (like I did in the example I'm attaching) your animation will look wrong (it's applying the skin to a mesh deformed from the frame you have selected, instead of the initial state)

This might even be a feature, although I'm hard pressed to find how this can work in practice 😄 
[BoxSkinnedBug.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1100677/BoxSkinnedBug.zip)

**Comment by UX3D-nopper** [comment]
It's a bug. Just looked at the code and it is obvious.
Think it is an easy fix, but I will fo it tomorrow,

**Comment by Arcnor** [comment]
Thanks, appreciated!

**Comment by UX3D-nopper** [comment]
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/1340c563b46e1a15eb4574825229548b3e1d2364 should fix this.

Will test and close if everything is fine.

**Comment by UX3D-nopper** [comment]
Okay, tested with this and some other skinned model.

**Comment by Arcnor** [comment]
Thank you!
