### ISSUE TITLE
Option to ignore Armature in the hierarchy when exporting

### ISSUE THREAD

**Issue by motorsep** [KhronosGroup/glTF-Blender-Exporter#200]
I recall when exporting into FBX, Armature becomes root bone and actual root bone becomes its child. I am sure there are use cases when you need to keep Armature as root in the export, but generally hierarchy should only include bones as that's what a game engine expects when importing skeletal models.

Instead of this in glTF: 

Armature > root > pelvis > ...

it should be like this:

root > pelvis > ...

**Comment by donmccurdy** [comment]
Thanks! This is worth looking into, but may be difficult to implement properly because there is no guarantee the hierarchy has a single root bone... Using the Armature as the root handles that implicitly, although in #166 it is causing issues as well...

**Comment by motorsep** [comment]
Actually, when you add an Armature in Blender, a single bone is automatically added to the Armature. Sow when you export and remove Armature, you will end up with a single bone. 

Also worth mentioning that some options are gonna have to imply that artist who is exporting into glTF knows what (s)he is doing ;) (thus having bones in the Armature)

**Comment by donmccurdy** [comment]
I'm not sure about this option, but we won't be adding new features to this repository. We're working on sorting out remaining skinning issues in the new repository (https://github.com/KhronosGroup/glTF-Blender-IO) and once that is done, feel free to open an issue there if it's still needed.
