### ISSUE TITLE
Trying to access missing skin when loading

### ISSUE THREAD

**Issue by dantoye** [KhronosGroup/glTF-Blender-Exporter#202]
[default.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1945492/default.blend.zip)

![image](https://user-images.githubusercontent.com/6707696/39226872-01cd91b8-480a-11e8-9be1-99050d8b9c89.png)

Note the skins is a 13 element array, but nodeDef.skin = 13

![image](https://user-images.githubusercontent.com/6707696/39226880-19032fdc-480a-11e8-90c3-599145534799.png)

**Comment by dantoye** [comment]
It occurred to me this may be a bug with the threejs glTF importer, not the exporter. However it's beyond my knowledge to determine which is the cause.

**Comment by donmccurdy** [comment]
For some reason your `.blend` file is crashing Blender 2.79 for me... could you post the output `.gltf` file?

**Comment by donmccurdy** [comment]
Still crashing Blender in 2.8, unfortunately I can't reproduce this. 

I'd suggest trying the new exporter/importer (https://github.com/KhronosGroup/glTF-Blender-IO), which comes with Blender 2.8. Future development will be happening there.
