### ISSUE TITLE
Coordinate system mapping in developer documentation

### ISSUE THREAD

**Issue by 4DA** [KhronosGroup/glTF-Blender-Exporter#204]
[developer docs](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/developer.md#coordinate-system-mapping) state this:
> glTF 2.0 also uses a right-handed coordinate system, but with x point right, y point up and **z backward**.

On the other hand, GLTF [spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#coordinate-system-and-units) says this:
> The front of a glTF asset **faces +Z**.

Do developer docs imply that "backward" is the direction **away** from user into computer monitor?
If so, i think developer docs can be made concise stating what direction does the asset face.

**Comment by emackey** [comment]
That mapping table in the docs looks wrong.  Blender's +Z (Blender up) gets mapped to glTF's +Y (glTF up).  Blender's -Y is actually (per ortho view presets, such as Numpad 1) considered Blender's "front", so Blender -Y gets mapped to glTF's +Z (glTF forward).

This all amounts to a simple 90 degree rotation about the X axis, so not as complicated as it sounds.

We should fix the docs.

**Comment by donmccurdy** [comment]
New docs (https://docs.blender.org/manual/en/dev/addons/io_gltf2.html) mention glTF convention is +Y up. More details would be welcome but not high priority in my opinion.
