### ISSUE TITLE
No ByteStride

### ISSUE THREAD

**Issue by ladiszlai** [KhronosGroup/glTF-Blender-Exporter#205]
Is it normal that in my exported glTF file there is no ByteStride value in the vertex BufferView ?

**Comment by ale64bit** [comment]
As far as I understand, the byte stride is not mandatory (see the schema of buffer views). Moreover, the spec says: 

> "Buffer view could have byteStride property. It means byte-distance between consequential elements. This field is defined only for buffer views that contain vertex attributes."

If the byte stride is not specified, you assume the stride is the size of the underlying component type of the accessor. Again, see the full details in the [data alignment section](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#data-alignment): 

> When byteStride of referenced bufferView is not defined, it means that accessor elements are tightly packed, i.e., effective stride equals the size of the element. When byteStride is defined, it must be a multiple of the size of the accessor's component type. byteStride must be defined, when two or more accessors use the same bufferView.

**Comment by donmccurdy** [comment]
That's correct; the field is optional.
