### ISSUE TITLE
Inconsistent colorspace for baseColorFactor and COLOR_0

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#206]
After some quick tests with vertex colors and baseColorFactor, I'm seeing inconsistent results. The lighter box is using vertex colors.

| viewer | screenshot |
|---|---|
| blender | <img width="543" alt="screen shot 2018-05-01 at 10 13 39 am" src="https://user-images.githubusercontent.com/1848368/39483881-aa2c9674-4d28-11e8-932d-953739282d6d.png"> |
| three.js | <img width="541" alt="screen shot 2018-05-01 at 10 18 40 am" src="https://user-images.githubusercontent.com/1848368/39483998-1bd4a352-4d29-11e8-8d5e-f9e5f3b4bc71.png"> |
| babylon | <img width="634" alt="screen shot 2018-05-01 at 10 13 17 am" src="https://user-images.githubusercontent.com/1848368/39483903-bd6237d0-4d28-11e8-8389-d79dff05921f.png"> |

Likely cause: Blender [stores vertex colors in sRGB internally](https://blender.stackexchange.com/questions/82441/vertex-colors-are-wrong-value), whereas glTF specifies linear:

> In addition to the material properties, if a primitive specifies a vertex color using the attribute semantic property COLOR_0, then this value acts as an additional linear multiplier to baseColor.

Related: https://blender.stackexchange.com/questions/101156/does-blender-support-linear-colorspace-for-vertex-colors

**Comment by emackey** [comment]
So, this converter should adapt the stored values during export?

**Comment by donmccurdy** [comment]
Yes, I think so.
