### ISSUE TITLE
Name glTF meshes using Blender objects name, not Blender meshes name

### ISSUE THREAD

**Issue by Vinc3r** [KhronosGroup/glTF-Blender-Exporter#207]
If an artist name its model, he will logically named it through the object data part in Blender, and keep the default name generated in mesh data, 'cause it would be a pain to rename each time both properties in an efficient workflow.

![naming workflow](https://i.imgur.com/DHAmG7o.png)

```JSON

    "meshes": [
        {
            "name": "Cube",
            "primitives": [
                {
                    ...
                },
                {
                    ...
                }
            ]
        }
    ],
    "nodes": [
        {
            "mesh": 0,
            "name": "myObject.000"
        }
    ]

```

Here, I think the meshe should be named with *myObject.000* in it.
Maybe it's an issue if a mesh node have the same name as the nodes node? If so, why not use a pattern like this: __*objectName*\_mesh__ (so in this example: _myObject.000\_mesh_).

---

This naming convention leads for issue when objects use multimaterials, for example when the glTF file is imported in babylonJS:

![multimaterial](https://i.imgur.com/JGqVNEY.png)

Here it's not very convenient to target a precise mesh or submeshes by name. I think here it's not a babylonJS issue, but the glTF naming convention which should be enhanced.

What do you think about this idea?

**Comment by donmccurdy** [comment]
When loading the model in BabylonJS, is it doing anything with the node name `myObject.000`, or just using the mesh name? In three.js we do the opposite I think, and prefer to keep the node name instead of the mesh name.

/cc @bghgary

**Comment by Vinc3r** [comment]
Even if only BabylonJS use the *meshes* data names for now, I think it still more user-friendly to re-use the object name instead of the default Blender primitive mesh name.

About the BabylonJS gltf loader:
- if an object have only one material, the object is named as the gltf *nodes* names,
- if an object have two or more materials, the object is split into one submeshes per materials, parented to an empty object named as the gltf *nodes* names, submeshes are named according to the gltf *meshes* names with a numbered prefix (_\_0_, _\_1_, ...)

**Comment by donmccurdy** [comment]
The general mapping should probably be:

| Blender | glTF |
|---|---|
| object | node |
| mesh + 1 material | 1 mesh + 1 primitive + 1 material |
| mesh + N materials | 1 mesh + N primitives + N materials |

I recognize many users may not change the default names, but throwing away the mesh name feels odd because it does map pretty intuitively to a glTF mesh object, and so someone might naturally expect a custom mesh name to appear in their glTF export.

**Comment by Vinc3r** [comment]
So, why not adding a checkbox in the exporter to force use of object name instead of mesh name? This way all users could have the choice.

**Comment by emackey** [comment]
For what it's worth I'm not keen on this idea, or adding a checkbox to enable it.

Currently this exporter copies Blender node names to glTF node names, and copies Blender mesh names to glTF mesh names.  It's hard to get any clearer than that.  If you care about the mesh names, I feel like you should name the meshes appropriately in Blender.  Most people shouldn't though, given that animations target nodes.

**Comment by emackey** [comment]
I could imagine a Blender plugin to auto-rename all your meshes to match your node names, that might be a cool thing to have.

**Comment by Vinc3r** [comment]
Actually there are already Blender scripts for that (e.g.: [Name Panel](https://blendermarket.com/products/name-panel/), [Batch Rename Datablocks](https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Object/Batch_Rename_Datablocks)).

I understand that naming the gltf datablocks using the exactly same name as Blender datablocks seems the more logical things to do, but in my opinion it looks like more as a dev' point of view, and not really an artist POV for whom the meshes name datablocks have no interest :-) So I still think having this option could be very useful.

About animations, Blender names actions using the object name, and if I well understand gltf use nodes ID to link anim' to meshes, so changing the mesh name should probably change nothing (note that I'm not sure about that).

**Comment by donmccurdy** [comment]
Closing issues as we move toward the new project (https://github.com/KhronosGroup/glTF-Blender-IO/). At this time I think the naming behavior of the exporter is what it should be, but feel free to open a new issue on the new repository if you can't get it working for your use case.

**Comment by Vinc3r** [comment]
just for the memory, I was already opened an issue on the new repo to discuss about it, closed now ;)

https://github.com/KhronosGroup/glTF-Blender-IO/issues/224

**Comment by emackey** [comment]
I think using a separate mesh-rename addon, such as one of the ones you linked above, is a better answer than changing the way glTF export works for everyone.  Not all artists treat the mesh name as meaningless, and glTF nodes can re-use glTF meshes just like in Blender.  Keeping the names 1:1 the same (between Blender and glTF) is the most sensible strategy for the exporter, especially when existing addons can manage collections of names in Blender.

**Comment by Vinc3r** [comment]
yep I get & understand it ;)
