### ISSUE TITLE
no texture export

### ISSUE THREAD

**Issue by ladiszlai** [KhronosGroup/glTF-Blender-Exporter#208]
I made a simple animated cube in blender, I exported it with texture, but there was no texture in the glTF file expect material.

**Comment by donmccurdy** [comment]
Please share a blend file (zips can be dragged into comments) or details about your material settings.

**Comment by ladiszlai** [comment]
Here ya

https://files.fm/u/q2kmh4k2

**Comment by ladiszlai** [comment]
Thank you for the answer ! I tried exporting in the same way like you did but now the exporter gave me an error: 

![nevtelen](https://user-images.githubusercontent.com/6253595/39662106-346e163c-505d-11e8-8d25-5157b80bf010.jpg)

**Comment by donmccurdy** [comment]
Hm that is a bug on our part, because you are saving the `.gltf` to the same folder as the source image. It will be fixed, but meanwhile you can work around it by saving to another folder.
