### ISSUE TITLE
Combine RGB textures not export?

### ISSUE THREAD

**Issue by capitalknew** [KhronosGroup/glTF-Blender-Exporter#21]
Hello. I tried to export gltf with metallic and roughness separately (but combined by "Combine RGB"), but Blender does not export this texture. Blender have no own image processing library? Would be good ImageMagick, for example, inside of Blender.

**Comment by UX3D-nopper** [comment]
Merging the seperate channels could be done with Blender and there is no need for ImageMagick inside Blender.
This feature is out of scope for the exporter. The glTF PBR nodes expect the textures as they are defined in glTF 2.0.
However, your idea is good and I suggest you implement a command line tool using ImageMagick, which is combining these channels. If it is working, please list it here:
https://github.com/KhronosGroup/glTF/issues/867
