### ISSUE TITLE
PNG texture is exported as JPG (even for normals)

### ISSUE THREAD

**Issue by soadzoor** [KhronosGroup/glTF-Blender-Exporter#211]
Hi,

If I remember correctly, this plugin used to export every texture as PNG. Now, as I tested, it exports the textures as JPG in most cases, except when the alpha channel of the texture is used (in that case it's exported as PNG).

Normal maps are also exported as JPG, even when the original normal map is a PNG.
JPG for normals are horrible, though, the smallest artifacts (due to the compression) are easily visible.

I suggest the following: if a texture is originally PNG, then export it as PNG. If it's originally JPG, export it as JPG. If it's something else besides these two, then export it as JPG for textures-without-alpha, PNG for textures-with-alpha.

If the suggestion above is wrong (or hard to implement), then I suggest at least exporting the normal maps as PNG.

@donmccurdy  What do you think?
Thanks

**Comment by donmccurdy** [comment]
>  JPG for normals are horrible, though, the smallest artifacts (due to the compression) are easily visible.

Is this common practice, to use PNG for normal maps to avoid JPG artifacts? Or would it be better to expose a slider for compression level?

> I suggest the following: if a texture is originally PNG, then export it as PNG. If it's originally JPG, export it as JPG. If it's something else besides these two, then export it as JPG for textures-without-alpha, PNG for textures-with-alpha.

I'm OK with this idea. It is at least predictable; this exporter would try to preserve original textures wherever possible, and optimizations would be left to other tools. @emackey what do you think?

Example of artifacts in a JPG normal map:

![39642352-5bfa6f98-4f86-11e8-8c80-02f360f31f98](https://user-images.githubusercontent.com/1848368/39712045-79e26112-51d6-11e8-8f19-1a02b01b512e.png)

**Comment by emackey** [comment]
> I suggest the following: if a texture is originally PNG, then export it as PNG. If it's originally JPG, export it as JPG. If it's something else besides these two, then export it as JPG for textures-without-alpha, PNG for textures-with-alpha.

Sounds good to me.

**Comment by soadzoor** [comment]
> Is this common practice, to use PNG for normal maps to avoid JPG artifacts?
I think it is, especially on the web, where PNG is the only widely supported lossless image format

**Comment by donmccurdy** [comment]
Ok, let's make the change. I'll get to this when I have the chance — it may be a few weeks — or PRs would be welcome.

**Comment by slicer4ever** [comment]
I've done a minor fix that doesn't seem to break anything:

in gltf2_get.py i changed the function:
```
def get_image_uri(export_settings, blender_image):
    """
    Return the final URI depending on a filepath.
    """
    extension = '.jpg'
    if get_image_use_alpha(export_settings, blender_image):
        extension = '.png'

    return get_image_name(blender_image) + extension
```
to just:
```
def get_image_uri(export_settings, blender_image):
    return blender_image.name;
```

and in gltf2_generate.py line 2155 i changed from:
```
        if get_image_use_alpha(export_settings, blender_image):
```
to:
```
        if os.path.splitext(blender_image.name)[1]==".png":
```

I haven't seen anything break yet...but hopefully that changes any problems(note the line above may need to be modified so it can parse capital PNG as well.)

**Comment by donmccurdy** [comment]
Opened https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/221 to do essentially that — if the artist uses JPG or PNG, preserve that. All other formats will be converted to one of the two, based on their usage. glTF does not support other formats like BMP/TIFF/PSD, to ensure that viewers can efficiently load models.
