### ISSUE TITLE
Equivalence between glTF Metallic Roughness group to Principled BSDF shader?

### ISSUE THREAD

**Issue by MiguelAlgaba** [KhronosGroup/glTF-Blender-Exporter#213]
Hi, I was trying to get some equivalent results with simple materials using the glTF Metallic Roughness node group and Principled BSDF shader, however I'm not sure if I'm doing something wrong or there are some bugs leading to very noticeable differences.

For example these are the parameters I'm using to try to get a light blue non-metallic material with a 0.5 roughness:

<img width="515" alt="screen shot 2018-05-08 at 20 54 03" src="https://user-images.githubusercontent.com/1735089/39776744-f95e862e-5301-11e8-8d51-3cf7a5b5f840.png">

These are the results I get when using the Principled BSDF shader when rendering with Cycles (see the glossy areas on top of the blue cone)

![0_materials_principledbsdf](https://user-images.githubusercontent.com/1735089/39776822-2cc03e40-5302-11e8-9999-f3105761536d.png)

And these are the results I get when using the glTF Metallic Roughness group instead (see how the result looks like having a roughness of 1 while I tried to specify a roughness of 0.5)

![0_materials_gltfmetallicroughness](https://user-images.githubusercontent.com/1735089/39776928-7acaa22e-5302-11e8-985a-48a54209e12a.png)

I know this repo is all about exporting to glTF format, however I think it is not clear how to get equivalent results within Blender as well as what to expect to see when loading the exported file into some other viewer. Is there some reference guide explaining the equivalence between the glTF Metallic Roughness node group and the Principled BSDF shader (at least for simple materials like diffuse, glossy, emission, etc)?

**Comment by donmccurdy** [comment]
We now support the Principled BSDF material in https://github.com/KhronosGroup/glTF-Blender-IO.
