### ISSUE TITLE
Skinning and animation keys

### ISSUE THREAD

**Issue by slicer4ever** [KhronosGroup/glTF-Blender-Exporter#215]
Hello, This isn't so much an issue as a question as the online viewers seem to have no problem with my exported models.

basically I can't figure out how the inverse bind matrix and the rotation frames from this model: [model link](https://drive.google.com/file/d/1LMdeAqmpKlPswocoQzDSGTofhSRJV2C1/view?usp=sharing) work out.  for armature.001 the inverse bind matrix says their is no rotation, yet the first frame of the rotation animation says that their is a 90 degree rotation around the z axis.  so when i load the model, apply each bind matrix, then apply the first frame of animation, this applys the 90 degree rotation to my vertices instead of the no rotation as expected.

I would really like some insight into what i'm missing as my expectation is each rotation animation's first frame should be the identity quaternion.

Note i uncheck rotate to Y up to simplify the rotation values.

**Comment by donmccurdy** [comment]
Armatures have to go through nontrivial conversion at export, it's hard to say what might be causing this. it may be a bug, or may be something about representing Blender's bones (which have a head and a tail end) as glTF's joints (which are simply points).
