### ISSUE TITLE
Can't install: Add-on checkbox disabled:: Blender 2.79b OSX

### ISSUE THREAD

**Issue by eighteight** [KhronosGroup/glTF-Blender-Exporter#217]
<img width="796" alt="screen shot 2018-05-16 at 23 23 03" src="https://user-images.githubusercontent.com/542368/40142046-431eb72a-5960-11e8-950c-0b6522e0cfe0.png">

**Comment by donmccurdy** [comment]
How are you installing the addon? Was this using one of the [methods described here?](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/scripts)

**Comment by donmccurdy** [comment]
Will need more details to address this, let us know if this is still an issue.
