### ISSUE TITLE
ior / fresnel

### ISSUE THREAD

**Issue by goetzmoritz** [KhronosGroup/glTF-Blender-Exporter#218]
Hi there,

is there any way how to build a velvet-like material with this glTF-Exporter?
I did not find any ior/fresnel-examples.

Thanks!

**Comment by so-rose** [comment]
@goetzmoritz Fresnel is automatically added to materials in glTF based on base reflectivity, using the common Schlick approximation. You can't control this base reflectivity in a Metalness workflow, but, you can if you use the Specular workflow.

To my knowledge, the glTF spec doesn't define any finer control over the Fresnel curve, or any preset approximations for more complex incident angle effects (like metals). I personally think this would be a great future extension.

There is a way to use IOR in glTF materials, though. Just calculate [this formula](https://blender.stackexchange.com/questions/84885/how-to-calculate-specular-value-for-principled-bsdf-node-from-ior), and make the result the SpecularFactor value of the Specular Glossiness node.

**Comment by goetzmoritz** [comment]
Thanks for that answer. Yet I wonder how they did this:

https://cdn.soft8soft.com/demo/player/player.html?load=../applications/materials/blender_essential/export/velvet_soft.gltf.xz

**Comment by lexaknyazev** [comment]
@goetzmoritz They use their own custom material extensions that can describe blender's material node graph.
