### ISSUE TITLE
The COLLADA file created in Maya can not be correctly converted to glTF 2.0

### ISSUE THREAD

**Issue by cx20** [KhronosGroup/glTF-Blender-Exporter#22]
This Issue has been separated from https://github.com/KhronosGroup/glTF-Sample-Models/issues/83#issuecomment-311939203

I also tried Blender 2.78c and [glTF 2.0 Explorter](https://github.com/KhronosGroup/glTF-Blender-Exporter/).
First I tried to display [EmaSimpleSkin.dae](https://github.com/cx20/jsdo-static-contents/blob/master/models/collada/EmaSimpleSkin/EmaSimpleSkin.dae) on Blender.
![emasimpleskin_blender_gltf2_20170629_002](https://user-images.githubusercontent.com/1833979/27683813-5785f166-5d02-11e7-966d-022e25e9bf5c.gif)
Next, I tried to display the glTF 2.0 file exported from Blender in Three.js.
[Three.js + glTF 2.0 model result:](http://jsdo.it/cx20/yfvq)
![emasimpleskin_threejs_gltf2_20170629](https://user-images.githubusercontent.com/1833979/27683862-82afeb9e-5d02-11e7-8406-f27db34ff958.gif)

I think that models including skinning animation have not been converted correctly.

**Comment by UX3D-nopper** [comment]
Let me have a look at it.

**Comment by UX3D-nopper** [comment]
Just tried out the model with my Vulkan renderer ... from my side I do not see any different output than in Blender. This is a screenshot during the animation and the polygon is bended correctly:

![grafik](https://user-images.githubusercontent.com/27856744/27690298-3fcb2a80-5ce1-11e7-8878-6f9a7c9b08d4.png)

**Comment by UX3D-nopper** [comment]
Can you please check the three.js importer and skinning renderer? Maybe there is a problem.

**Comment by cx20** [comment]
Hmm. It is not displayed even in Three.js and Babylon.js, is it a viewer problem?

[Three.js + EmaSimpleSkin.gltf result](http://jsdo.it/cx20/yfvq)
[Babylon.js + EmaSimpleSkin.gltf result](http://jsdo.it/cx20/c7eJ)

[WalkingLady.dae](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/sourceModels/WalkingLady/WalkingLady.dae)  has a more complex skinning animation. Could you please try converting this?

**Comment by UX3D-nopper** [comment]
![grafik](https://user-images.githubusercontent.com/27856744/27692036-f6b77dda-5ce5-11e7-90c8-7c0cc4b988de.png)

**Comment by UX3D-nopper** [comment]
Works on my side.

**Comment by UX3D-nopper** [comment]
![grafik](https://user-images.githubusercontent.com/27856744/27692142-3fab26ae-5ce6-11e7-9925-d91afbb6f261.png)
Also the astro boy works.

**Comment by cx20** [comment]
Thank you for confirmation. I would like to add Issue for Three.js and Babylon.js viewers.
/ping @donmccurdy @bghgary

**Comment by takahirox** [comment]
I'm looking into the issue that Three.js can't correctly display EmaSimpleSkin.gltf exported by Blender exporter here https://github.com/mrdoob/three.js/issues/11644

I'm feeling like the model is missing premultiplied Bind Shape Matrix in Inverse Bind Matrices. 
(Refer to https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skins)

Would you please check if the Blender glTF exporter premultiplies Bind Shape Matrix?

**Comment by UX3D-nopper** [comment]
Having a look at it.

**Comment by UX3D-nopper** [comment]
Found the problem.

**Comment by UX3D-nopper** [comment]
![grafik](https://user-images.githubusercontent.com/27856744/27770001-80b0462c-5f37-11e7-9fe7-faf7fed2a22f.png)

**Comment by takahirox** [comment]
The problem of Blender Exporter? Or Three.js?

**Comment by UX3D-nopper** [comment]
With the exporter and I fixed it (not uploaded it).
Problem is, that in Blender and armature can have several meshes, each with an individual bind shape matrix.
So, in the end, I need to apply the bind shape matrix and need to dublicate the mesh, if used somewhere else.

**Comment by UX3D-nopper** [comment]
Ah, I have an idea :-)

**Comment by UX3D-nopper** [comment]
I think I fixed it - will upload now:
![grafik](https://user-images.githubusercontent.com/27856744/27781123-db26279e-5fcc-11e7-85d3-bebf4b296365.png)
![grafik](https://user-images.githubusercontent.com/27856744/27781136-ec826976-5fcc-11e7-922b-ae844b9461ef.png)
![grafik](https://user-images.githubusercontent.com/27856744/27781152-0035a71c-5fcd-11e7-98d4-e016fc00820d.png)

**Comment by UX3D-nopper** [comment]
Please try out:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/7809600c95d529db7ca7f1f04cbb220a11f5c932

**Comment by takahirox** [comment]
@cx20 would you please try?

**Comment by UX3D-nopper** [comment]
![grafik](https://user-images.githubusercontent.com/27856744/27791987-ecff7b2a-5ff7-11e7-8b21-23946f656ce2.png)
Also the lady animates correct, screenshot from here:
https://gltf-viewer.donmccurdy.com/

I close the ticket, as I think it is fixed. Please reopen, if you have another non-working skinning model.

**Comment by cx20** [comment]
I tried again with Three.js and Babylon.js. Both seem to be OK.
[Three.js + EmaSimpleSkin.gltf result](http://jsdo.it/cx20/6vRt)
![emasimpleskin_threejs_gltf2_20170704](https://user-images.githubusercontent.com/1833979/27802102-a576670e-605c-11e7-8686-e382e24c9127.gif)

[Babylon.js + EmaSimpleSkin.gltf result](http://jsdo.it/cx20/EGIL)
![emasimpleskin_babylonjs_gltf2_20170704](https://user-images.githubusercontent.com/1833979/27802304-f25aa548-605d-11e7-8318-3e08d09c1fce.gif)

@UX3D-nopper Thank you for fixing it.
