### ISSUE TITLE
Specular Glossiness node is broken

### ISSUE THREAD

**Issue by so-rose** [KhronosGroup/glTF-Blender-Exporter#222]
Hello,

I've discovered that the "glTF Specular Glossiness" does not work correctly!

First, some basic assumptions I made based on the [extension specification](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md):
* The **specularFactor** property is an RGB property that colors the reflective portion of the shader.
* The **specularGlossinessTexture** is an RGBA texture property (RGB specular + A Gloss), which is mapped to the **Specular** and **Glossiness** properties in the node group
* A material with a zeroed **diffuseFactor** and/or **diffuseTexture** still has a reflective surface color matching the relevant specular properties noted above.

The node's present behavior is inconsistent with these assumptions!
* In Blender, an RGB value plugged into either **Specular** or **SpecularFactor** is interpreted as a black and white value.
* Zeroing the **Diffuse** and/or **DiffuseFactor** values, whilst a specular value is non-zero, still results in a black material.

Demonstrations follow:

![demon_1](https://user-images.githubusercontent.com/8473401/40238120-48b25130-5a80-11e8-9f06-ed09d1652601.png)

![demon_2](https://user-images.githubusercontent.com/8473401/40238127-4c566cf4-5a80-11e8-9836-1899ff380886.png)

![demon_3](https://user-images.githubusercontent.com/8473401/40238643-ca2ccb40-5a81-11e8-9f9c-7cbdf10e06cb.png)

Further notes:
* The present behavior is also inconsistent with other glTF implementations (like [this one](https://bghgary.github.io/glTF/convert-between-workflows/))
* The present behavior, inconsistent with the assumptions, exists in both the glTF.blend and glTF2_Principled.blend variants of the node.
* Here are the .blend files I used to make the demonstration images: [demonstration.zip](https://github.com/KhronosGroup/glTF/files/2017096/demonstration.zip)

Information:
```
Commit: 8af23eb
Blender Version: 2.79b
```

Best Regards,
Sofus Rose

**Comment by emackey** [comment]
Confirmed, this is a miswiring of spec/gloss nodes.  In particular the non-principled version, where all the math has been laboriously laid out as individual Blender nodes, the specular input is treated as monochrome.

The version that feeds into Blender's Principled node could be even more challenging to fix, as essentially the specular intensity feeds into the principled metallic input, which is also monochrome, and it's a native node so there's no going into the sub-sub-nodes to fix it that way.  There may not be any way to use Blender's own Principled node to provide specular color as per glTF spec.

**Comment by emackey** [comment]
Also there's an actual node in the graph named "TODO: Check if OK" as it converts the specular input to monochrome.  I don't think it's OK.

![exporternodes](https://user-images.githubusercontent.com/1235080/40255265-8edc6b3a-5ab4-11e8-96a1-aa3d0cab193e.png)

**Comment by donmccurdy** [comment]
@so-rose thank you! I think a pull request would be very welcome, if you're willing.

**Comment by emackey** [comment]
@so-rose That's a nice looking node graph you posted there.  Agreed, a pull request would be most welcome.

**Comment by so-rose** [comment]
@donmccurdy @emackey Thank you very much! I made the pull request!

**Comment by oparisy** [comment]
Will the issues with respect to the Principled node be a showstopper for #101 (the idea of using the same Principled BSDF node to specify Cycles, Eevee and glTF materials)?

**Comment by emackey** [comment]
@oparisy Good question.  I think it will only be a showstopper for models built for the `KHR_materials_pbrSpecularGlossiness` extension.

It should not stand in the way of core glTF 2.0 metal/rough materials.

**Comment by oparisy** [comment]
@emackey #101 would still be on track for 2.8, then. Thanks for your answer!

**Comment by donmccurdy** [comment]
Closing – see discussion in https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/225 and https://github.com/KhronosGroup/glTF-Blender-IO/issues/52.
