### ISSUE TITLE
GLTF Export Crashes when Exporting with materials

### ISSUE THREAD

**Issue by Eric02** [KhronosGroup/glTF-Blender-Exporter#224]
Hello,
In Blender, when exporting a scene with 5 objects (5 materials in total) as GLTF with "export material" checked, it crashes. Default settings. The model is 72000 tris. Materials are very simple (1 tex as baseColor). I have tested with a cube (with 1 texture material) and it also crashed.

I have just updated now after seen a new commit but the crash persists. Too bad...

Traceback (most recent call last):
  File "C:\Users\...\Documents\glTF-Blender-Exporter-master\scripts\add
ons\io_scene_gltf2\__init__.py", line 373, in execute
    return gltf2_export.save(self, context, export_settings)
  File "C:\Users\...\Documents\glTF-Blender-Exporter-master\scripts\add
ons\io_scene_gltf2\gltf2_export.py", line 84, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "C:\Users\...\Documents\glTF-Blender-Exporter-master\scripts\add
ons\io_scene_gltf2\gltf2_generate.py", line 2890, in generate_glTF
    generate_images(operator, context, export_settings, glTF)
  File "C:\Users\...\Documents\glTF-Blender-Exporter-master\scripts\add
ons\io_scene_gltf2\gltf2_generate.py", line 2176, in generate_images
    create_image_file(context, blender_image, path, file_format)
  File "C:\Users\...\Documents\glTF-Blender-Exporter-master\scripts\add
ons\io_scene_gltf2\gltf2_create.py", line 338, in create_image_file
    copyfile(src_path, dst_path)
  File "C:\Users\...\Documents\blender-2.79b-windows64\2.79\python\lib\
shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'C:\\Users\\...\\Documents\\three.js-master\\thre
ejs\\Colonnes_LM.jpg' and 'C:\\Users\\...\\Documents\\three.js-master\\
threejs/Colonnes_LM.jpg' are the same file

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.79\sc
ripts\addons\sverchok-master\core\handlers.py", line 68, in sv_main_handler
    @persistent
KeyboardInterrupt

**Comment by donmccurdy** [comment]
This was meant to have been fixed by https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/f610a1cfdc3239d5578568a89ef0d29e83401526 four days ago — if it is not fixed for you, could you provide a `.blend` file reproducing the issue? You can drag ZIP files into GitHub comments.

Also, you can work around the issue by exporting to a different directory.

**Comment by Eric02** [comment]
As you said, it works when you save it in a different folder. To make sure, I re-tested the problem and it was the same. 

Here you have. Please, let me know once you've downloaded it. 
http://webgl-test.blp.archi/github/threejs.zip

I used your GLTF Viewer: nice work! I have to learn from it.

**Comment by donmccurdy** [comment]
Thanks! I've downloaded the `.blend` file, and on an older version of the exporter I can reproduce the issue, but on the newest exporter I cannot. You're sure that you've both replaced the old exporter and restarted Blender since then?

If so, could you try this build of the exporter as well?
[io_scene_gltf2-PATCHED.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2027662/io_scene_gltf2.zip)

**Comment by Eric02** [comment]
Sorry to insist but on Windows 7, I still have the same issue.

I have even uninstalled Blender (2.79b), reinstalled both Blender and the patch and... same. When downloading **io_scene_gltf2_PATCHED.zip**, I get **io_scene_gltf2.zip** (no PATCHED in the file name). Isn't that strange? URL error?

I really think I how done things correctly... or I'm repeating the same mistake.

**Comment by emackey** [comment]
Check if you have a folder named `__pycache__` as a child of `io_scene_gltf2`.  If so, quit out of Blender and delete this folder, it's a cache of pre-compiled python and could be out of date.

**Comment by Eric02** [comment]
__pycache__ was the problem. Now it works fine. 

Thank you for the help!

**Comment by Eric02** [comment]
Don't worry, it happens to me all the time.  :-)  I'll be using GLTF a lot, so thank you for your work!

**Comment by LambdaFalcon** [comment]
This still happens for me with Blender 2.79b, just downloaded the latest files.
Here is the output:
```
----- Python Traceback -----
    File "/Applications/blender.app/Contents/Resources/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 366, in execute
      return gltf2_export.save(self, context, export_settings)
    File "/Applications/blender.app/Contents/Resources/2.79/scripts/addons/io_scene_gltf2/gltf2_export.py", line 84, in save
      generate_glTF(operator, context, export_settings, glTF)
    File "/Applications/blender.app/Contents/Resources/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2750, in generate_glTF
      generate_images(operator, context, export_settings, glTF)
    File "/Applications/blender.app/Contents/Resources/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2045, in generate_images
      image_data = create_image_data(context, export_settings, blender_image, file_format)
    File "/Applications/blender.app/Contents/Resources/2.79/scripts/addons/io_scene_gltf2/gltf2_create.py", line 363, in create_image_data
      return _create_jpg_data(context, export_settings, blender_image)
    File "/Applications/blender.app/Contents/Resources/2.79/scripts/addons/io_scene_gltf2/gltf2_create.py", line 374, in _create_jpg_data
      create_image_file(context, blender_image, path, 'JPEG')
    File "/Applications/blender.app/Contents/Resources/2.79/scripts/addons/io_scene_gltf2/gltf2_create.py", line 339, in create_image_file
      copyfile(src_path, dst_path)
    File "/Applications/blender.app/Contents/Resources/2.79/python/lib/python3.5/shutil.py", line 104, in copyfile
      raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
  shutil.SameFileError: '/Users/.../public/uploads/a8dRnnZkqT/appleD.jpg' and 'public/uploads/a8dRnnZkqT/appleD.jpg' are the same file
```

In `gltf2_create.py` this line is supposed to check that this error cannot happen:
```
if dst_path != src_path:
    copyfile(src_path, dst_path)
```

The paths are indeed different, but they point to the same file because one path is absolute and the other is relative.
I don't know how this can happen though, since they are created using: `bpy.path.abspath(...)`

Is `bpy.path.abspath` broken?
