### ISSUE TITLE
Force Uint16-32 export even for small models?

### ISSUE THREAD

**Issue by capitalknew** [KhronosGroup/glTF-Blender-Exporter#23]
I found problem. When model have very few vertices, then exports indices as Uint8. How to force export as Uint16 or Uint32?

**Comment by UX3D-nopper** [comment]
Well, it is not a problem. The exporter just does not have this feature. Let me have a look at your pull request but actually, I would prefer just to force a value.

**Comment by capitalknew** [comment]
Here preview version of pull request 
https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/24

**Comment by UX3D-nopper** [comment]
Added an update, where it is possible to force the indices type:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/8a1bc08e5f81982a8e461a43104611bd4723525f
Having a minimum indices filed just makes things more complicated for the user.

Hope you can live with this fix.
