### ISSUE TITLE
export generate randomly mesh primitives order when multimaterials are used

### ISSUE THREAD

**Issue by Vinc3r** [KhronosGroup/glTF-Blender-Exporter#231]
The issue is that the same object using multimaterials is not the same when reexporting after quitting Blender. This bring us to issues and interactions breaking when scripting using submeshes once in a 3D engine.
I think the mesh primitives order should follow materials index from Blender.

I have put all the process into this zip file: [gltf-random-submesh.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2058528/gltf-random-submesh.zip), here the readme content:

---

**base.blend** : an object with 3 materials on it (using MetallicRoughness GLTF material)

# Process

- open base.blend
- export to base-export01.gltf
- re-open the blend without quitting Blende r(ctrl + shift + O) and export to base-export02.gltf
- quit Blender
- open base.blend
- export to base-export03.gltf

# Results

Compare .gltf files with a soft like Winmerge:

- export01 & 02 are the same:

![comparing_01-02](https://i.imgur.com/nL0UDOK.png)

- export01 & 03 are different!:

![comparing_01-03](https://i.imgur.com/oQlAysB.png)

And this leads to result when playing with submeshes in a 3D engine (here, babylonJS):

![gltf-submesh-randomize](https://i.imgur.com/1TqWvQj.gif)

**Comment by Vinc3r** [comment]
I've tested on few scenes the PR from TanguyBr and it seems fixing this bug & keepiing the multimaterial order :)

**Comment by donmccurdy** [comment]
This issue has been fixed in the new importer/exporter, https://github.com/KhronosGroup/glTF-Blender-IO/. Closing here, will comment on the PR – it may still be merged, but the CLA needs to be signed.
