### ISSUE TITLE
Having multiple rigging setups in a scene results in geometry getting distorted or discarded.

### ISSUE THREAD

**Issue by zomboh** [KhronosGroup/glTF-Blender-Exporter#232]
Hello there!

Came across this: if you have two rigging setups in a scene (doesn't matter if the second one is actually parenting any mesh), the resulting exported glTF will either show some distorted geometry (displaced polys), or will directly discard some geometry. Once the second setup is removed from the scene, every mesh will export and render as expected. I understand the glTF spec supports multiple skeletons in the same scene.

Steps to reproduce:
1. Create any 2 meshes
2. Create 2 armatures
3. Make any armature the parent of any mesh with automated weights
4. Either do the same with the unparented armature/mesh pair, or don't.
5. Export to glTF with the "export skinning" and "export all layers" checkboxes selected (and "export selection only" unchecked, just to make sure).

Here's my Blender (v2.79) view: ![blender](https://user-images.githubusercontent.com/17140223/40805131-97f5040c-651d-11e8-8858-db62c5cdab05.png)

Here's @donmccurdy's glTF viewer: 
![gltfviewer](https://user-images.githubusercontent.com/17140223/40805207-d3777280-651d-11e8-9e72-56177112ca77.png)

Here's BabylonJS viewer:
![babylonjs](https://user-images.githubusercontent.com/17140223/40805254-fa8fd45c-651d-11e8-9d0b-4376dba28fda.png)

A-Frame doesn't render anything, same as with BabylonJS viewer.

If you need any more info please let me know. I tried other models with wildly different topologies, applied materials etc, and the results slightly vary but are always the same: either some geometry gets distorted or discarded.

Here's both the .blend and glTF files I tested this with: [rigging_glTF.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2059858/rigging_glTF.zip)

**Comment by enzyme69** [comment]
Have you found solution to this yet?

**Comment by emackey** [comment]
This was [reported again on Blender Stack Exchange](https://blender.stackexchange.com/q/132849/18161).

**Comment by donmccurdy** [comment]
Fixed at least in part by https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/352. Also note that future development will be moving to https://github.com/KhronosGroup/glTF-Blender-IO.
