### ISSUE TITLE
Required Roughness and Metallic Map for Ambient Light to work

### ISSUE THREAD

**Issue by Eric02** [KhronosGroup/glTF-Blender-Exporter#233]
Hello!

This may not be a bug but, in Blender, when using glTF Metallic Roughness, you must add a texture in the MetallicRoughness socket otherwise an ambient light in THREE.js won't work. In a usual Principled shader (Blender PBR shader), you can leave it blank and it will use default values and return a good result. It took me a while to get comparable results in Blender and with THREE.js.

Maybe this detail will save someone some time.

Cheers,

Eric

**Comment by emackey** [comment]
The default values for Metallic and Roughness are both `1.0`, which produces a material that doesn't reflect much light.  If you're lacking a metal/rough texture, try setting MetallicFactor to `0` (for non-metallic surfaces), and/or set RoughnessFactor to `0.5` or some middle-ish number.

It looks like Blender's Principled node defaults both of these values to `0.0` when first created, hence the results are different.

**Comment by donmccurdy** [comment]
Also note that threejs requires an environment map be added (at runtime, not baked into the model) for metallic PBR materials.

**Comment by Eric02** [comment]
Oh ok! If metallic factor = 1 and there is no environment, then the material turns pitch black because it reflects no ( = 0) environment light. It's a little bit different than what happens in Blender but I understand a bit more.
After some tests, I still have to work on factors as, in PBR for UE4 or Cycles/Blender the textures (B/W for roughness and metallic) take care of them. I have noticed I can do everything, I just need more practice.

Thank you both.
