### ISSUE TITLE
Transparent image used as material exported incorrectly.

### ISSUE THREAD

**Issue by xbeat** [KhronosGroup/glTF-Blender-Exporter#235]
In this model the mesh of the soccer golie net uses a transparent material, the back part (the grey one) becomes incorrectly transparent only from the point of view of the camera (the background of the skybox is displayed) while the grey part, which uses an image as background is rendered correctly.

**Blender file:** 
[stadium.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2065846/stadium.blend.zip)

**Exported files with html viewer:**
[stadium.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2065848/stadium.zip)

**Export parameters:**
![gltf blender export params](https://user-images.githubusercontent.com/20385856/40885427-2fda53ee-6726-11e8-80c3-9a892551cb15.png)

**Blender render ( correct ):**
![gltfblender](https://user-images.githubusercontent.com/20385856/40885438-51fe129e-6726-11e8-8624-245b427edd53.png)

**glTF ( wrong transparency )**
 **using @donmccurdy glTF Viewer** https://github.com/donmccurdy/three-gltf-viewer 
![gltfviewer](https://user-images.githubusercontent.com/20385856/40885449-7b155890-6726-11e8-9f16-1a4dbf4e2bfb.png)

**Comment by donmccurdy** [comment]
I don’t have access to Blender to check the files but this looks like a transparency sorting issue, and that often requires changes to the model to solve for realtime rendering.

If you’re able to, using a transparent texture with holes for the net, in mask/cutout mode, will probably give better results here.

**Comment by xbeat** [comment]
Hi @donmccurdy, thanks for your reply, I had the same problem with the three.js blender export JSON plugin ( now deprecated ) and it was resolved this [way](https://discourse.threejs.org/t/transparent-image-used-as-material-rendering-incorrectly-solved/2445/8). Unfortunately I can not import in the editor the file GLTF (I opened a report on the [forum](https://discourse.threejs.org/t/load-gltf-in-the-editor-not-appearing/3005)) to check whether the solution is the same. The solution using a transparent image as material would be the optimal solution, even to retain the reduced file size. Currently I am unable to change the net using the mask/cutout mode ( i need to learn how to do it ). :(

**Comment by donmccurdy** [comment]
I'm not a Blender expert by any stretch (there is a Blender Stack Exchange that would be better) but this seems to work:

| material | texture |
|---|---|
| <img width="351" alt="screen shot 2018-06-03 at 10 14 06 pm" src="https://user-images.githubusercontent.com/1848368/40896626-af7a24b2-677b-11e8-95b1-68732ddf1d58.png"> | <img width="353" alt="screen shot 2018-06-03 at 10 14 14 pm" src="https://user-images.githubusercontent.com/1848368/40896631-b28d4684-677b-11e8-9ce6-56738bde7b64.png"> |

It looks funny in Blender (I don't know why) but correct once exported to three.js.

| result in Blender | result in three.js |
|---|---|
| <img width="640" alt="screen shot 2018-06-03 at 10 14 26 pm" src="https://user-images.githubusercontent.com/1848368/40896638-c0595b18-677b-11e8-88a8-76774a63609c.png"> |  <img width="537" alt="screen shot 2018-06-03 at 10 13 46 pm" src="https://user-images.githubusercontent.com/1848368/40896640-c61e38ca-677b-11e8-8fe0-a8284bf36ac0.png"> |

You'll also want to mark the model as double-sided in three.js to get the inside of the net appearing correctly. It's currently not possible to do that part in Blender.

```js
object.traverse((node) => {
  if (node.isMesh) node.material.side = THREE.DoubleSide;
});
```

**Comment by xbeat** [comment]
@donmccurdy, can you post the Blender file and the js so I can do some tests with a working example? Thanks!
