### ISSUE TITLE
Different Renders between glTF2.blend and glTF2_Principled.blend

### ISSUE THREAD

**Issue by filibis** [KhronosGroup/glTF-Blender-Exporter#239]
Hi,
I downloaded [this Leather Shoes](https://sketchfab.com/models/626759e64b7542b9a852d67e743715c8) and imported into Blender via [this importer](https://github.com/ksons/gltf-blender-importer). (It looks fine with this importer's node but i wanted to test embedding textures when exporting. And i think it only works with your node groups, right?)

I wonder why it looks different/wrong when i append/link the node from **glTF2_Principled.blend** ? (It's fine if i append/link **glTF2.blend**). I presume they should look identical. Am i doing something wrong?

I use Blender 2.79b , here is the [packed blend file](https://drive.google.com/file/d/1SrCCYMJ_Uv2xMek6mAabz3lkJ0h02FfN/view?usp=sharing).

![appended_from_gltf2](https://user-images.githubusercontent.com/26340322/40920492-64791230-6815-11e8-985b-e4a90e5bbc0c.jpg)
![appended_from_gltf2_principled](https://user-images.githubusercontent.com/26340322/40920494-64a112e4-6815-11e8-885d-9fc994be580f.jpg)

**Comment by Vinc3r** [comment]
As you have linked your glTF group, I wan't able to see your material. I think you should merge as fake user the material from gltf blend files to share your scene.

Your renders above are just viewport preview I suppose? Is the render is the same on your 3D engine? on Cycles?

**Comment by filibis** [comment]
Can't you just re-link with your glTF group?
Yes, it's Cycles, render and viewport are displaying same. You can see the difference only by connecting the 'BaseColor', so i assume problem lies there.

**Comment by donmccurdy** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO supports principled  BSDF node now, we recommend that over these node groups.
