### ISSUE TITLE
Blender array modifier ignored.

### ISSUE THREAD

**Issue by SET001** [KhronosGroup/glTF-Blender-Exporter#242]
[collons4.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2087341/collons4.zip)

I have made a simple model in Blender where I have 2 rows of columns (6 columns in each). I made a row using `array` modifier and then copy it to obtain second row. Then I exported it as .gltf file to my project using exporter from this repo. But when I'm trying to preview this file in Visual Studio Code I see same 2 rows of columns but each row contain only 1 column. 
 
![blendergltfexportfailonarrays](https://user-images.githubusercontent.com/30506/41196137-92750fbe-6c42-11e8-8441-129d369ff120.png)

The screenshot shows preview for three.js but the problem is same for babylon and cesium preview. Can you please help if this is a Blender-Exporter issue or this is a problem of visual studio preview plugin or is this a problem with render library?

I have attached zip file with source .blend file and .gltf I'm getting after export. 
I'm useing Blender v 2.79b

**Comment by SET001** [comment]
I have found a notice about modifiers [here in documentation](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md#user-content-apply-modifiers) but since I'm new both in Blender and graphics I can't understand is it related to my problem or not.

**Comment by SET001** [comment]
I have found `Apply modifiers` in exporter settings and that solves my problem. Sorry for disturbing...

**Comment by SET001** [comment]
But just curios to know what does phrase from docs - "When exporting, apply these specific modifiers for a correct visual output of the scene" mean?

**Comment by emackey** [comment]
It probably needs clarification, but I think the author was trying to explain that users would want to avoid "apply modifiers" on things like skinning and morphing, and only apply modifiers when it was needed and made sense to do so, such as for arrays.
