### ISSUE TITLE
The occlusion of metallic roughness material doesn't look right in blender

### ISSUE THREAD

**Issue by Lee-Heisenbug** [KhronosGroup/glTF-Blender-Exporter#243]
I'm testing glTF Metallic Roughness node in blender. There is something wrong when I'm testing the occlusion texture. As the 2.0 specification mentions, *the occlusion values are sampled from the R channel of the texture. Higher values indicate areas that should receive full indirect lighting and lower values indicate no indirect lighting*. So I made a occlusion texture for a sphere. But the area where was red was darker in blender, brighter in three. I was using [glTF Viewer](https://gltf-viewer.donmccurdy.com/) for the test.

Render result in blender
![result-in-blender](https://user-images.githubusercontent.com/26576701/41200242-76765e62-6cd3-11e8-9ac0-b3f2db1fce30.JPG)

Render result in three
![result-in-three](https://user-images.githubusercontent.com/26576701/41200246-7a2e3e76-6cd3-11e8-9ef4-b9d193867cb8.JPG)

And when I'm testing the OcclusionStrength property, the result in blender is different from the one in three. But I think that might have something to do with the occlusion texture error mentioned above.

OcclusionStrength = 0

Render result in blender
![result-in-blender-occlusionstrength-0](https://user-images.githubusercontent.com/26576701/41200243-76f78ca8-6cd3-11e8-9d6a-9ae35c58039c.JPG)

Render result in three
![result-in-three-occlusionstrength-0](https://user-images.githubusercontent.com/26576701/41200247-7b935170-6cd3-11e8-9a8e-353245883216.JPG)

OcclusionStrength = 1

Render result in blender
![result-in-blender-occlusionstrength-1](https://user-images.githubusercontent.com/26576701/41200245-791a8094-6cd3-11e8-91c4-55a7a995b457.JPG)

Render result in three
![result-in-three-occlusionstrength-1](https://user-images.githubusercontent.com/26576701/41200249-7cf0f432-6cd3-11e8-8f8b-ad1337b2d6c2.JPG)

I don't know if there is a bug or if I was just doing it wrong.

Here is the file. Since the environment texture is huge, I removed it from the file.
[occlusion.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2087694/occlusion.zip)

**Comment by ldstein** [comment]
I'm also experiencing the same issue (Blender 2.79b, Windows x64) while preparing textures as per https://www.khronos.org/blog/art-pipeline-for-gltf

![screenshot-blender](https://user-images.githubusercontent.com/3657344/41758556-fef243b8-761b-11e8-98dd-80d12ce69ef6.jpg)

Online GLTF viewers show the occlusion map:

![screenshot-gltf-viewers](https://user-images.githubusercontent.com/3657344/41758511-99782b74-761b-11e8-99f8-bffe0c28dcbc.jpg)

Blend file, textures and generated GLB here: [occlusion-test.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2126341/occlusion-test.zip)

**Comment by Lee-Heisenbug** [comment]
@ldstein Maybe we could inverse the red channel of the texture and inverse the OcclusionStrength to make things right in blender?

**Comment by donmccurdy** [comment]
/cc @emackey @bghgary 

The spec is saying the inverse of what I'd thought ... higher occlusion values indicate _less_ occlusion? Had we discussed this before, or that a mistake? It looks like threejs and babylonjs already implement the more intuitive interpretation, where higher occlusion values indicate more occlusion.

**Comment by bghgary** [comment]
This is not a mistake. Babylon definitely works as per spec. I'm pretty sure Three does it per spec as well or the PBR sample models with occlusion will all look wrong.

**Comment by donmccurdy** [comment]
Ah ok. Yes three.js does it per spec too:

```
float ambientOcclusion = ( texture2D( aoMap, vUv2 ).r - 1.0 ) * aoMapIntensity + 1.0;
reflectedLight.indirectDiffuse *= ambientOcclusion;
```

Probably just a rendering issue in this exporter then.

**Comment by donmccurdy** [comment]
Closing this issue, current work on AO in the new importer/exporter and Blender 2.8 tracked in https://github.com/KhronosGroup/glTF-Blender-IO/issues/123.
