### ISSUE TITLE
[Question] bone rotation values are different from blender values

### ISSUE THREAD

**Issue by ladiszlai** [KhronosGroup/glTF-Blender-Exporter#245]
For example the default quaternion rotation values of my bone in blender are:
![nevtelen](https://user-images.githubusercontent.com/6253595/41341385-e0b4eb86-6ef9-11e8-8a11-e22b0f60079d.jpg)

and when exported in gltf:
![nevtelen2](https://user-images.githubusercontent.com/6253595/41341486-19de1716-6efa-11e8-9ff1-5bdb9b626dd2.jpg)

my first keyframe values:
![nevtelen3](https://user-images.githubusercontent.com/6253595/41341636-76dd3474-6efa-11e8-9c67-a77195b548d2.jpg)

in gltf:
![nevtelen4](https://user-images.githubusercontent.com/6253595/41341658-82c7f8dc-6efa-11e8-8299-d570188a213c.jpg)

Why is this happen ? I am writing a gltf addon to a program that would load the model but thanks to these differences the bone rotation of the models are going crazy while animation plays. Maybe gltf use different system for these values ? because with gltf viewer the model is alright.

**Comment by oparisy** [comment]
Maybe this is related to the [coordinate change applied when exporting](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/46391f58b3a16b1834569bb1941622fe792b4dfd/docs/developer.md#coordinate-system-mapping)?

**Comment by ladiszlai** [comment]
No it's not "- not joints -"

**Comment by oparisy** [comment]
Oh! My bad.

**Comment by ladiszlai** [comment]
Can help me someone who is a developer of this addon how rotation values are generated ?

**Comment by ladiszlai** [comment]
I realized that its because when I made my skeleton there was rotation in the bone and gltf exported that, so the first blender values  show that it has no rotation with the mesh after attaching the skeleton.
