### ISSUE TITLE
Can we add a feature to preserve the vertex order?

### ISSUE THREAD

**Issue by edankwan** [KhronosGroup/glTF-Blender-Exporter#246]
Can we add a feature to preserve the vertex order?

**Comment by miirak** [comment]
Yeah please do this feature.

**Comment by emackey** [comment]
I haven't looked into this at all, but, what's wrong with it now?  I mean do all polygons have reversed order, or only some?  Does Blender use clockwise ordering for the front face?  I'm pretty sure glTF requires counter-clockwise vertex order for the front face of the polygons.

**Comment by donmccurdy** [comment]
Closing this issue, further development is happening on the new importer/exporter based on this project: https://github.com/KhronosGroup/glTF-Blender-IO.

Feel free to reopen the issue there, although I think we'll need more information about what reordering you see.
