### ISSUE TITLE
Smoothing group export

### ISSUE THREAD

**Issue by proteamer** [KhronosGroup/glTF-Blender-Exporter#25]
Hi,

Is it possible to export mesh with a few smoothing groups?

I've created simple [scene](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1115319/testcase.blend.zip) in blender with sphere and made half of sphere with sharp edges (Edit Mode: Mesh ‣ Edges ‣ Mark Sharp). You can see more information in [blender docs](https://docs.blender.org/manual/en/dev/modeling/meshes/editing/smoothing.html). See rendered example bellow:

![screen shot 2017-06-30 at 16 28 09](https://user-images.githubusercontent.com/1376014/27737714-e04bf856-5db1-11e7-8565-d3be7838c5c4.png)

Then I've exported glTF file with default settings and got next renderer image via glTF Extension for Visual Studio Code. Sharp edges are absent:

![screen shot 2017-06-30 at 16 28 52](https://user-images.githubusercontent.com/1376014/27737715-e20bc11c-5db1-11e7-9493-e87029641cee.png)

JFYI: I've also tied to export the scene as Collada:

<img width="561" alt="screen shot 2017-06-30 at 16 33 06" src="https://user-images.githubusercontent.com/1376014/27737717-e55f11b6-5db1-11e7-920b-83b09554c480.png">
It looks as expected.

**Comment by UX3D-nopper** [comment]
Generally, it is working (this is another, similar scene):
![grafik](https://user-images.githubusercontent.com/27856744/27744096-9306b614-5dbe-11e7-889b-2a83d1485870.png)

But when I export your scene, the information gets lost. Let me check.

**Comment by UX3D-nopper** [comment]
Okay, got it. I am setting the faces smooth, not the edges.

**Comment by UX3D-nopper** [comment]
Okay, this should fix it:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/d9451cd3ed30a83a73cbc0c7b7d96d854a0e0cf0

**Comment by proteamer** [comment]
Thanks for the fix!

I've tested it on me scenes and it works but I faced with another issue. In case of I'm disabling `auto smooth` then time of export significantly increases. For instance: I have the scene with 71k faces (26 objects) export `auto smooth` takes about 5 seconds and with `auto smooth` takes about 15 minutes.

Could you please take a look at it? Maybe we need to create another issue?

**Comment by UX3D-nopper** [comment]
The problem is - if auto smooth is enabled - the exporter has to scan each edge of the polygon.
I will create a ticket for this, as an enhancement.
Also, please note, that smoothing the faces has the same effect and the export should be much faster:
![grafik](https://user-images.githubusercontent.com/27856744/27755709-c6f5e41c-5df1-11e7-9c95-cdaa6fb7f357.png)

**Comment by UX3D-nopper** [comment]
Issue added here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/26

**Comment by UX3D-nopper** [comment]
Also, if you can share the scene, please go ahead.
If you can not chare the scene, maybe you can profile yourself, where the real bottle-neck is?
With `profile_start()` and `profile_end()` you can instrument the Python code. The result is printed out in the Blender console.

**Comment by proteamer** [comment]
I've add some profilers in exported code and figured out that the bottle-neck is:

``` python
if blender_mesh.use_auto_smooth:
    for edge_key in blender_polygon.edge_keys:
        blender_edge = blender_mesh.edges[blender_mesh.edge_keys.index(edge_key)]

        if blender_edge.use_edge_sharp:
            use_sharp = True
            break 
```
In case of disabled `auto smooth` time to convert polygon to primitive indices is `9.5367431640625e-07` seconds and with enabled `auto smooth` is `0.01264810562133789` seconds. So if we have [scene](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1117752/shpere.blend.zip) with 2048 polygons that we get next timings:

2048 * 9.5367431640625e-07 = **0,001953125**
2048 * 0.01264810562133789 = **25,9033203125**

> Also, please note, that smoothing the faces has the same effect and the export should be much faster

I actually use next pipeline: 3d Max -> export FBX -> Blender -> Import FBX -> Export glTF; I'm not sure that FBX accept smoothing the faces I will check it.

**Comment by UX3D-nopper** [comment]
I added an option (not uploaded yet), where you can disable the auto smooth check.
At a later point of time, I will check, how this can be made faster.

**Comment by proteamer** [comment]
This [scene](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1120089/normal_test.blend.zip) seems have incorrect normals after export. Could you take a look?

**Comment by UX3D-nopper** [comment]
![grafik](https://user-images.githubusercontent.com/27856744/27801583-0e23636c-601f-11e7-9a48-67a80288a3ef.png)
![grafik](https://user-images.githubusercontent.com/27856744/27801590-1431147a-601f-11e7-9e90-3a9e29866f9a.png)

In the above two images (Blender render and my internal renderer), auto smooth is disabled. The output seems to be correct. We will have a look at it, when auto smooth is enabled. But it will be an enhancement, as you can get the same result with another approach.
