### ISSUE TITLE
glTF Metallic Roughness: Missing textures when used in Node group

### ISSUE THREAD

**Issue by ldstein** [KhronosGroup/glTF-Blender-Exporter#251]
Hi,

I have a simple blend file comprised of two cubes with two different materials applied:

1. Material 1: glTF Metallic Roughness with a PNG linked to BaseColor
2. Material 2: glTF Metallic Roughness inside a node group, PNG linked to BaseColor

Both render fine in Blender but when exported as GLB/GLT, Material 2 is missing its texture.

Very possible (indeed likely) this is a user error issue. Appreciate any confirmation if the glTF group nodes are supposed to work inside custom group nodes.

Test project here: [gltf-missing-texture-test.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2132775/gltf-missing-texture-test.zip)

Screenshots:

Left Cube material nodes
![screenshot-blender-left-cube](https://user-images.githubusercontent.com/3657344/41846224-a10fed2e-78a8-11e8-9982-db1f387cb69b.png)
Right Cube material nodes (metallic roughness used inside custom group):
![screenshot-blender-right-cube](https://user-images.githubusercontent.com/3657344/41846227-a2c26ab6-78a8-11e8-93d4-c312f00e1574.png)
Result in Web Viewer
![screenshot-gltf-viewer](https://user-images.githubusercontent.com/3657344/41846232-a465e244-78a8-11e8-8e0e-4bee17cf1436.jpg)

**Comment by emackey** [comment]
I don't think this exporter looks inside user-defined custom nodes for copies of its own custom node.

glTF is meant to be capable of rendering at interactive rates across a wide array of platforms and hardware, and as such its core PBR material is defined specifically for this.  It cannot support the feature set of all of Cycles nodes and maintain this level of compatibility.  As a result, this exporter specifically searches for a known glTF node, and expects certain kinds of inputs to be hooked up to the node, if found.  Pushing the node down into another custom group, or hooking up the node in ways not described in the user documentation here, may render correctly in Blender but will not translate to glTF.

**Comment by ldstein** [comment]
Thanks all for the clarification!

**Comment by donmccurdy** [comment]
Closing as we now support Principled BSDF in glTF-Blender-IO (https://github.com/KhronosGroup/glTF-Blender-IO).
