### ISSUE TITLE
The alpha value of BaseColorFactor of Metallic-Roughness doesn't work in blender

### ISSUE THREAD

**Issue by Lee-Heisenbug** [KhronosGroup/glTF-Blender-Exporter#252]
I was making a box with a base color texture.
![basecolor-blender](https://user-images.githubusercontent.com/26576701/41965549-65cf2210-7a2f-11e8-9ff6-a1e8516d1555.jpg)

When the alpha was set to 0.5, the box was still opaque in blender.
![basecolorfactor-alpha-0 5-blender](https://user-images.githubusercontent.com/26576701/41966953-0a870950-7a33-11e8-8f0f-cca6af2a5138.jpg)

But the box was transparent in three.
![basecolorfactor-alpha-0 5-three](https://user-images.githubusercontent.com/26576701/41966789-a17538f6-7a32-11e8-92b8-2715acc051db.jpg)

As the [glTF 2.0 reference guide](https://www.khronos.org/files/gltf20-reference-guide.pdf) mentions, *the baseColorFactor contains scaling factors for the red, green, blue and **alpha** component of the color*. So the result in three is right. This might be a rendering issue in blender.

glTF Blender Exporter version: 1.0

The blender file: [BaseColorFactorAlpha.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2140728/BaseColorFactorAlpha.zip)

**Comment by donmccurdy** [comment]
This sounds like a limitation in Blender. In the new importer/exporter (https://github.com/KhronosGroup/glTF-Blender-IO) we're getting away from custom nodes and recommending the default Principled BSDF node.

**Comment by Lee-Heisenbug** [comment]
@donmccurdy Thanks for the info.
