### ISSUE TITLE
Bones export incorrectly if not descendants of one root bone for armature

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#253]
It looks like bones that are not children of one root bone for an armature become offset. This can be worked around by re-parenting the bones. I'm not sure if this is a mismatch between Blender and the glTF spec, so the exporter needs to do extra work to adjust, or if it's just a simple regression. The only recent, relevant PR I can think of is https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/177.

![39100284-4e81deda-463c-11e8-9d3b-92ea5cd06a22](https://user-images.githubusercontent.com/1848368/42127849-d16426ac-7c54-11e8-8e23-6d8addd98489.png)

![39100286-53ae3656-463c-11e8-9695-356711f63a00](https://user-images.githubusercontent.com/1848368/42127850-d65072d8-7c54-11e8-80ae-2938d8ed6df8.png)

**Comment by donmccurdy** [comment]
I'm not sure, but I think it is something different — 

1. the `Cube.002` mesh has more than 4 joint vertex influences, which can be limited with the *Limit Total* option in weight painting mode.
2. using the "Bake skinning constraints" option at export fixes the offset between the lower leg and the foot

Some of the meshes in the scene are not exporting for me, and I'm not sure why that is.

**Comment by soadzoor** [comment]
Yea, I figured out the "bake skinning constraints", thanks.
It's very strange, because in your viewer the "hair" and the "cheeks" are not visible. However, in the babylon viewer (http://sandbox.babylonjs.com/) they're visible, although they're on the ground. So I guess they're exported, but something is messed up with their position.

**Comment by donmccurdy** [comment]
Another possible issue is that many bones in this model have duplicate names. glTF doesn't require unique names, and I don't know whether the Blender Python API particularly does, but there are things in both this exporter and three.js that may break if names are not unique. It's also possible that this exporter just isn't working properly with multiple armatures in a single scene right now (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/232).
