### ISSUE TITLE
Armature modifier applies last pose when "apply modifiers" is active

### ISSUE THREAD

**Issue by karroffel** [KhronosGroup/glTF-Blender-Exporter#254]
As noted in https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/166#issuecomment-395833769, when exporting a model with an armature, the last pose before exporting will be *applied*.

This is pretty problematic, as it deforms all animations (unless the armature was in a rest pose anyway).

The FBX exporter addresses this problem by saving all armature states before the export, then setting all the armature states to REST, exporting the mesh with applied modifiers, then restoring the previous states.

This can be worked around by making sure that an action with the rest pose is on top in the NLA and the only strip contributing. But it can cause a lot of pain and confusion when setting up an initial workflow. It certainly took me a while to figure it out the first time!

(Actually I found this problem in another Blender exporter, a better COLLADA exporter for the Godot game engine, here the PR that fixed the problem: https://github.com/godotengine/collada-exporter/pull/65. I noticed this exporter has the same problem, so the PR in the other project might be helpful as a reference, as well as the standard FBX exporter in Blender).

**Comment by donmccurdy** [comment]
It looks like the FBX exporter just skips Armature modifiers, when "Apply Modifiers" is selected... do you know if that would be an acceptable fix here?

**Comment by donmccurdy** [comment]
Fixed in new repo (https://github.com/KhronosGroup/glTF-Blender-IO/), we no longer apply the Armature modifier when this option is enabled.
