### ISSUE TITLE
The normal scale of metallic roughness material doesn't look right in blender

### ISSUE THREAD

**Issue by Lee-Heisenbug** [KhronosGroup/glTF-Blender-Exporter#255]
The normal map of the test model:
![normal-map](https://user-images.githubusercontent.com/26576701/42144029-601cdd8e-7deb-11e8-85b0-4607bc5d9093.jpg)

**NormalScale = 1:**
Rendered Result in blender:
![normal-scale-1-blender](https://user-images.githubusercontent.com/26576701/42144145-2f703298-7dec-11e8-9994-0d891a6f54fb.jpg)
Rendered Result in three:
![normal-scale-1-three](https://user-images.githubusercontent.com/26576701/42144148-3477b84c-7dec-11e8-8c30-e2db3c6044dd.jpg)

**NormalScale = 0.5:**
Rendered Result in blender:
![normal-scale-0 5-blender](https://user-images.githubusercontent.com/26576701/42144166-4b7bb4da-7dec-11e8-8fb7-5225529820fe.jpg)
Rendered Result in three:
![normal-scale-0 5-three](https://user-images.githubusercontent.com/26576701/42144171-4f8e89c6-7dec-11e8-9cea-7359c9729422.jpg)

**NormalScale = 0:**
Rendered Result in blender:
![normal-scale-0-blender](https://user-images.githubusercontent.com/26576701/42144183-61579cc4-7dec-11e8-921d-57f9c635daeb.jpg)
Rendered Result in three:
![normal-scale-0-three](https://user-images.githubusercontent.com/26576701/42144187-694b7a40-7dec-11e8-8988-a140ca9212fb.jpg)

The images show that when the normal scale is lower the surface of the model seems to be darker in blender. When the normal scale is 0, the detail of the surface disappears in three.js but still shows up in blender.

Related Softwares:
Blender 2.79
glTF Blender Exporter 1.0
three.js r93

blender file: [normalmap.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2153728/normalmap.zip)

**Comment by donmccurdy** [comment]
Fixed in new importer/exporter (https://github.com/KhronosGroup/glTF-Blender-IO/) where we're using the Principled BSDF node rather than a custom metal/rough node.
