### ISSUE TITLE
Consider distributing releases

### ISSUE THREAD

**Issue by Alan-FGR** [KhronosGroup/glTF-Blender-Exporter#259]
It's not acceptable that you have to download this entire repository as instructed [here](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/scripts) just to get the few python scripts if you just want to export glTF files from Blender.

**Comment by Alan-FGR** [comment]
To make things worse GitHub doesn't allow you to easily download those files without a lot of clicks and afaik git also won't help you getting just some files/folder, best you can do is clone the whole shebang with depth=1 but that's the same as downloading the GitHub zip.

**Comment by nem0** [comment]
https://git-scm.com/docs/git-archive, or just use godot

**Comment by donmccurdy** [comment]
I think this would be a good enhancement, along with including version numbers in the code and `generator` field of exported assets.

**Comment by emackey** [comment]
Fully agreed we need versioned, dated releases.

This might be duplicate with #120.

**Comment by donmccurdy** [comment]
Closing, as glTF-Blender-IO is now shipping with the Blender 2.8 beta.
