### ISSUE TITLE
addon( image as planes) to import image then export cannot display

### ISSUE THREAD

**Issue by DarrenWong** [KhronosGroup/glTF-Blender-Exporter#260]
Learning to draw a flag following the tutorials: https://www.youtube.com/watch?v=Mwzz-Y6t-v8, 
Using original plane it can display after export as glTF2.0, but import use addon(image as planes) then export as glTF2.0 cannot display in the viewer or Threejs  as below pic. Is it glTF exporter not support the add-on (images as planes) ? I use default setting, export files including  image.jpg, bin and gltf,
Thanks

![screenshot from 2018-07-09 18-16-24_recompress](https://user-images.githubusercontent.com/5771106/42445253-2606c4c4-83a5-11e8-9388-09b6dc1376e8.jpg)

**Comment by DarrenWong** [comment]
sorry typo.. yes images as planes.
The flag is an image, but just not display in objectMode

**Comment by donmccurdy** [comment]
The "import image as plane" addon creates a material with transparency enabled and alpha set to 0.0, meaning the exported result is invisible. I have no idea why it does that, but unchecking the option in the material settings will fix it:

<img width="500" alt="screen shot 2018-07-09 at 8 08 02 pm" src="https://user-images.githubusercontent.com/1848368/42487051-0168abdc-83b4-11e8-815b-d35a1fcbf2d7.png">

**Comment by DarrenWong** [comment]
I try again and it works, thanks a lot
