### ISSUE TITLE
Exported Models Show No Materials on Facebook or Oculus

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [KhronosGroup/glTF-Blender-Exporter#261]
I downloaded this exporter so that I could create custom models and scenes in Blender and then add them to my Oculus Home environment. However, I have discovered that no materials, textures, or even colors are being exported despite me having checked all material and PBR-related options. I am using Blender 2.79, and have tested the exported models in both Oculus Home and Facebook's 3D model embedding system. I have attached both the .blend file for the test model and the exported .glb file.
[Test GLB Export.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2185299/Test.GLB.Export.zip)

**Comment by donmccurdy** [comment]
Hi @AwesomeAnimationGamer — this exporter does not yet support Principled BSDF materials, per https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/101. In the meantime we provide custom PBR nodes, described in the [user documentation](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md).

**Comment by AwesomeAnimationGamer** [comment]
Oh, I missed that part. Thanks!

**Comment by AwesomeAnimationGamer** [comment]
I'm still having issues. I found the file with the nodes and was able to transfer my current model over just fine. However, the exported model still shows no colors. Metallic roughness is preserved, but color data seems to be getting lost.
![hyperwarp engine 1](https://user-images.githubusercontent.com/13543820/42605325-4a26d05a-8545-11e8-8bb2-2118a0cbd59d.png)
![hyperwarp engine 2](https://user-images.githubusercontent.com/13543820/42605326-4a3975d4-8545-11e8-8de5-4f1c79b4015f.PNG)

**Comment by donmccurdy** [comment]
Yeah sorry, so a confusing bit on these nodes is that `BaseColor` needs to be an Image Texture. `BaseColorFactor` accepts simple color information like you're doing here. Hoping we can support Principled BSDF soon so that the normal workflows just work. 😅

**Comment by AwesomeAnimationGamer** [comment]
And something is still going wrong. The file exports as 1 KB and Facebook rejects it, saying it is unsupported. These are the options I have ticked in the export:
![export settings](https://user-images.githubusercontent.com/13543820/42606272-a79c30fe-854a-11e8-8fb2-30665cff9ee2.PNG)
And here is the bugged exported file:
[Hyperwarp Engine.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2186652/Hyperwarp.Engine.zip)
All I changed between the versions was to migrate the color data to BaseColorFactor.

**Comment by donmccurdy** [comment]
Hm well the file certainly looks empty. Are you able to share the `.blend` file?  Maybe something to do with that "selected only" checkbox?

**Comment by donmccurdy** [comment]
You may be able to get a little more info about the file from http://github.khronos.org/glTF-Validator/, which I believe is a large subset of the validation that Facebook uses during upload.

**Comment by AwesomeAnimationGamer** [comment]
I can confirm it was caused by the "Selected Only" checkbox. I guess it wasn't registering that I had the object selected already. It's working now, it seems the only thing that's still having a problem is the Emissive texture. It stays gray in Facebook's 3D view regardless of the color set in Blender. (Emissive component on PBR node has no differing effect to the basic emissive shader)

**Comment by donmccurdy** [comment]
Hm, I don't know what to make of the emissive texture issue. Does the emissive color appear on http://sandbox.babylonjs.com/ or https://gltf-viewer.donmccurdy.com/? You also can't use an Emissive node, the texture must be wired into that same glTF PBR node's `Emissive` slot.

Note that neither of those viewers (nor Facebook) apply bloom post-processing, so you won't get that nice emissive glow, but just a solid color unaffected by lighting.

**Comment by AwesomeAnimationGamer** [comment]
It does indeed show up that way. Hopefully it affects lighting in Oculus Home, but if not then this will be just fine too. Thank you so much for your help! Hopefully I'm closing this for good now.

**Comment by donmccurdy** [comment]
Sure thing! I think Sketchfab's viewer should show emissive nicely if you want to upload the GLB there.  We also have a glTF gitter chat (https://gitter.im/KhronosGroup/glTF) if you want to ask one-off questions. :)

**Comment by AwesomeAnimationGamer** [comment]
I just tested. I have to tweak the model itself, but it works perfectly in Oculus Home! The Emissive part doesn't necessarily cast light but it has a nice little glow effect around it.
