### ISSUE TITLE
Exporter can't handle internal images

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-Exporter#264]
First reported in #237 by @FreakTheMighty.

If an image has been created internally in blender, such as by baking or a UV grid image, and saved into the Blend file with "pack as PNG", it may not have an actual image file on disk.

Currently, our exporter crashes on such images, and does not export the model at all.  This is because we try to copy existing images, like JPG files, to avoid a decode/re-encode round trip.  The exporter should detect whether the source file exists, and only copy it when it's available, otherwise save a new version.

Here's a test file:  [InternalImageTest.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2189022/InternalImageTest.zip)  In this file, a cube has a packed-as-PNG UV grid image applied, but there is no corresponding PNG on disk.  The exporter should save a new PNG from Blender's image data.

**Comment by sonygod** [comment]
I got the same error!can't export image with fbx embed media

**Comment by emackey** [comment]
@sonygod As a workaround, you can have Blender save the image to disk, and then replace the internal image with the saved image.

**Comment by FreakTheMighty** [comment]
Hey, just wanted to call attention to my comment here: https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/237#issuecomment-404713858

The concern with my original work around was that it was lossy in the case of existing compressed images, but I'm not sure that's the case.

**Comment by emackey** [comment]
Thanks @FreakTheMighty.  I haven't had a chance to dig into the save/load stuff yet to test this.

**Comment by donmccurdy** [comment]
Fixed at https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/314. I haven't looked at the `save_render` question — if that's still a problem, could we open a new issue?
