### ISSUE TITLE
Modifiers exported in the wrong order

### ISSUE THREAD

**Issue by soadzoor** [KhronosGroup/glTF-Blender-Exporter#266]
I made a very simple blend file to demonstrate this problem:
- It's an animation with the help of an armature (try playing the animation in blender)
- The armature modifier is the first modifier of the mesh in blender
- When I export it to glTF with "apply modifiers" checked, it seems that the mirror modifier is applied before the armature modifier, so the animation gets distorted

Try dropping the glb file here: https://gltf-viewer.donmccurdy.com/, and you'll see. The animation looks the  same as if I changed the order in blender, and played it internally (in blender).

[Armature.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2195705/Armature.zip)

**Comment by donmccurdy** [comment]
Would it be acceptable to just skip the Armature modifier, when "Apply Modifiers" is selected? See https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/142.

**Comment by soadzoor** [comment]
> Would it be acceptable to just skip the Armature modifier, when "Apply Modifiers" is selected? See #142.

I think so, yes. Or maybe better: have a separate toggler for that, if possible?

**Comment by donmccurdy** [comment]
The new exporter (https://github.com/KhronosGroup/glTF-Blender-IO) is skipping the Armature modifier by default and that seems to be working well (armatures are exported regardless). I don't think a separate option is needed but we can consider it if so.
