### ISSUE TITLE
Empties with children are duplicated when exporting selected

### ISSUE THREAD

**Issue by Capital-Asterisk** [KhronosGroup/glTF-Blender-Exporter#267]
It turns out that empties, and also point lights, get duplicated when objects are parented to them. The issue only happens when the "Export selected only" is enabled. Both have the exact same transformation definitions, extra properties, and name. The only difference is that one lists children and the other one does not. I could not find anything in the specification to indicate that this is intentional. 

    "nodes" : [
        {
            "mesh" : 1,
            "name" : "Cube",
            "translation" : [
                -1.9036643505096436,
                -4.57893180847168,
                -1.1928699016571045
            ]
        },
        {
            "mesh" : 0,
            "name" : "Cube.001",
            "translation" : [
                -1.9036645889282227,
                -4.57893180847168,
                -1.192870020866394
            ]
        },
        {
            "children" : [
                0
            ],
            "name" : "Empty",
            "translation" : [
                1.9036645889282227,
                4.57893180847168,
                1.1928701400756836
            ]
        },
        {
            "name" : "Empty.001",
            "translation" : [
                -2.578963279724121,
                3.178974151611328,
                -0.6574060916900635
            ]
        },
        {
            "children" : [
                1
            ],
            "name" : "Empty.002",
            "translation" : [
                5.122903347015381,
                3.958202838897705,
                1.3997524976730347
            ]
        },
        {
            "name" : "Empty",
            "translation" : [
                1.9036645889282227,
                4.57893180847168,
                1.1928701400756836
            ]
        },
        {
            "name" : "Empty.002",
            "translation" : [
                5.122903347015381,
                3.958202838897705,
                1.3997524976730347
            ]
        }

**Comment by donmccurdy** [comment]
Hi! How recently did you install or update the exporter? @emackey submitted a fix July 11 that may have solved this.
