### ISSUE TITLE
Adding bones changes mesh coordinate system in GLTF viewer

### ISSUE THREAD

**Issue by DariusV21** [KhronosGroup/glTF-Blender-Exporter#269]
Hello!

I am trying to make a simple sliding door animation for my GLTF viewer and keep running into this problem:
When i parent my objects (doors) with the separate bones (ctrl + p > Bone) in blender it all looks good, but if i export this scene to GLTF format and look at it in GLTF viewer - doors are misplaced as if coordinate system has changed. Misplacing happens even when there are no animations nor any actions made.

Is this a bug or am i doing something wrong?

This is what i have and what i get:
https://imgur.com/a/slVP6o2

My blender file: 
https://blend-exchange.giantcowfilms.com/b/5024/

**Comment by DariusV21** [comment]
Found a couple issues with similar problems: #155 and #74 which i found very helpful.
Workaround to this problem is:
> ...to create joints and weights for this mesh and give full weight to the bone it is assigned to.

**Comment by donmccurdy** [comment]
Glad you were able to work around the issue! Closing this bug but will leave #74 open to track.
