### ISSUE TITLE
Cannot find GLTF specific nodes

### ISSUE THREAD

**Issue by mastayoda** [KhronosGroup/glTF-Blender-Exporter#27]
Hello there,

First of all thanks so much for this effort, it is a life saver!
The issue: I have exported many of the examples in the repo and works like a charm, but when I open any other blender project I cannot add any of the GLTF specific nodes... It does not appear in the menu or the search, the rendering engine is selected as Cycles. Any idea why?

**Comment by lexaknyazev** [comment]
You need to load glTF materials before using them, as described here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/pbr_node

**Comment by UX3D-nopper** [comment]
As Alexey said, you need to link one of the items. After you linked them, you can add a group 'glTF Metallic Roughness' or 'glTF Specular Glossiness' in the cycles node editor.
At the moment, this is explained in a minimal form. We will add a better documentation plus images the next days.

**Comment by mastayoda** [comment]
Thanks so much for all for the responses! I got it working :). One last thing, this may not belong to this issue. In my case, I'm not a Blender pro, so this may be silly: Is there a way to instead of editing all my Cycles nodes and replace shader nodes with GLTF specific, just add a final node to 'capture' all shaders and be able to export? For example, a new gltf node between a Mix shader and Material output:

[NODES IMAGE](https://ibb.co/cKKwf5
)

**Comment by UX3D-nopper** [comment]
If I understand you correct - in short - this is not possible.

We use Cycles and the glTF node groups to simulate as best the PBR materials from glTF 2.0. So anything else - a Cycles node tree - cannot be converted to a glTF 2.0 PBR material.

We know, editing every Cycles material again is time consuming but there is not way around.
But you need to "see" this process from converting a ray/path tracing (Cycles) to a real-time (glTF 2.0) material.

**Comment by mastayoda** [comment]
Thanks so much! I understand now. In any case, this is an amazing job. I will try to understand the entire workflow and every node, maybe a *plugin* that converts from Cycles nodes pipeline to an equivalent GLTF node group may be possible, this way the change is done automatically(or semi). I will give it a try! Thanks so much for the support!

**Comment by UX3D-nopper** [comment]
I think the glTF 2.0 materials section plus the rest of the document should now answer this question:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md
