### ISSUE TITLE
Export animation with extra values for the animated property

### ISSUE THREAD

**Issue by Lee-Heisenbug** [KhronosGroup/glTF-Blender-Exporter#270]
Here's the .blend file:
[simple-translate.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2218415/simple-translate.zip)

I made an animated cube. The animation only has two keyframes, and the cube just do a simple translation animation. And I found something interesting when I look into the exported glTF file.

The animation data:
![animation](https://user-images.githubusercontent.com/26576701/43065284-f370646c-8e93-11e8-848c-1a6fbefd39b4.jpg)

The input data(represents the time):
![time](https://user-images.githubusercontent.com/26576701/43065373-37dc949a-8e94-11e8-9176-bf0b96f81820.jpg)

The output data(represents the animated property):
![value](https://user-images.githubusercontent.com/26576701/43065377-3a02652e-8e94-11e8-8ae9-bfed50eecf16.png)

In my opinion, the length of output data should be 6( 3 times as 2 ) instead of 18, right?

When I load this file using three.js, the length of values of a track is also 18.
![three](https://user-images.githubusercontent.com/26576701/43065656-0fa3e374-8e95-11e8-8f91-1196bf5e9a4f.jpg)

Is this a bug?

**Comment by emackey** [comment]
No I believe this is correct.  The `CUBICSPLINE` interpolation method is [specified](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animation-samplerinterpolation) to store 3 times the data, for the sake of storing two tangent/control points along with the keyframe.  Additionally, your output format is `VEC3` to store positions.  So the resulting output array then is `3 * 3 * 2` floats long.

**Comment by donmccurdy** [comment]
^Yes, this differs from the default cubicspline interpolation in three.js, which doesn't preserve "handles" and just estimates a smooth curve between control points. When using linear or discrete interpolation, you'll see the usual number of values.

**Comment by Lee-Heisenbug** [comment]
I see. But there is a little problem here. I want the animation play just one time and stop at the last frame, the animation seemed to stop at the first frame.
![simple-animation](https://user-images.githubusercontent.com/26576701/43113878-dba41ba8-8f2e-11e8-9fc5-b72104bfe07b.gif)

Then I tried to export the scene again with "force sample animation" checked, the aniamtion worked as expected. But the animation data was larger.
![simple-animation-sampled](https://user-images.githubusercontent.com/26576701/43113888-e25ab010-8f2e-11e8-878e-11d4aa032a19.gif)

Is this fixable? Should I make sure the "force sample animation" is checked if I wanna export aniamtion?

**Comment by donmccurdy** [comment]
I think the issues you're describing now just have to do with settings in the three.js animation API, probably. See [action.clampWhenFinished](https://threejs.org/docs/#api/animation/AnimationAction.clampWhenFinished) for example. The glTF file itself does not specify whether the animation should loop, freeze, etc.

 Note that if you've checked "export within playback range" and "force sample animation" you may be exporting many empty keyframes if the playback range goes farther than your actual keyframes.
