### ISSUE TITLE
Can hidden mesh be excluded from export?

### ISSUE THREAD

**Issue by ffreling** [KhronosGroup/glTF-Blender-Exporter#272]
Hi,

I have a Blender scene with a few meshes whose visibily are set to false.
I would like to keep them in the Blender file but not display them in the glTF file.

Is there such an option? I know about `Export selected only` but I would like the same behavior with `Export visible only`.

Or maybe inside the glTF file there is a way to know if a mesh is visible, but I couldn't find it.

Any insight will be appreciated :)

**Comment by donmccurdy** [comment]
You can use layers and disable the "export all layers" option at export, so that only the first (?) layer will be exported. I'd prefer not to add a third filter option, although perhaps improving the existing two would be worthwhile. I'm not sure if disabling "export all layers" exports only the first layer, or all active layers. An "Active layers" checkbox (defaulting false) might be clearer.

**Comment by emackey** [comment]
The existing "export all layers" thing does treat the first layer as "special" and it will be the only layer exported when all layers are not selected.  For what it's worth, I personally disagree with this behavior, and I think that the toggle should be between *visible* layers vs. all layers, not layer 1 vs. all layers.  Luckily, the default is all layers, so it's not much of a problem.

I do like the idea of not exporting hidden objects.  Such objects do not render into Blender's final output, so it would make sense to exclude them from glTF as well.  I don't know if we need yet another toggle to allow them to pass; I'm more inclined to just drop them from the export.  Thoughts?

**Comment by donmccurdy** [comment]
Yeah, I'd be fine with excluding hidden meshes by default, maybe comparing against other Blender exporters first to ensure this is consistent. My main concern was just having another UI toggle to think about.

**Comment by ffreling** [comment]
I already use layers to arrange my scene, I'd like to not have to put everything inside one layer.

I understand than adding a new UI toggle will make the export a bit heavier, but I think there is value in it.

Thanks for the replies.

**Comment by donmccurdy** [comment]
Per https://github.com/KhronosGroup/glTF-Blender-IO/issues/107 we will need to adjust how this works in 2.8, let's continue discussion there.
