### ISSUE TITLE
Exporter generates animation samplers with "input" and "output" fields as "-1"

### ISSUE THREAD

**Issue by alexGuntha** [KhronosGroup/glTF-Blender-Exporter#273]
Hello,

I tried to do some tests first using the Monster model from the glTF-Sample-Models repository ( [url](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Monster) ), then using the original blender file from the 3drt website ( [url](http://www.3drt.com/3dm/free/3drt.com-free-monster-animated-character.zip) ) to tweak the model to see if my importer still works.

(Also, I noticed the blender version of the model is very different from the sample file, but that's another story.)

After exporting this model, either as .glb or .gltf, 4 animation samplers have their "input" and "output" fields set as "-1". However, the spec says these fields are required, and should be both >= 0 .
[url](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#animation-sampler)

I provide you with a zip file containing both the .gltf and .glb versions of the exported file.
[monster.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2245148/monster.zip)

Tested with blender 2.79

**Comment by donmccurdy** [comment]
That official sample was created with COLLADA2GLTF, which would be the reason for the inconsistency. See https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/sourceModels/Monster for the source.

It looks like this model contains bones with duplicate names (e.g. `Bip01 Tail`), which may be one issue, but probably not the core problem here. The exporter writes `-1` when it encounters something it can't handle but still wants to avoid failing altogether. If there were a way to display user-facing warnings after an export, that would be much better. In the logs, I see: `ERROR: Invalid count 0`. Not sure yet what else is going on.

**Comment by donmccurdy** [comment]
Filed https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/277.

**Comment by donmccurdy** [comment]
Closing as future work on skinning will be in the new repository (https://github.com/KhronosGroup/glTF-Blender-IO). There are some known issues open there, but we're working on it.
