### ISSUE TITLE
Animation looks choppy after export

### ISSUE THREAD

**Issue by alexGuntha** [KhronosGroup/glTF-Blender-Exporter#278]
Hello,

I did some tests using the sample files' Cesium Man ([https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan)). I imported it in Blender 2.79 using Julien Duroure's importer, both 0.3.0 and 0.4.0 ([https://github.com/julienduroure/gltf2-blender-importer](https://github.com/julienduroure/gltf2-blender-importer)), then, without doing any change, exported it in .glb.

The choppiness looks obvious in gltf-viewer ([https://gltf-viewer.donmccurdy.com/](https://gltf-viewer.donmccurdy.com/)). (Additionnally, the texture and the bind pose seem to have been lost in translation, if I trust the viewer).
I see the same result when I import it in my engine.

I attached a zip file with both version of the CesiumMan.glb file.
[CesiumMan_issue.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2276282/CesiumMan_issue.zip)

I first suspected the importer of doing something wrong, but the animation looks fine in Blender after the import.

**Comment by donmccurdy** [comment]
The new exporter (glTF-Blender-IO) appears to have fixed this issue.
