### ISSUE TITLE
Saving export settings for new files and globally

### ISSUE THREAD

**Issue by moll** [KhronosGroup/glTF-Blender-Exporter#282]
Hey,

I'm not sure if this should already work or not, but how would one save or reuse exporter settings without setting them manually for every new and old file? I'm aware there was some work done for the "Save Settings" button in (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/119), but from my brief tests it only works for saving settings inside a single existing file. Doesn't seem to work for the startup file nor provide a way to quickly load settings for existing files. I propose it'd be a convenient feature to have. Similarly to, let's say, the OBJ exporter's presets work.

While we're on the topic of saving settings, I must say I don't understand the "pin" mechanism and find it unintuitive. I initially thought "Save Settings" would save the currently chosen settings _once_. After a second look, it has a pin icon that seems to toggle. Which of these states is the one that saves settings? When it does save settings? After changing something? Where does it save settings? (I know this now, but without looking through GitHub issues, you can't tell). While presets would be feature work, I reckon doing a bit of rewording of the save button would improve its usability. Killing the confusing pin toggle and going with a does-what-you-expect "Save Settings to Current File" wording would be a good start.

Thanks!

**Comment by donmccurdy** [comment]
Fixed in the new project, glTF-Blender-IO.
