### ISSUE TITLE
Installing as zip

### ISSUE THREAD

**Issue by andreyrd** [KhronosGroup/glTF-Blender-Exporter#283]
Not sure why the installation process documented is so complicated.
You can simply zip the `io_scene_gltf2` folder and use "Install Add-on from File..." in Blender.

Should the docs be updated?

**Comment by Vinc3r** [comment]
and maybe it could be a good way to use the [release page](https://github.com/KhronosGroup/glTF-Blender-Exporter/releases) of github, to simplfy even more the process?

**Comment by donmccurdy** [comment]
If that is install process works consistently for different OSes, then yes I think we should update the documentation.

@McNopper do you know if there was some issue here?

**Comment by McNopper** [comment]
Should work on any OS and yes, the docs could be updated. The manual process is more for developers.

**Comment by donmccurdy** [comment]
Closing, as glTF-Blender-IO is now shipping with the Blender 2.8 beta.
