### ISSUE TITLE
Normalizing weights to sum to 1

### ISSUE THREAD

**Issue by moll** [KhronosGroup/glTF-Blender-Exporter#286]
Hey,

As per https://github.com/KhronosGroup/glTF/pull/1352 and https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/#skinned-mesh-attributes weights must now sum up to 1. Am I wrong to say that weights are not yet normalized by the exporter given the recent spec change? I played around with it and think I did end up with a model with weights beyond 1.

Thanks!

**Comment by donmccurdy** [comment]
Merging with https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/275.
