### ISSUE TITLE
Exporting Shaders/Changing Textures 

### ISSUE THREAD

**Issue by jamestreno** [KhronosGroup/glTF-Blender-Exporter#287]
Hi all, 

Was wondering if it is possible to change shaders/textures after exporting from Blender. So far it seems that the textures are baked into the mesh which makes it impossible to change textures. 

Also was wondering if there is a way to attach a roughness and metalness map to the GLTF metallic roughness node.

**Comment by donmccurdy** [comment]
Could you clarify what sort of changes you mean? If you're exporting to `.glb`, try exporting to `.gltf` instead and you'll see a more human-readable version of the glTF asset, with textures in external files for easier edits. It's certainly possible to change the textures after export.

"Image Texture" nodes may be attached to the glTF metallic roughness node at the "MetallicRoughness" input. The packing is RGB = Occlusion, Roughness, Metallic.

**Comment by donmccurdy** [comment]
Related: https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md#pbr-materials

**Comment by jamestreno** [comment]
Hi, sorry if I wasn't clear. I've tried to export in .gltf format for this and I am able to see the mesh which is a cube with a basic texture that I made within Blender. I am trying to accomplish a colour change within the program in the future so I have a couple of shaders/textures which I have made at the same time.

So I was wondering if there was a way to export either a shader or the mesh so that it would be easier for me to change the texture or shader in the program. As whenever I've tried exporting the mesh, it seems to bake the texture into the mesh and I am not able to change the texture.

**Comment by donmccurdy** [comment]
Textures are never baked into a mesh, they remain as image assets that can be changed by tools capable of doing so.

I don't know what program you're using, or what part of the glTF PBR material you're trying to change, so I do not know how to help you more than that sorry. Whatever program it is, you probably want to ask there about how to edit an imported model. Generally programs can edit meshes and materials the same way, regardless of what format was used to load them.

**Comment by mzpq01** [comment]
What about FBX format that exported from 3dx max with the setting of "embedded media" turned on? It creates a single file with baked texture and lighting condition(if you render is and then apply the rendered texture back). And if you use this fbx model, it does not need real time render but a flat shader instead. So is that possible to apply a flat shader to such model? In one word, is that possible to apply flat shader to fbx model with baked texture(including all the lighting effects)?

**Comment by mzpq01** [comment]
> Textures are never baked into a mesh, they remain as image assets that can be changed by tools capable of doing so.
> 
> I don't know what program you're using, or what part of the glTF PBR material you're trying to change, so I do not know how to help you more than that sorry. Whatever program it is, you probably want to ask there about how to edit an imported model. Generally programs can edit meshes and materials the same way, regardless of what format was used to load them.

What about FBX format that exported from 3dx max with the setting of "embedded media" turned on? It creates a single file with baked texture and lighting condition(if you render is and then apply the rendered texture back). And if you use this fbx model, it does not need real time render but a flat shader instead. So is that possible to apply a flat shader to such model? In one word, is that possible to apply flat shader to fbx model with baked texture(including all the lighting effects)?

**Comment by donmccurdy** [comment]
Embedded textures and flat shading are two different things. Textures can be embedded into the model file — so there's only a single file — regardless of whether PBR or a flat/unlit/shadeless material is used.

I'd also mention that even when textures are embedded, they're not "baked" in any permanent sense. You can still separate the textures back out, edit them, swap them, and so on.

In Blender, the *Shadeless* checkbox can be used for flat shading, so that lighting does not affect the material. I don't know whether the FBX exporter applies that when exporting to FBX. The latest version of the glTF exporter currently does not (https://github.com/KhronosGroup/glTF-Blender-IO/issues/83), but you can still turn off lighting after loading the model into a game engine or something.
