### ISSUE TITLE
Export produces texture files on one computer but not another

### ISSUE THREAD

**Issue by cfravel** [KhronosGroup/glTF-Blender-Exporter#289]
I have an Asus laptop that produces textures with gltf export
I have new MSI laptop that does not.
On both machines installed the gltf exporter as instructed using Option 1 of the detailed instructions (copying the directory, enabling the addon)

Here is what I've done:
1. Asus laptop, Windows 10, updates are current.
2. New scene, delete the box
3. Use Blender Render
4. Import an FBX that was exported from Maya. // renders materials in Blender 
5. Export gltf // export materials checked
6. I get texture files  (I don't if I did the FBX import & gltf export in Cycles render mode)
7. MSI laptop, Windows 10, updates are current.
8. New Scene, delete the box
9. Use Blender Render
10. Import same FBX // renders materials in Blender
11. Export glTF // export materials checked
12. I get gltf and bin, but no textures

I have reviewed the settings in the two Blender installations, they look the same.
I have tried this with both the 2018-03-24 and 2018-07-28 versions of the gltf exporter, no difference in this respect.
What else do I need to consider?
Should I expect that the texture files would export when in Blender Render mode?  (They do on my Asus)

**Comment by cfravel** [comment]
More info:

If i bring the .blend file that I created on the Asus over to the MSI and export from that, i get the texture files exported.

**Comment by donmccurdy** [comment]
This project is soon going to be replaced with the newer importer/exporter, https://github.com/KhronosGroup/glTF-Blender-IO, which comes included with Blender. We haven't had any reports of similar issues there, so I'm going to consider this closed, but if the problem persists please open an issue on the new repo.
