### ISSUE TITLE
Question about material extension

### ISSUE THREAD

**Issue by Arcnor** [KhronosGroup/glTF-Blender-Exporter#29]
Sorry if this is not the right place for questions, but I don't see any other channel for this kind of thing.

I see that the exporter uses the `KHR_materials_cmnBlinnPhong` extension for materials. However, this doesn't seem to be the same extension defined at https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common (that name is not even found in the whole of the repository, including issues). Also, it doesn't seem to be the same extension ThreeJS implements (that one seems to be called `KHR_materials_common` and it seems to match a bit what the official repository discuss in some issues)

So the question is, where is this extension defined? I'm trying to implement an exporter and viewer, but I'm finding it very difficult to support all extensions out there, as there seems to be little in the way of documentation.

Thanks in advance, and again sorry if this is not the right channel.

**Comment by donmccurdy** [comment]
Hi @Arcnor — the core glTF2.0 spec is finalized, including PBR, but the extensions for common materials are not final yet. The previous versions used `KHR_materials_common` for common materials, but it's likely we'll switch to `KHR_materials_cmnBlinnPhong` when this is agreed upon. 

So, the Blender exporter is closer to where I think things will end up, but that feature is still experimental (and hasn't been implemented in three.js yet). Assuming no major changes, we'll probably implement `KHR_materials_cmnBlinnPhong` in three.js in a few weeks.

**Comment by Arcnor** [comment]
Ok, thanks for the information. Any place where I can find where/when this happens? As I said, the only place where this extension is even named on what it appears to be the whole Internet is this repository 😄 .

In any case, I'll change my exporter to the new thing soon as well, although I'm guessing even if ThreeJS supports the new standard, is going to ignore the `ambientTexture` for example, as it ignores `ambient` right now, am I correct? In that case I'll probably check Babylon instead, as my exporter needs to work with all properties without changes.

Thanks again!

**Comment by donmccurdy** [comment]
You can subscribe to updates on these: https://github.com/KhronosGroup/glTF/issues/947 https://github.com/KhronosGroup/glTF/pull/633

But that's correct; three.js doesn't do a separate ambient color or map on phong materials, and it's possible ambient will be omitted from glTF's blinn-phong extension in the end, too. If that's a problem for you please weigh in [here](https://github.com/KhronosGroup/glTF/issues/947). :)

**Comment by Arcnor** [comment]
Thank you again @donmccurdy , I'll probably do although I don't see mention of dropping support for `ambient` on that ticket. In any case, I'll subscribe to those tickets.

**Comment by UX3D-nopper** [comment]
Thanks a lot Don for answering the questions.
In the coming days, we will create a schema for the extension plus a short documentation.
We will then make a pull request and if the glTF 2.0 working group accepts the extension, it will be an offical one.
Please note, any extension listed in the experimental section are not final and/or official.
As soon as an experimental extension is accepted, it will be listed somewhere else in the exporter.

**Comment by Arcnor** [comment]
Thank you both, I'll keep an eye on the repository for the new PR and adapt my code if needed.

**Comment by UX3D-nopper** [comment]
I am closing this, as the effort of the extension can be tracked here:
https://github.com/KhronosGroup/glTF/issues/947
