### ISSUE TITLE
(Bone) name mangling bug

### ISSUE THREAD

**Issue by Usnul** [KhronosGroup/glTF-Blender-Exporter#295]
Bone names are mangled during export. As a user I want to control the names of the bones so I can find them later. 

Currently exporter turns this:
![image](https://user-images.githubusercontent.com/5939063/44989625-bca5cf00-af8e-11e8-8af6-f1d6004a14e3.png)

into this:
![image](https://user-images.githubusercontent.com/5939063/44989638-c7f8fa80-af8e-11e8-901c-b8ae357dc61e.png)

**Comment by donmccurdy** [comment]
Is the second screenshot in threejs? Periods and some other punctuation are stripped in GLTFLoader using THREE.PropertyBinding.sanitizeNodeName, because they break threejs animation binding.

**Comment by Usnul** [comment]
Okay, but what about prepending the parent name?

**Comment by donmccurdy** [comment]
Looks like that part is the exporter. Not sure why, though. /cc @McNopper

**Comment by donmccurdy** [comment]
This issue is fixed in glTF-Blender-IO, although there are some other bugs with armatures that we're working to fix.
