### ISSUE TITLE
Simple spline translation animation not exported correctly

### ISSUE THREAD

**Issue by mosra** [KhronosGroup/glTF-Blender-Exporter#299]
Attached is a reduced test case from a larger animated scene, containing just three translation keyframes on a single object. Playing the animation in Blender results in a movement, but the exported glTF file (exporter commit 49032f9c0eac05f00e4853badceb8c14a1c2d6cc) has three keyframes with a `CUBICSPLINE` interpolation that are *all the same* and thus not moving anywhere. Every keyframe has the following value:

```
CubicHermite(Vector(0, 0, -0), Vector(-0.00908947, 0.0330051, 0.00744379), Vector(0, 0, -0))
```

The ZIP file contains the original `*.blend` and an exported `*.gltf` + `*.bin` file. The translation track is contained in the `*.bin` starting at position 212 (0xd4).

[bezier_single_particle.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2381024/bezier_single_particle.zip)

Exporting the file with animation resampled to linear works correctly. I tried to redo the animation from scratch in an attempt to discover what might be triggering this bug, but no luck.

Thank you!

Cc: @steeve @ffreling

**Comment by donmccurdy** [comment]
It looks like this is working correctly in https://github.com/KhronosGroup/glTF-Blender-IO, could you confirm?


![169117cf-742e-4e40-859a-7d8782391286-21255-00024edd5c922f66](https://user-images.githubusercontent.com/1848368/49355199-57d83e80-f67b-11e8-8cac-38b302491155.gif)

**Comment by mosra** [comment]
Yes, I can confirm, works for me with IO as well.

**Comment by donmccurdy** [comment]
Further development will be happening on the https://github.com/KhronosGroup/glTF-Blender-IO repository, so I'm gradually closing on moving older issues.
