### ISSUE TITLE
Binary export not compatible with Three.js GLTF2Loader

### ISSUE THREAD

**Issue by wpk-** [KhronosGroup/glTF-Blender-Exporter#3]
When I export the default Blender scene (cube, light, camera) to glb, with the default settings, the GLTF2Loader in Three.js finds an unexpected token in the JSON data (and thus fails to parse).

Of course the error could be on either side -- export or loader. Would you know of any tool I could use to validate the glb?

**Comment by lexaknyazev** [comment]
The error is on the exporter side.

@UX3D-nopper
Chunk length mustn't include chunk header, i.e., it must be 8 bytes fewer.

**Comment by McNopper** [comment]
Validated with commit:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/a01092d528f38df3530b4254613a06da3268060e

**Comment by UX3D-nopper** [comment]
See above, thx McNopper :-)
