### ISSUE TITLE
doesn't export quick smoke

### ISSUE THREAD

**Issue by daton89** [KhronosGroup/glTF-Blender-Exporter#300]
i'm trying to export a model to use it in three.js, it's important for me that after import on threejs i can see the smoke effect and the particles, but unfortunately this doesn't happen.

i don't know if is an issue or i'm doing something wrong in my project, so i've attached the blender project and a screenshot of my export settings. 

can someone please help me to figure out what's wrong? 

Here you can fin the blender project:
[Explosion-Export.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2392489/Explosion-Export.blend.zip)

These are the options of the glTF exporter addon:
![42058792_571571029963228_5463545760287031296_n](https://user-images.githubusercontent.com/6856342/45685295-34582a00-bb49-11e8-9d9d-f814c8af7a08.png)

These are the node of the quick smoke:
![42108766_1872912529495313_4977608848270426112_n](https://user-images.githubusercontent.com/6856342/45691737-6ec9c300-bb59-11e8-8ba2-1a8dc592ae6d.png)

**Comment by donmccurdy** [comment]
The effect will need to be converted to a mesh or points to be represented in glTF — the format does not preserve/convert node trees or volume shaders, and I'm not sure how to represent it in three.js if glTF did. If there is another format that can do this I'd be curious to know, but I think you're using features of Blender that are not likely to be export-compatible.

**Comment by donmccurdy** [comment]
There are many features in Blender that have no equivalent in portable formats or runtime engines, and fluid animation is in that category. Unfortunately I think the best you can do would be to export each frame of the animation to a separate mesh. Here is the [same question for FBX+Unreal](https://blender.stackexchange.com/questions/36521/how-to-export-fluid-animation-100-prebaked-and-import-to-ue4) and [another related discussion on Modo](http://community.foundry.com/discuss/topic/74923/importing-blender-fluid-simulation-with-particles-into-modo?mode=Post&postID=676363), which both also came back to exporting a mesh per frame.

It [may be possible](https://blender.stackexchange.com/questions/89803/copied-and-pasted-a-working-fluid-simulation-objects-and-settings-to-another-ble) that Alembic can export the animation, but I have no idea whether three.js's Alembic loader can play it back sorry.
