### ISSUE TITLE
Reflection between objects ( three.js & gltf2 & blender 2.79 )

### ISSUE THREAD

**Issue by blend3dweb** [KhronosGroup/glTF-Blender-Exporter#301]
Good afternoon.
 I am export two models from Blender 2.79 to three.js.
Scene:[https://www.blend3dweb.ru/projects/test_reflection.html](url)
Shadows work. Objects reflect the world around them but do not reflect among themselves.

Scene  code:

                         //MR -  YES mirror
            var loader = new THREE.GLTFLoader();
            loader.load( '/gltf/1.gltf', function ( gltf ) {

                gltf.scene.traverse( function ( node ) {

                    if ( node.isMesh || node.isLight ) node.castShadow = true;
                    if ( node.isMesh || node.isLight ) node.receiveShadow = true;

                } );

                       gltf.scene.traverse( function ( child ) {

                    if ( child.isMesh ) {

                        child.material.envMap = envMap;
                    }

                } );
                gltf.scene.position.x = 0;
                gltf.scene.position.y = 0;
                gltf.scene.position.z = 0;

                       scene.add( gltf.scene );

            } );
                         //MR -  YES mirror
            var loader = new THREE.GLTFLoader();
            loader.load( '/gltf/2.gltf', function ( gltf2 ) {

                gltf2.scene.traverse( function ( node ) {

                    if ( node.isMesh || node.isLight ) node.castShadow = true;
                    if ( node.isMesh || node.isLight ) node.receiveShadow = true;

                } );

                gltf2.scene.traverse( function ( child ) {

                    if ( child.isMesh ) {

                        child.material.envMap = envMap;

                    }

                } );
                    gltf2.scene.position.x = 0;
                    gltf2.scene.position.y = 0;
                    gltf2.scene.position.z = 0;

                    scene.add( gltf2.scene );

            } );`

Render reflection in Blender
![1](https://user-images.githubusercontent.com/43431061/45797604-0c82d680-bcaf-11e8-90e9-bad4452b9549.png)
How to implement reflections between objects?
![2](https://user-images.githubusercontent.com/43431061/45797665-5a97da00-bcaf-11e8-8543-27c6e717338e.gif)

Is it related to the exporter?

**Comment by Vinc3r** [comment]
it's related to Three.js

**Comment by emackey** [comment]
Blender is using the Cycles renderer in your screenshot.  Note how long it takes to produce an image: It's quick, but not nearly fast enough for a video game's framerate.  Cycles is doing "Path Tracing" on the CPU, and it takes time to trace the paths and find those reflections.  That's not something that a realtime interactive renderer can do (yet).  ThreeJS and all the other interactive renderers just show environment reflections on shiny surfaces, not traced reflections.  It's common practice to make local reflection environments for objects that need to show their surroundings.

Last month, NVIDIA made headlines by announcing a new line of hardware realtime ray tracing.  I don't have hands-on experience with one, but in theory this is the first step to accomplishing what you're asking for here, with realtime ray-traced reflections.  But be aware, it may take quite some time before raytracing hardware becomes commonplace, and it could be months or years before we see support for that appearing in WebGL where ThreeJS and others can access it.

But for the short-term at least, you'll need to work around the idea that objects only reflect environment maps, and place and structure assets accordingly.

**Comment by blend3dweb** [comment]
Look at an example: [https://www.blend3dweb.ru/projects/reflection.html](url)
Export from blender. Mutual reflection and reflection of the world? It is Blend4Web.
Whether development of such function for the gltf exporter is possible?

**Comment by Vinc3r** [comment]
it's surely not have to do with an exporter, but with the 3d engine. in blend4web both exporter & engine are linked and developped by the same team. 
don't know about 3js, but in BJS for example you can use a mirrorPlane to do what you want ([example](https://www.babylonjs-playground.com/#2EP7UB#0) - line 70)

**Comment by blend3dweb** [comment]
All thanks.
