### ISSUE TITLE
Exporting only selected objects doesn't quite work for lights

### ISSUE THREAD

**Issue by godlikepanos** [KhronosGroup/glTF-Blender-Exporter#304]
I've opened the 04_lights.blend scene. I've selected only one light in the scene and then tried to export it. In the exporter options I have both "Export selected only" and "Export KHR_lights" checked.

The output gltf file doesn't have all the information about the light I selected:

[04_lights.txt](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2409080/04_lights.txt)

When I unckeck "Export selected only" seems to work fine.

**Comment by donmccurdy** [comment]
In https://github.com/KhronosGroup/glTF-Blender-IO/issues/107 we will need to change how this export works, most likely to simply export visible objects only rather than using selection and layers. Let's continue discussion there.
