### ISSUE TITLE
What are the limitations of the glTF exporter (specifically allowed inputs)

### ISSUE THREAD

**Issue by JeremyBYU** [KhronosGroup/glTF-Blender-Exporter#305]
Hi,
I'm not a blender/modelling expert so may be using incorrect terminology. I have been fiddling around with textures on meshes and exporting them with this glTF exporter but have run into some issues .  If I just use a simple image texture and connect it to the baseColor pin on an `GlTF metallic roughness` group then I can successfully see rendered textual result in blender *and* export and see all textures in other gltf viewers.  

![image](https://user-images.githubusercontent.com/6628085/45987463-94fecf80-c03f-11e8-8db9-4be5ad26b91a.png)

However if I try to `mix` the texture  using the `MixRGB` node with an attribute node (some other color) and connect the output to the same `GlTF metallic roughness`  group then blender renders correctly but **the export** is not successful, gltf viewers will not have the texture visable.

![image](https://user-images.githubusercontent.com/6628085/45987491-bbbd0600-c03f-11e8-8b02-b145fe0139c9.png)

It seemed to me that mixing the color was not a "compatible workflow" that the exporter was expecting. I looked at some other issues, notable Issue #251.  It states the following:
  
>  As a result, this exporter specifically searches for a known glTF node, and expects **certain kinds of inputs** to be hooked up to the node, if found

I was wondering what are the "certain kinds of inputs" that are allowed. And when the author says "input" I'm thinking it means: Any node in the "chain" from the left side of the node editor all the way to the final connection to the KronosGroup created node group.  I'm trying to convert someone else's model/material and it makes use of the following nodes before connecting to the input of `GlTF metallic roughness` :

*  DiffuseMask
*  RGB Mix
*  Separate XYZ
*  Multiply

Any of these supported?

Here is an overview of the material I am trying to make export compatible if it helps to understand what I'm trying to do.

![image](https://user-images.githubusercontent.com/6628085/45987694-f7a49b00-c040-11e8-855e-49a4962c6fd5.png)

Thanks for any help and appreciate the work of this project.

**Comment by garyritchie** [comment]
Hey @JeremyBYU the allowed inputs are listed in the table under [PBR Materials](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md#pbr-materials).
Only noodles from a Texture node are permitted, otherwise your setting a color or numeric value in the node group itself.

What you could do is pre-bake your custom cycles nodes down to texture maps.

**Comment by JeremyBYU** [comment]
Oh wow, I seemed to have missed that section. Though it doesn't seem to have anything explicit to say about baseColor, but I assume it's the same as the normal texture. 

Okay I will research this notion of "prebaking" and see what I can do. Thank you for your help!

**Comment by donmccurdy** [comment]
@garyritchie do you happen to know if Blender has Python APIs for baking cycles nodes to textures?

**Comment by garyritchie** [comment]
Factor is multiplied with baseColor. I hit that speed bump, too.

I recommend taking a look at "polly" blend file here: https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly as it has several material setups.

![image](https://user-images.githubusercontent.com/853094/46035178-7268c700-c0d0-11e8-9190-6f4993cbc6ac.png)

**Comment by garyritchie** [comment]
> @garyritchie do you happen to know if Blender has Python APIs for baking cycles nodes to textures?

Not a python developer here, so this looks a bit foreign, and sparse, to me: https://docs.blender.org/api/current/search.html?q=bake&check_keywords=yes&area=default

Baking cycles textures isn't too difficult. You set the Bake Type to Emit and use this setup, selecting each bake target texture in turn:
![image](https://user-images.githubusercontent.com/853094/46035920-39c9ed00-c0d2-11e8-86b0-47034798f748.png)

Normal maps are different and I found a node group for that: http://digicreatures.net/articles/cycles-normal-baking.html

**Comment by donmccurdy** [comment]
That looks like what I needed, thanks! :)

**Comment by JeremyBYU** [comment]
Thanks @garyritchie  for your help. So after a little more experimenting I believe I have learned the following.You can mix colors with an Image Texture in two ways:

Manual Color
1.  You are right that the baseColorFactor (which I think you meant when saying "factor") can be used to successfully mix colors and be exported. 
2. The baseColorFactor has to be manually entered for a proper export. Meaning you click on the baseColorFactor parameter and select a color.

Variable/Programmatic Color
1. You can set USE_COLOR_0 to 1.0  and attach an attribute node (like vertex color) to use COLOR_0. 
2. This color will then be mixed with the baseColor texture. It can be successfully exported.
3. However you can't really control the 'mixing'. It seems to use the multiply form of mixing and has a hard-coded fraction of 1.0. I learned this by inspecting the Khronos Node Group.

Wondering if there is a way to control the mixing. I manually changed the node group settings for mixing fraction, it updated in realtime in blender to what I wanted, but when I export it doesn't seem to take.  This makes me think that the python code for this extension for exporting also needs to be updated or taken in account. 

Overall, I think I will should do the prebaking idea. However, I probably would do it programmaticly with the python API.

Thanks!
