### ISSUE TITLE
Exporting glb deletes texture file (jpg)

### ISSUE THREAD

**Issue by saschandroid** [KhronosGroup/glTF-Blender-Exporter#307]
I'm using the pbr node tree from glTF2.blend. I exported the model as glb into the same directory where the texture and model files are saved. After the export is finished, all used texture files (jpgs) in this folder are gone/deleted by the exporter. This only happens if I use jpgs (pngs are still there) and the filenames and image names in the shader nodes are equal. 

To reproduce:
1. setup pbr shader node for gltf/glb
2. open/drag "usedtexture.jpg" into shader node
3. set "usedtexture.jpg" = Image.name (the default node name in blender) 
4. export glb (where export folder = import/texture folder)
5. exporter deletes "usedtexture.jpg" from disc permanently

Possible fix (?): rename Image.name in nodes before exporting or use different names for temporarily saved files

**Comment by donmccurdy** [comment]
This is fixed in the new exporter (https://github.com/KhronosGroup/glTF-Blender-IO).
