### ISSUE TITLE
Extra camera included on export

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#31]
I have a scene containing two cameras, `pasted__camera1` and `pasted__camera2`, and I deleted the default camera. After exporting, my glTF contains three cameras:

```
    "cameras" : [
        {
            "name" : "Camera", 
            "perspective" : {
                "aspectRatio" : 1.703595982340029, 
                "yfov" : 0.5033799409866333, 
                "zfar" : 100.0, 
                "znear" : 0.10000000149011612
            }, 
            "type" : "perspective"
        }, 
        {
            "name" : "pasted__camera1", 
            "orthographic" : {
                "xmag" : 0.30000001192092896, 
                "ymag" : 0.30000001192092896, 
                "zfar" : 100.0, 
                "znear" : 0.0010000000474974513
            }, 
            "type" : "orthographic"
        }, 
        {
            "name" : "pasted__camera2", 
            "perspective" : {
                "aspectRatio" : 1.0, 
                "yfov" : 0.6606064438819885, 
                "zfar" : 100.0, 
                "znear" : 0.0010000000474974513
            }, 
            "type" : "perspective"
        }
    ]
```

The first is unexpected — perhaps the active camera from the editor, even though it's not technically the scene?

[camera_test2.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1126721/camera_test2.blend.zip)

**Comment by UX3D-nopper** [comment]
If you save the object and load again, the problem should be gone. Will check the Blender 'user' count and filter otu these objects.

**Comment by UX3D-nopper** [comment]
This should fix it:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/b1dac0a204bf7cd31ca7710f5f91056e69f05d31

**Comment by donmccurdy** [comment]
Thanks! :)
