### ISSUE TITLE
exporting only wireframe

### ISSUE THREAD

**Issue by raaaas** [KhronosGroup/glTF-Blender-Exporter#310]
is there any way to skip all material/texture/etc and export only wireframe ?

i want to make file as small as possible

**Comment by donmccurdy** [comment]
You can disable materials in the export settings, which I believe will also remove textures, to export only geometry.

That is somewhat different from exporting a wireframe, though. This exporter does not support the glTF "LINES" primitive, but it isn't really a space-saving option anyway — the number of vertices will be similar to a triangulated mesh. To render a wireframe, you'll probably want to use viewing options in your engine.
