### ISSUE TITLE
Exported camera is weirdly positionned

### ISSUE THREAD

**Issue by nagman** [KhronosGroup/glTF-Blender-Exporter#316]
I've made an export of my scene, including the cameras, and I want to use this camera in place of the three js camera I've built.
But when I do this, my camera is totally f***ed up and I don't understand why.

### Some screenshots
Here's my scene in Blender:
![capture](https://user-images.githubusercontent.com/16116486/46610449-114ae580-cb0b-11e8-8611-ea7d830db50c.JPG)

From the camera:
![capture2](https://user-images.githubusercontent.com/16116486/46610454-1740c680-cb0b-11e8-949e-4b1eb7d393d0.JPG)

From the camera, with textures:
![capture3](https://user-images.githubusercontent.com/16116486/46610462-1c9e1100-cb0b-11e8-92f4-f859d68f4a08.JPG)

And in the browser, using Three.js:
![capture4](https://user-images.githubusercontent.com/16116486/46610609-83232f00-cb0b-11e8-8d62-52a65eafb100.JPG)

### How I did this
In my main file:
```
import * as THREE from 'three';
import Ground from './Ground';

[...]

let camera = new THREE.PerspectiveCamera();
new Ground(scene).then(ground => {
  camera = ground.camera;
});

[...]

renderer.render(scene, camera);
```

And my Ground.js file:
```
import * as THREE from 'three';
import GLTFLoader from 'three-gltf-loader';

const Ground = scene => {
  return new Promise((resolve, reject) => {
    const loader = new GLTFLoader();
    loader.load('models/ground.gltf', gltf => {
      let camera;
      gltf.scene.traverse(node => {
        if (node.isCamera) camera = node;
      });
      const ground = gltf.scene.getObjectByName('Ground');
      scene.add(ground);
      resolve({camera});
    });
  });
};

export default Ground;
```

**Comment by emackey** [comment]
That looks like clipping.  Maybe set the near plane closer?

**Comment by nagman** [comment]
Up. Any clues?

**Comment by emackey** [comment]
Could be a bug.  I'll flag it.

**Comment by Lee-Heisenbug** [comment]
@nagman I think this issue( #265 ) might explain what is going on to your camera.

**Comment by donmccurdy** [comment]
Could you share an example `.blend` file? You can attach ZIP files to GitHub comments.

**Comment by nagman** [comment]
Hi @donmccurdy, I've finally recreated entierely my camera in Three js.
I don't have a special .blend file to show you, it's just a simple camera with no extra options.
I don't think it's related to blender, instead the gltf plugin.

**Comment by nagman** [comment]
@donmccurdy I've just done a test with http://gltf-viewer.donmccurdy.com/ and it works with a simple scene exported from Blender.
As I've dropped this issue some weeks ago because I've recreated the camera in threejs, I'm closing this.
If I encounter the same bug in the future, I'll reopen this issue.
