### ISSUE TITLE
wrong scale units

### ISSUE THREAD

**Issue by ranbuch** [KhronosGroup/glTF-Blender-Exporter#317]
I've tried to export a simple cube from `blender` to `glTF`.

In the first time I've exported it when scene scale was `INCHES`.

The second time the scene scale was `Centimeters`.

Both `glTF's` looks exactly the same, as did the `bin` files.

Shouldn't you convert the units on export to `Meters`?

When using the models on AR scale really meters . . .

**Comment by emackey** [comment]
glTF doesn't define what scale its units are.  Certain products (Cesium and STK) always interpret those units as meters, for real-world sizes.  Other apps may choose other units, especially if they want to show individual molecules or entire galaxies.  But the configured Blender units don't have any bearing on the output glTF file, so it's up to the user to ensure that the same units are used for all models that will be in the scene together.

**Comment by lexaknyazev** [comment]
@emackey 
In "Coordinate System and Units" part of the spec:
> The units for all linear distances are meters.

**Comment by emackey** [comment]
Missed that one, sorry!

I looked at Blender 2.80's unit system, and it's different from 2.79 in that changing the units changes the reporting.

In Blender 2.79, if you take the default cube (with +/- 1 meter vertices), and switch the units to "Inches", you'll see the vertices are reported at +/- 1 inch in the new system.

In Blender 2.80, take the same cube and switch the units to "Imperial" (no more inches etc), and the default cube is now reported as having vertices at +/- 3.28084ft.  The resulting glTF has accessors with min/max bounds at +/- 1.

So, I'd consider this resolved, fixed on the Blender side of things.

**Comment by ranbuch** [comment]
@emackey forgive me if I've misunderstood you but I don't understand the connection between `Blender's` specifications and [glTF](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0) specifications.

Even if someone is using an old version he should export the model in the right scale.

And event more important, from what you have wrote it looks like while exporting inches on `Blender 2.8` you will still get wrong scale.

**Comment by emackey** [comment]
Hi @ranbuch,

> from what you have wrote it looks like while exporting inches on `Blender 2.8` you will still get wrong scale.

I believe Blender 2.80 has the units sorted out correctly.  In the case I described, 1 meter equals 3.28084 feet, so, switching Blender's UI units and seeing this value show up on the default cube means that they have decided to keep their internal units as meters, and adapt the UI to show the user's configured units.  The glTF exporter exports the internal units, not the adapted ones, so, you're seeing meters in the exported file, regardless of what you've chosen to display on the UI (and as @lexaknyazev corrected me, meters are the official length units of glTF, so this is correct behavior).

Blender 2.79 took a different approach.  Changing the display units on the UI results in a change in the reported actual scale of the model.  For example, if changing from meters to feet, all 1-meter measurements in 2.79 became 1-foot measurements, and the overall scale of the model became incorrect.  I don't think our exporter has any good way to compensate for this, given the way the model lacks a coherent internal representation.  So, I'm glad they fixed this in 2.80.
