### ISSUE TITLE
Duplicated skins and nodes

### ISSUE THREAD

**Issue by Arcnor** [KhronosGroup/glTF-Blender-Exporter#32]
For a model I've imported from FBX, the resulting GLTF file contains 6 skins (which seem to be an exact copy of one another) where only 2 of them are used. Also, it seems that the armature node has as its children 2 nodes pointing to the same mesh, which if I understand the process correctly, will render the mesh twice.

I've attached screenshots of the Blender tree and a representation of the GLTF using a tool I'm developing, which (hopefully) should be readable enough. I can share the Blender file if required (as I understand that screenshots might obviously not be enough to debug this) but I need to do so privately, as the model is not free nor owned by me.

![model_blender_exporter](https://user-images.githubusercontent.com/28616/27896919-5ffda77c-6260-11e7-981d-54e13c62f601.jpg)

EDIT (pressed send too quickly after attaching): As you can see, there are two nodes ending in `.001` not present in the Blender tree below. Those two nodes are pointing to the same meshes to their non-001 counterparts (`meshes[0]` and `meshes[1]`, respectively) but only the non-001 ones contain a pointer to the skin.

![blender](https://user-images.githubusercontent.com/28616/27896928-6e924590-6260-11e7-98bd-0a91680e0bc2.jpg)

**Comment by UX3D-nopper** [comment]
Seems to be same problem:
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/31

Let me fix this and retest again. If the problem still occurs, please send me the file.

**Comment by Arcnor** [comment]
Thanks, will watch the other ticket, then, although at least part of my problems look different, but let's retest when you finish :).

**Comment by Arcnor** [comment]
Also, applying the workaround you had in that ticket helped a bit (saving the scene, then reloading). The duplicate nodes are gone, and also now I "only" have 4 skins. However, I can't find references for 2 of those skins, so I think they are still not supposed to be there :).

**Comment by UX3D-nopper** [comment]
Okay, I have uploaded the fix:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/b1dac0a204bf7cd31ca7710f5f91056e69f05d31

Please try again. If the bug stil occurs, reopen the ticket and send me the file for debugging.
