### ISSUE TITLE
NormalScale and Roughness texture not working in VR windows mixed reality home environment

### ISSUE THREAD

**Issue by ankervold** [KhronosGroup/glTF-Blender-Exporter#324]
I made a test environment to look at wood floor textures for a custom mixed reality home environment. Looking at the environment in mixed reality viewer, babylonjs sandbox and gltf-viewer.donmccurdy.com all the textures export as expected from blender. When looking at the actual environment in VR with a lenovo explorer there’s some problems. 

The NormalScale does not change the texture, the normal map is there but it stays at the same factor (looks like 1.0) no matter what the NormalScale is set to. 

The features of the Roughness texture do not show at all. There was no difference in having a connected roughness texture and only the color texture. The RoughnessFactor did work when it’s only a color texture or color and roughness texture connected.

When the Roughness texture and Normal texture are both connected the RoughnessFactor does not work, 0, 0.5, 1 all look the same. The texture looks as if the RoughnessFactor is set at 0 (glossy reflective) no matter what when they are both connected. 

Link to the glb. https://drive.google.com/open?id=11rXojREXfPnyCPfSDdP5TcFS27YDpaua

**Comment by donmccurdy** [comment]
Not sure but I think Windows MR devices may require some extra processing via https://github.com/Microsoft/glTF-Toolkit.

/cc @bghgary

**Comment by bghgary** [comment]
@najadojo Can you help?

**Comment by najadojo** [comment]
Sorry for the late reply this isn't a forum we monitor for Windows Mixed Reality issues. The best route to providing feedback is through the [Feedback Hub](https://www.microsoft.com/en-us/p/feedback-hub/9nblggh4r32n?activetab=pivot:overviewtab). This method will get us detailed information about what your operating environment is as well. It is also worth your while to make sure you've updated to Windows 10 October 2018 Update, it contains a number of glTF related fixes and added support.

We do have an open issue with Normal Texture Scale in Windows Mixed Reality environments. For example the test asset from [glTF-Asset-Generator - Material 04](https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Material/Material_04.gltf) fails to render correctly. I'm not sure what issue you might be facing with roughness textures I'm unaware of any bugs in this area, for example [glTF-Asset-Generator - Material MetallicRoughness 10](https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Material_MetallicRoughness/Material_MetallicRoughness_10.gltf) renders the same as the sample engines.

**Comment by ankervold** [comment]
These screenshots should make it easier to see. If you compare the roughness texture 4,5,6 (middle three) to the 7,8,9 (right three) in the mixed reality home they look identical but in the gltf viewer you can see the details of the roughness texture in 7,8,9. 

Also in the 1,2,3 (far left) you can see when the Roughness texture and Normal texture are both connected the RoughnessFactor does not work, 0, 0.5, 1 all look the same. The texture looks as if the RoughnessFactor is set at 0 (glossy reflective) no matter what when they are both connected.

I'm fully updated for windows, latest nvidia drivers, gtx 1070 i5-6600k, I do put it down to 60hz from 90hz though since it did black in and out at 90. Very high(beta) and high settings give me more detailed shadows but doesn't effect roughness or normal maps that I could tell. 
 
I haven't tried the glTF toolkit and asset converter because I mostly just use blender, visual studio is a little beyond my skills, but it may solve the problem. 
![20181209_195224_mixedreality](https://user-images.githubusercontent.com/42947756/49706322-3afbb800-fbf3-11e8-89f3-c1c5854bb7ab.jpg)
![annotation 2018-12-09 202449](https://user-images.githubusercontent.com/42947756/49706323-3cc57b80-fbf3-11e8-9dc9-ef20677ba08c.jpg)
![20181209_195247_mixedreality](https://user-images.githubusercontent.com/42947756/49706326-3f27d580-fbf3-11e8-8028-8aad761f614f.jpg)
![annotation 2018-12-09 202518](https://user-images.githubusercontent.com/42947756/49706328-418a2f80-fbf3-11e8-88c0-70b7f1caff16.jpg)
![20181209_195302_mixedreality](https://user-images.githubusercontent.com/42947756/49706332-44852000-fbf3-11e8-9516-da1f823a2c4b.jpg)
![annotation 2018-12-09 202550](https://user-images.githubusercontent.com/42947756/49706335-47801080-fbf3-11e8-9d26-597cc53235ba.jpg)
![20181209_195336_mixedreality](https://user-images.githubusercontent.com/42947756/49706343-52d33c00-fbf3-11e8-906f-a3939e3fd113.jpg)
![annotation 2018-12-09 202607](https://user-images.githubusercontent.com/42947756/49706347-55ce2c80-fbf3-11e8-8881-496541df9067.jpg)
![20181209_195354_mixedreality](https://user-images.githubusercontent.com/42947756/49706350-5797f000-fbf3-11e8-9724-38c1eca9779d.jpg)
![annotation 2018-12-09 202813](https://user-images.githubusercontent.com/42947756/49706351-5a92e080-fbf3-11e8-93ee-2525ce9affab.jpg)
![20181209_195402_mixedreality](https://user-images.githubusercontent.com/42947756/49706369-74ccbe80-fbf3-11e8-9b64-9c237fb9c059.jpg)
![annotation 2018-12-09 202832](https://user-images.githubusercontent.com/42947756/49706377-7f875380-fbf3-11e8-8a40-9a171f4cdf1a.jpg)
![20181209_195409_mixedreality](https://user-images.githubusercontent.com/42947756/49706398-b2c9e280-fbf3-11e8-9f1e-066a8f7b3c0b.jpg)
![annotation 2018-12-09 202904](https://user-images.githubusercontent.com/42947756/49706399-b65d6980-fbf3-11e8-815f-0f68af5cfb4c.jpg)
![20181209_195417_mixedreality](https://user-images.githubusercontent.com/42947756/49706400-ba898700-fbf3-11e8-9c2e-1b11ac1601f0.jpg)
![annotation 2018-12-09 202921](https://user-images.githubusercontent.com/42947756/49706402-bc534a80-fbf3-11e8-87ac-90b5f66e3b30.jpg)
![20181209_195427_mixedreality](https://user-images.githubusercontent.com/42947756/49706404-be1d0e00-fbf3-11e8-9d96-eebd3abaaa2e.jpg)
![annotation 2018-12-09 202943](https://user-images.githubusercontent.com/42947756/49706405-bfe6d180-fbf3-11e8-97d4-fcb0b5ce5677.jpg)
![annotation 2018-12-09 201318](https://user-images.githubusercontent.com/42947756/49706419-d1c87480-fbf3-11e8-908f-076090c4bfc1.jpg)
![annotation 2018-12-09 201447](https://user-images.githubusercontent.com/42947756/49706421-d2f9a180-fbf3-11e8-9c2c-a7e674e56e29.jpg)
![annotation 2018-12-09 201549](https://user-images.githubusercontent.com/42947756/49706423-d42ace80-fbf3-11e8-8e36-3e8ef25cf2fa.jpg)
![annotation 2018-12-09 201554](https://user-images.githubusercontent.com/42947756/49706424-d55bfb80-fbf3-11e8-95b9-7646387a299c.jpg)
![annotation 2018-12-09 201614](https://user-images.githubusercontent.com/42947756/49706425-d68d2880-fbf3-11e8-9df8-31d26441a036.jpg)

**Comment by donmccurdy** [comment]
Closing as external bug, remaining issue can be tracked in https://github.com/KhronosGroup/glTF-Blender-IO/issues/165.
