### ISSUE TITLE
Infinite projection matrix export

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Blender-Exporter#33]
Please, add an option to omit `zfar` for perspective cameras. 

Spec issue with details: https://github.com/KhronosGroup/glTF/issues/722

**Comment by UX3D-nopper** [comment]
This should implement it:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/cf56068706f4348699438e1f6417a6561dd6ec9f

Nice catch!
