### ISSUE TITLE
Image Data Block ID indexing

### ISSUE THREAD

**Issue by AlexRadacki** [KhronosGroup/glTF-Blender-Exporter#331]
We used the Unity FBX Exporter to convert our Unity Scene to FBX and then the glTF-Blender-Exporter to get a gltf. This works quite well, but all objects end up with the same texture. The reason seems to be a data-block id indexing bug. Since Blender doesn’t allow same-named unique ids, they get renamed with a [.n] suffix. e.g. A duplicate of [ImageName] becomes [ImageName.001], [ImageName.002] … This suffix gets lost somewhere in the exporting process so all objects end up with just [ImageName] as the image data block id.
The issue can be fixed manually by removing the dot from the ids. ([ImageName.001] to [ImageName001]) so we think that the dot acts as a trim char.

**Comment by donmccurdy** [comment]
I'm not sure what change is needed here — do you have a `.blend` that shows the problem? How does a data-block ID get represented in the exported glTF? Or are you saying the `.blend` is being modified during export?

**Comment by AlexRadacki** [comment]
[BlenderGLTFExportExample.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2648358/BlenderGLTFExportExample.zip)
This example demonstrates the problem very well: Two objects with single-user materials textures and image file data. When the images get labeled with the same name e.g. "Image", blender adds a suffix [.001] to one of them. If you now export this .blend to a gltf, the suffix gets stripped and all textures point to the same image - to the first one without a suffix. So all objects end up with the same image. You can see that in the gltf file:

```json
"materials" : [
        {
            "extensions" : {
                "KHR_materials_unlit" : {}
            },
            "name" : "Material",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [...],
                "baseColorTexture" : {
                    "index" : 0
                },
                "metallicFactor" : 0.0,
                "roughnessFactor" : 0.9
            }
        },
        {
            "name" : "Material.001",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [...],
                "baseColorTexture" : {
                    "index" : 0 <--this_should_be_"1"
                },
                "metallicFactor" : 0.0
            }
        }
    ],
    "meshes" : [...],
"textures" : [
        {
            "sampler" : 0,
            "source" : 0
        },
        {
            "sampler" : 0,
            "source" : 0  <--this_should_be_"1"
        }
    ]
```

If you edit these values and reload the gltf, the images get assigned correctly.

**Comment by donmccurdy** [comment]
I see, thanks!

**Comment by donmccurdy** [comment]
This has been fixed in the new importer/exporter: https://github.com/KhronosGroup/glTF-Blender-IO.
