### ISSUE TITLE
Material parameters not exporting with glTF2_Principled shader

### ISSUE THREAD

**Issue by PatrickRyanMS** [KhronosGroup/glTF-Blender-Exporter#334]
I just pulled latest from the glTF-Blender-Exporter repo to test alpha modes in Blender. I used the glTF2_Principled shader like I normally do to wire up a simple test:

![blenderalphamode](https://user-images.githubusercontent.com/31326855/48728618-45c1bf00-ebea-11e8-80b8-902b6dbeff3b.PNG)

The blue cube is fully opaque. The green cube is using 0.5 alpha with an AlphaMode of 0 so I should get alpha blend mode. The red cube is using 0.5 alpha with 0.5 AlphaCutoff and an AlphaMode of 1 so I should get alpha clip mode and not render the red cube at all. When exporting, I ensure the export materials is checked:

![blenderexport](https://user-images.githubusercontent.com/31326855/48728765-c2549d80-ebea-11e8-87a8-2f8166ec0cbd.PNG)

However, when I export, I get no material parameters in the resulting glTF:

![blendermaterials](https://user-images.githubusercontent.com/31326855/48728780-cb456f00-ebea-11e8-9259-d60eec3cd68e.PNG)

The mesh renders correctly with no materials in a glTF viewer and the rest of the file seems intact, just no material parameters. Blender scene and glTF export are linked below for you.

[BlenderTestAlpha.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2596697/BlenderTestAlpha.zip)
[AlphaTest.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2596691/AlphaTest.zip)

**Comment by donmccurdy** [comment]
`BaseColor` must be an *Image Texture* node, whereas `BaseColorFactor` accepts colors as you're doing here. I think `Alpha` also has to be an *Image Texture*, and the scalar alpha could come from `BaseColorFactor`? This is a recurring source of confusion, in https://github.com/KhronosGroup/glTF-Blender-IO we will support Principled BSDF nodes.

**Comment by PatrickRyanMS** [comment]
Yes, this is a very misleading part if the Blender UI. Now that I see your post, I remember this was the case and just don't normally use Blender. I would suggest, if possible going forward, to add the word "Texture" to inputs that need to be textures. I don't know if there's a way to remove the ability to set values on inputs that can only accept textures, but that would be the ideal solution. Thanks for the quick response!
