### ISSUE TITLE
BasicColorFactor Animation not exporting

### ISSUE THREAD

**Issue by vin-ni** [KhronosGroup/glTF-Blender-Exporter#335]
Hi,
I'm trying to animate the material color of a sphere.

Unfortunately the color of the sphere stays the same as in the first frame. Is there a different way to get the material animations going? I followed this [tutorial](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md) to apply the material.

Here are two screenshots of the transformation I'm trying to achieve:
<img width="1219" alt="bildschirmfoto 2018-11-21 um 18 31 29" src="https://user-images.githubusercontent.com/9806572/48858652-37c39800-edbc-11e8-9ed0-74301578d14c.png">
<img width="1245" alt="bildschirmfoto 2018-11-21 um 18 31 21" src="https://user-images.githubusercontent.com/9806572/48858653-37c39800-edbc-11e8-8cad-67c311ad4735.png">

Thanks a lot!

**Comment by donmccurdy** [comment]
Sorry, the glTF spec does not yet support animation of material properties. I think we'll get there eventually, but in the meantime the exporter can't implement it.

**Comment by vin-ni** [comment]
Is there any other tool you know of I can use to achieve this?

**Comment by emackey** [comment]
I recall there was interest in animated materials in the past, and even an extension proposal, but those efforts seem to be on hold for now:  https://github.com/KhronosGroup/glTF/pull/1301#issuecomment-422932982

I don't know of other formats that support it, perhaps there are some.  For glTF we'd be interested in an updated or new extension proposal, but implementation could be a challenge for some engines.

**Comment by donmccurdy** [comment]
> Is there any other tool you know of I can use to achieve this?

Where and how do you need to use the result? No tool will be able to create a glTF file that achieves this, because the format doesn't allow it. Depending on where you need to use the model, another format may or may not be available.

I do think we should follow up on the extension proposal at some point though.

**Comment by vin-ni** [comment]
Just in a normal three js screne.
I haven't done that much with it yet, but wouldn't it be the same as animating position by just updating the material color?

**Comment by donmccurdy** [comment]
Unfortunately, I don't think there is any model format where both (1) the format supports animated materials, and (2) the three.js loader for that format also supports it. I checked for COLLADA and FBX, anyway, it's not impossible that their may be others. I do expect this will arrive in glTF eventually, and at that point THREE.GLTFLoader will support it. In the meantime, if you are able, you might be able to add support to THREE.ColladaLoader.

It's not particularly hard to implement animation of materials in three.js, using JavaScript, but creating the data format and tooling for authoring is a bit more work. :)

**Comment by vin-ni** [comment]
Alright, I'll try that.
Thanks!
