### ISSUE TITLE
Optional enabling/disabling of the lights exports

### ISSUE THREAD

**Issue by thmxv** [KhronosGroup/glTF-Blender-Exporter#336]
Sometimes we just want to export a 3D model but have lights in the Blender scene just to allow previewing/rendering of the said model. For such cases, it would be nice to have an option to enable or disable the export of the light objects; just like we have for the cameras already.

**Comment by donmccurdy** [comment]
It does have an option, `Export KHR_lights`, I think? That should only be visible if you've enabled experimental settings in the addon preferences, and shouldn't be exporting light unless it's enabled. Do you get a different result?

Also, this exporter implements a draft version of the glTF lights spec. You'll want to switch over to https://github.com/KhronosGroup/glTF-Blender-IO if you need lights — that project will eventually replace this one.

**Comment by thmxv** [comment]
You are right on all account. I did not see the experimental settings and thought the lights were exported by default.

I don't need lights, at the contrary I don't want to export them.

I din't even know about the other add-on. I will switch to it as soon as it is ready.
