### ISSUE TITLE
Export Extras option is not working.

### ISSUE THREAD

**Issue by ZanQdo** [KhronosGroup/glTF-Blender-Exporter#337]
The option for Export Extras used to export custom atributes. This is not working on 2.0 ATM

**Comment by donmccurdy** [comment]
Could you provide an example? You can attach `.zip` files to GitHub comments. And what do you mean by "on 2.0"?

**Comment by ZanQdo** [comment]
@donmccurdy Of course. Here is the Blender 2.8 file, made with latest 9abcf56fa88 build for windows. Also contains exportef GLTF using the included GLTF 2.0 exporter (YAY!)

[Cube.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2617940/Cube.zip)

Export goes fine with this printed to the console:

`INFO: Starting glTF 2.0 export
INFO: Extracting primitive
DEBUG: Adding primitive without splitting. Indices: 36 Vertices: 24
INFO: Primitives created: 1
INFO: Finished glTF 2.0 export`

The object was exported with the Export Extras option, however no property is exported. There should be a "Foo" property with a value "Bar"

Thanks

**Comment by ZanQdo** [comment]
Thanks I guess it's IO. You can close this
