### ISSUE TITLE
Bones "Inherit Rotation" property is ignored.

### ISSUE THREAD

**Issue by Eketol** [KhronosGroup/glTF-Blender-Exporter#340]
I'm working with a 3d model in Blender wich has some bones with 'Inherit Rotation' disabled.
Exporting to GLTF seems to ignore that property, all bones seems to be exported with 'Inherit Rotation' enabled.
Exporting to FBX works as expected.

Please see attached demo.
[bones_test.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2633444/bones_test.zip)

- Is there some option in the exporter that fix this?
- Is there a recommendation about the use of this property? Is it better to enable 'Inherit Rotation' in all bones and readjust them to have my animation exported correctly?

**Comment by donmccurdy** [comment]
GLTF (like Unity and most engines, I think...) does not allow inherited rotation to be disabled the way that Blender does. I suspect that the FBX exporter bakes animation frame by frame to accomplish this, and that if you were to move the joints manually in an engine, rotation would still be inherited. 

I'm surprised the "sample animations" option doesn't fix this when exporting to glTF. Not sure why that is, but we can consider this an enhancement, or at least try to figure out what the FBX exporter does.

**Comment by donmccurdy** [comment]
Closing for now, I think this is likely out of current scope.
