### ISSUE TITLE
doesn't export material properly (pbrMetallicRoughness node is empty) from Blender 2.8 properly

### ISSUE THREAD

**Issue by kenyee** [KhronosGroup/glTF-Blender-Exporter#341]
Hoping this is a known issue w/ this version, but in case it's not, it's a good test for the new version in the other repo.
When using a surface that has a metallic color, the exporter emits an empty node:

> "extensions" : {},
>    "materials" : [
>        {
>            "pbrMetallicRoughness" : {}
>        }
>    ],
>    "meshes" : [
>        {
>            "name" : "CUCurve.003",

**Comment by donmccurdy** [comment]
This project does not support Blender 2.8 — work on that has been moved to https://github.com/KhronosGroup/glTF-Blender-IO, which is included in the new Beta release. (or is that what you're reporting an issue about?). You should use the Principled BSDF node there.

**Comment by kenyee** [comment]
Oops...installed this one by mistake :-(
It wasn't in the 2.8 Beta so I grabbed this one and installed it.  I'll grab the other one..thanks.

**Comment by kenyee** [comment]
<img width="897" alt="screen shot 2018-11-30 at 9 09 03 pm" src="https://user-images.githubusercontent.com/586670/49323141-12820880-f4e5-11e8-8843-f0817ad13758.png">

Hmm...git cloned the glTF-Blender-IO site and copied the add-ons over to the Blender 2.8 Beta admins dir and it doesn't seem to work at all.
I'll try grabbing another copy of the Blender Beta...odd that it didn't include GLTF support out of the box when the release notes say it did...

**Comment by kenyee** [comment]
yep...and when I look at the About dialog, it says 2.8 Beta.  Didn't have time to do it tonight but will this weekend or on Monday.  Thanks and sorry about the invalid bug report :-)
