### ISSUE TITLE
Feature request: Export scene.extras

### ISSUE THREAD

**Issue by EJTH** [KhronosGroup/glTF-Blender-Exporter#343]
It seems like extras for scenes are not exported with the gltf blender exporter. This would be very handy for me to set properties for a game im working on, and it seems like it is covered by the glTF specifications.

Using blender 2.78

**Comment by emackey** [comment]
@EJTH Thanks for your contribution in https://github.com/KhronosGroup/glTF-Blender-IO/pull/138!
