### ISSUE TITLE
Exporting ignores Cycle Mapping node in Blender

### ISSUE THREAD

**Issue by mokargas** [KhronosGroup/glTF-Blender-Exporter#35]
Currently I have an issue where exporting using the GLTF Metal Roughness PBR together with Mapping nodes: - the Mapping node scaling and rotation will be ignored:

Blender:
![image](https://user-images.githubusercontent.com/236984/27984530-d666cd46-641b-11e7-9532-03b3de73c3e2.png)

Three.JS/A-Frame:
![image](https://user-images.githubusercontent.com/236984/27984538-fa6de508-641b-11e7-9c50-4c0119057801.png)

The reason why this is a problem: my project doesn't use textures which are all the same size and rotation which seems to be an underlying assumption in the export.

Not sure if this is by design, if so, are there any workflow workarounds?

**Comment by UX3D-nopper** [comment]
You are right, this is not working by design. At the moment, it is not possible to pass a texture scale for glTF 2.0.
Let me have a look at your scene - maybe it can be solved differently.

**Comment by mokargas** [comment]
@UX3D-nopper Sure thing, do you want me to send it to you?

**Comment by UX3D-nopper** [comment]
No need to send, here is the solution:

- glTF 2.0 allows several texture coordinates and also the Blender exporter does export them:

![grafik](https://user-images.githubusercontent.com/27856744/27984675-2313caf8-63dc-11e7-893f-5ebc06336eea.png)

For the metal roughness texture, I have plugged a UV map as input. This is "allowed":
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md

So, if your model has several texture coordinates, you can choose, which one has to be used.
But you need to take care, as at the moment, only two texture coordinate sets have to be supported by a glTF 2.0 viewer.


If this is a hobby project, your approach is okay. But if you want to be more productive, I strongly recommend a professional tool like Substance Painter to apply materials directly on a 3D object.

**Comment by UX3D-nopper** [comment]
But please post your final rendering, as soon as you are finished!

**Comment by mokargas** [comment]
@UX3D-nopper Thanks for the direction. I'll give this a try and take a look at Substance Painter.

Currently this is a hobby. Previously I baked all textures with export to GLTF 1.0 and didn't bother with PBR, so right now I'm just trying to tease out a workflow I can re-use.

**Comment by feiss** [comment]
@UX3D-nopper Substance Painter is not the solution to everything, and there can be different reasons some studio or hobbyist don't want or cannot use it.

I hit with this issue today. I made a tileable texture with substance painter, and I wanted it repeated many times along the floor, and after some tries I realized there was no support for texture mapping transformations. The solution was to scale up the UVs of the floor. And I will use another UVmap for the lightmap.

**Comment by UX3D-nopper** [comment]
Agree, and maybe this could be a new extension, where a texture matrix can be stored somewhere.

But as far as I understand, this is a problem with the current features of glTF 2.0, right?

Even we would apply the Mapping into the UV map in Blender, you would still need a separate one for the lightmap.

**Comment by feiss** [comment]
Indeed! It is a spec thing, not an actual issue of the exporter.

**Comment by UX3D-nopper** [comment]
Okay, got it. Let's define a spec for texture coordinates. I put it on the list, what the guys want to discuss at SIGGRAPH.

**Comment by UX3D-nopper** [comment]
Here we go:
https://github.com/KhronosGroup/glTF/issues/1044

**Comment by donmccurdy** [comment]
Related: https://github.com/KhronosGroup/glTF/pull/1015 ... @feiss please also leave feedback there if you have suggestions on the proposal! 🙂
