### ISSUE TITLE
Exported GLTF is always black

### ISSUE THREAD

**Issue by dodox87** [KhronosGroup/glTF-Blender-Exporter#350]
Exported GLTF has all materials colors set to black (Color {r: 1, g: 1, b: 1).
Moreover the visualization is limited to a single face of the model.
In the screenshots you can see the differences.
<img width="510" alt="blender-ss" src="https://user-images.githubusercontent.com/12169627/51751039-19c42d80-20b4-11e9-810a-27c767f9a383.PNG">
<img width="479" alt="windows-ss" src="https://user-images.githubusercontent.com/12169627/51751054-2052a500-20b4-11e9-91a8-1e084765dbe0.PNG">
<img width="374" alt="viewer-ss" src="https://user-images.githubusercontent.com/12169627/51751063-26488600-20b4-11e9-8d9e-7d00c271b2b8.PNG">
<img width="551" alt="viewer2-ss" src="https://user-images.githubusercontent.com/12169627/51751068-2ba5d080-20b4-11e9-9625-846b8867e5e1.PNG">

**Comment by dodox87** [comment]
nobody can help me? :(

**Comment by emackey** [comment]
Hi @dodox87, this repo is mostly inactive now.  The exporter has been combined with an importer, and the new project lives here:

https://github.com/KhronosGroup/glTF-Blender-IO

Where are the colors in your model coming from?  The new exporter primarily gets colors from the "Base Color" input of the Principled BSDF node for Cycles & Eevee.  It can also use the old custom "glTF Metallic Roughness" node as a fallback, and it can work with vertex colors.
