### ISSUE TITLE
Camera parameters not being exported correctly

### ISSUE THREAD

**Issue by nicocornelis** [KhronosGroup/glTF-Blender-Exporter#37]
I recently encountered a problem with the camera parameters not being exported correctly. You can try it out by setting the fov in degrees in blender and compare it to the exported radian values from the glTF file. Whereas blender has the notion of sensor sizes and resolution, glTF does not, so perhaps it would be more useful to export the actual projection matrix used by blender for the camera. Furthermore, aspectRatio should be the ratio of view area instead of ratio of horizontal and vertical angle.

Here's some code which I believe fixes the issue:

For the perspective case:
`camview = blender_camera.view_frame(context.scene)`
`perspective['yfov'] = 2.0*math.atan2(0.5*(camview[0][1]-camview[2][1]),-0.5*(camview[0][2]+camview[2][2]))`
`perspective['aspectRatio'] = (camview[0][0]-camview[2][0])/(camview[0][1]-camview[2][1])`

and for the orthographic case:

`camview = blender_camera.view_frame(context.scene)`
`orthographic['xmag'] = 0.5*(camview[0][0]-camview[2][0])`
`orthographic['ymag'] = 0.5*(camview[0][1]-camview[2][1])`

Note that glTF does not support non-symmetric cameras, that's why averaged values are being used in the code above.

Kind regards,
Nico

**Comment by UX3D-nopper** [comment]
Why do you think, that the exported FOV is wrong?

The value, which can be set in in FOV field of the Camera, is angle / angle_x:
https://docs.blender.org/api/2.78c/bpy.types.Camera.html

As glTF is using FOV in the vertical direction, angle_y is exported, which is different from the entry in the user interface.

Regarding the aspectRatio, this should be correct as well, as both angles depend on the view area.

**Comment by UX3D-nopper** [comment]
But you are right, the aspectRatio is not behaving as it should.

Let me check.

**Comment by UX3D-nopper** [comment]
This should fix it:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/ef9d6501a8511978c92a2c18064323137d7f6858

Please reopen, if your scene/camera does not export as you expect.
In this case, please send me the file and a note, which values you would have expected.

**Comment by nicocornelis** [comment]
For example: if you set the horizontal and vertical pixel resolution to the same value in the scene tab, you get a square viewing frustum but the angle_x and angle_y value within blender are not equal. I believe this is because blender uses additional sensor size information to calculate the projection matrix. So if you would set the sensor with and height also to the same size (by setting 'sensor fit' to vertical in te camera tab and making width and height equal) you will see that angle_x and angle_y become the same. In other words, to get "useful" glTF camera values I believe the sensor size needs to be abstracted because glTF cannot represent it.

**Comment by UX3D-nopper** [comment]
Hmm, I expected, that if you change the sensor, all angle_* are updated.
Let me have a look at Blender source code, how they finally calculate it.

**Comment by nicocornelis** [comment]
That is correct, if you change the sensor, all angle_* are updated but if you change resolution in scene tab you will get non square pixels internally. With the blender_camera.view_frame function you get the four points located on the corners of the viewing frustum at the near clipping plane. If you use these values to determine yfov and aspect ratio you can reconstruct the projection matrix as defined by the glTF specification.

**Comment by UX3D-nopper** [comment]
Hmm, and the render preview and the final rendered output does differ, if non-square pixels are used.

**Comment by UX3D-nopper** [comment]
But I will use the preview images a reference.

**Comment by UX3D-nopper** [comment]
Okay, I understood your approach.

Made another fix for the FOV:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/2941d5186a3a87d7d37e734b747991d30cdfcd98

Will go through the math and check output on renderer.

**Comment by UX3D-nopper** [comment]
I googled a liitle bit, my colleague and I disussed this and I think this should be the proper fix:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/261b3b29b573aa24af57942e6a90e011e192d75c

![grafik](https://user-images.githubusercontent.com/27856744/28080404-30156d3c-666c-11e7-92d1-b5bc50473c0c.png)

![grafik](https://user-images.githubusercontent.com/27856744/28080348-f869af56-666b-11e7-96d7-bc18cc8bcd69.png)

The first image is rendered by Blender, the second one wih my Vulkan renderer:
The rendered pixels are at the same position.

**Comment by nicocornelis** [comment]
The above fix appears to work when sensor fit is set to 'auto' or 'horizontal', but not when set to 'vertical'. Can you verify?

**Comment by UX3D-nopper** [comment]
Verified, and I hope this finally fixes it :-) 
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/19be505bec0bdf0f672c8003b294d8b2b45d6633

**Comment by UX3D-nopper** [comment]
BTW, thanks a lot for finding this issue.

**Comment by nicocornelis** [comment]
You're very welcome. I tried a bunch of different values and the issue appears to be solved now.
Thanks for the fix :-)
