### ISSUE TITLE
Document requirements to export vertex colors

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/glTF-Blender-Exporter#4]
It took some digging to figure out that vertex colors are only exported if the color channel is named `COLOR_0`, `COLOR_1`, etc. This should be documented, but since there is currently no documentation, I don't know how to file the PR. Any comments on this?

**Comment by McNopper** [comment]
This evening, we do have the glTF working group call.
If they/we confirm the current development version, we will start making documentation plus screenshots.

You can expect, that there will be documentation for users and developers.
Goal is, that the Blender glTF 2.0 exporter is easy to use and each feature is well described.

The user documentation will include your requested information as well. The developer documentation will explain, how the exporter can be enhanced.

Even the exporter does already support a lot of features, please consider the whole project still in early stage.

Do say it in short: Documentation will come :-)

**Comment by stevenvergenz** [comment]
I know, I've been using it. Fantastic work! For the record, I was offering to help write some of the documentation once a structure was in place :)

**Comment by UX3D-nopper** [comment]
The result of the working group call was positive and we can now start with the documenation.

We will probably start with the explanation of the Blender node group, which is simulating the PBR metal roughness. Also, on how to export color channels or use a different texture coordinate set. Trying to explain all the features, which are not obvious.

**Comment by UX3D-nopper** [comment]
Goal is to have everything (all glTF 2.0 features plus selected extensions) implemented, tested and documented before SIGGRAPH.
