### ISSUE TITLE
Export Bezier as Hermite

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-Exporter#40]
Bezier can be converted to Hermite curve:
https://github.com/KhronosGroup/glTF-Sample-Models/issues/96#issuecomment-315213054

**Comment by UX3D-nopper** [comment]
Started with it:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/3180b08e44dc997d65d8081d5c0fb57ea8bc6a29

**Comment by emackey** [comment]
Was this completed?

**Comment by UX3D-nopper** [comment]
Yes, it works.

**Comment by UX3D-nopper** [comment]
Bezier animation - if possible - is exported a CUBICSPLINE.

**Comment by emackey** [comment]
Awesome 👍
