### ISSUE TITLE
Meshes aren't stored correctly (apparently) 

### ISSUE THREAD

**Issue by newincpp** [KhronosGroup/glTF-Blender-Exporter#42]
While working on my own graphics engine I wanted to implement gltf support. I didn't understood why my buffers were so wrong until I tried to use a viewer.
This is the original scene (.blend is downloadable)
https://sketchfab.com/models/c1b85e2e54394326bccd1a85d7f1fe75
This is how it looks when uploaded using Gltf2
https://skfb.ly/6suFA

The scene was done using blender 2.78 with the .glb mode (but I get the same result with .gltf embeded) using the attached settings.
Note: most of the scenes I tried to export have problems but this is the most "spectacular" one.
If you need more scenes I can upload you more.
Note: There is no animations, textures or even hierarchy. This is just meshes, math only materials and compositing.

Did I do something wrong or this exporter isn't production ready and I should use collada2gltf ?

PS: I also get python error if I try to export animations.

![settings](https://user-images.githubusercontent.com/3410903/28253798-8c4f24aa-6aa7-11e7-8eab-c61b4f7509cf.png)

**Comment by UX3D-nopper** [comment]
The above settings are the one you need to apply:

![grafik](https://user-images.githubusercontent.com/27856744/28255308-a04f7046-6ab5-11e7-9e16-e4eb76eb731d.png)

And here is the output:

![grafik](https://user-images.githubusercontent.com/27856744/28255293-7255bda8-6ab5-11e7-8f11-74fd5b12d979.png)

First, you need to apply the modifiers. The model uses Mirror etc. modifiers and they need to be applied to export correctly.
Second, you need to export all layers. The objects are assigned to different layers and so only a few were exported. By default, only the first layer is exported. This is the default setting, as other scenes do have on other layers helper objects, which should not be exported. In both cases, an exported scene can be wrong.

I am exporting using Integer indices, as this is the fastest export, as no splitting of models is needed. It should also work with Shorts.

Finally, the output is of course grey only, as standard Cycles materials are used. But this we discussed before.

Hope I could help you on this.

**Comment by UX3D-nopper** [comment]
Can you please send me the file, where the animation export error occurs?
Please make sure to use the latest exporter code.

At the moment, the exporter is in an alpha stage and we currently remove the last bugs. And of course documentation has to be added: Your issue just did came up, because you did not know the right settings.

**Comment by UX3D-nopper** [comment]
Uploaded it to Sketchfab as well:
https://skfb.ly/6suHz

**Comment by UX3D-nopper** [comment]
Added documentation for the export settings:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md
How this clarifies most issues.

**Comment by newincpp** [comment]
Thank you very much for this clarification. It seems I just misunderstood the "export for all layer" (I expected to be something like 1 layer=1 gltf Scene or 1 layer = 1 file or something like this) but **Everything is now clear**
Unfortunately I couldn't reproduce the python error during animation export I will make a new issue if it show up.
Thank you again.
