### ISSUE TITLE
KHR_technique_webgl extension support?

### ISSUE THREAD

**Issue by linuxaged** [KhronosGroup/glTF-Blender-Exporter#43]
what's the status of KHR_technique_webgl extension support?

I need to export the Techniques, programs, and shaders  with glTF 2.0 exporter.

**Comment by UX3D-nopper** [comment]
At the current point of time, this extnesion is not finalized:
https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_technique_webgl

As soon as finalized - like other extensions - it is been discussed to be integrated into the Blender exporter.

Please raise any issues in the above link, as it is not yet realted to the Blender exporter.
