### ISSUE TITLE
Export animaton for objects with follow path enabled

### ISSUE THREAD

**Issue by nicocornelis** [KhronosGroup/glTF-Blender-Exporter#44]
I believe that currently the animations for objects which are parented to a curve with path animation (follow path) enabled are not being exported.

Kind regards,
Nico

**Comment by UX3D-nopper** [comment]
Yes, this is true. If you need such an animation, please bake it before export.

Let's consider this as an enhancement, that this baking process is happening automatically.

**Comment by nicocornelis** [comment]
Is it possible to bake the animation for the path or does the action for all children need to be baked and exported?
In terms of node hierarchy it would make sense to export an animation for the path node only so that it transfers to children automatically. I guess a quick hack would be to parent all children to an empty and bake the action for the empty.

**Comment by UX3D-nopper** [comment]
You can bake exactly the action/animation you want. Select the path and run Object-Animation-Bake Action. The children with its animations normally should not be touched.
I suggest you just try it out, as this has nothing to do with the exporter: If the animation is behaving like you want plus the data is generated, it can also be exported to glTF , FBX, COLLADA or any format, whic contains animation data.
The only topic we need to think about, if this can easily be automated.
If yes - which I believe - it will become a feature and enhancement to the exporter.

**Comment by donmccurdy** [comment]
As another resource, I'm using the *Animation Nodes* Blender addon. The exporter cannot automatically bake those node graphs understandably, but I'm using this tutorial to convert the graph to keyframes: https://www.youtube.com/watch?v=IlrvI2Km-Tk
