### ISSUE TITLE
Export morph targets expects tangent attribute

### ISSUE THREAD

**Issue by moneimne** [KhronosGroup/glTF-Blender-Exporter#45]
I am trying to export a model with shape keys, but it seems to cause an error because the model doesn't have tangents. Does the exporter expect the model to have position, normal, and tangent attributes?

![morphexport](https://user-images.githubusercontent.com/14139842/28284049-bf4fb7ce-6afd-11e7-8d7b-71065eea215d.PNG)

**Comment by UX3D-nopper** [comment]
No, this is a bug but fixed here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/f6f95b3db9d7ac6d3a6abe45719ab83e6c3ff294

**Comment by UX3D-nopper** [comment]
Just tested, this is a morphing cube with just POSITION and NORMAL.

![grafik](https://user-images.githubusercontent.com/27856744/28285041-777d0f42-6b33-11e7-8265-029791abf930.png)

**Comment by UX3D-nopper** [comment]
Uploaded this blend file for testing:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scenes/01_morphed_cube_no_uv.blend

**Comment by moneimne** [comment]
Sorry to bring this issue back up, but are there any specific options that need to be checked/unchecked when exporting a model with morph targets? Right now, apart from the defaults, I have "Export selected only" checked, "Export for all layers" unchecked, and "Export tangents" unchecked. When I export like this, the exporter successfully creates a glTF with animated weights, but the primitives don't have targets.

**Comment by UX3D-nopper** [comment]
Hmm, can you give us the file that we can try it out? Just tested and morph target export works.

**Comment by UX3D-nopper** [comment]
Just exported with the default settings:
![grafik](https://user-images.githubusercontent.com/27856744/28574188-7c865208-714d-11e7-992f-598c8b66ad1f.png)

**Comment by moneimne** [comment]
Here is the blender file and the resulting glTF I got. It's also possible there is something wrong with my blender project.
[morphTargets.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1173276/morphTargets.zip)

**Comment by UX3D-nopper** [comment]
And this one with the given settings you mentioned:
![grafik](https://user-images.githubusercontent.com/27856744/28574284-c53f37bc-714d-11e7-803c-6ae2e91f4401.png)

**Comment by UX3D-nopper** [comment]
Works - just exported:
[morphedSuzanne.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1173286/morphedSuzanne.zip)

**Comment by UX3D-nopper** [comment]
Applied a metallic material and it runs in another viewer:
![grafik](https://user-images.githubusercontent.com/27856744/28574516-8335d942-714e-11e7-850b-11bfbccbd0e8.png)

**Comment by moneimne** [comment]
Were you able to export it like this with default settings?

**Comment by UX3D-nopper** [comment]
Yes- maybe you need to get the latest version of the exporter?

The ZIP is with orinal settings with your file.

The screenshot I quickly added a material.

**Comment by moneimne** [comment]
That might be it, so I'll make sure to grab the latest version.

Thanks for all the help!
