### ISSUE TITLE
KHR_materials_common extension will be supported ?

### ISSUE THREAD

**Issue by leonsal** [KhronosGroup/glTF-Blender-Exporter#47]
Will the [KHR_materials_common](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common) extension be supported when using Blender Render ?

**Comment by donmccurdy** [comment]
Hi @leonsal — the `KHR_cmnBlinnPhong` extension (which is supported experimentally by the Blender Exporter) is replacing KHR_materials_common. It experimental still, and most engines will not render KHR_cmnBlinnPhong yet.

**Comment by leonsal** [comment]
Is there a link to the KHR_cmnBlinnPhong specification document ?

**Comment by UX3D-nopper** [comment]
It is not final yet:
https://github.com/UX3D-nopper/glTF/tree/master_lights_blinnphong/extensions/Khronos/KHR_materials_cmnBlinnPhong
Also, when you are using the glTF 2.0 Blender exporter, during export, enable the experimental material. If your scene depends on the Blender Render, you will see the result in the glTF 2.0 file.
