### ISSUE TITLE
Incorrect normals export

### ISSUE THREAD

**Issue by proteamer** [KhronosGroup/glTF-Blender-Exporter#49]
Hi,

I faced with incorrect normals export when mesh contains `custom split normals data`:

Blender output:
![screen shot 2017-07-19 at 18 52 37](https://user-images.githubusercontent.com/1376014/28376784-ac6c2234-6cb3-11e7-967b-c2f35ac345e3.png)

[glTF Viewer](https://gltf-viewer.donmccurdy.com/) output:
<img width="539" alt="screen shot 2017-07-19 at 18 53 21" src="https://user-images.githubusercontent.com/1376014/28376785-ac74eb94-6cb3-11e7-98f6-2665227ec702.png">

The current export solution is based on the `Edge Split Modifier` which splits edges according to [mesh.auto_smooth_angle](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scripts/addons/io_scene_gltf2/gltf2_filter.py#L100). But blender doesn't use smooth angle when `custom split normals data` are available see blender tooltip for smooth angle input:
 
> Maximum angle between face normals that will be considered as smooth (unused if custom split normals data are available)

So model in blender has a differences of glTF model.

I'm not sure how `Edge Split Modifier` actually works if I disable `Edge Angle` option but this solution works for me:

```
--- a/scripts/addons/io_scene_gltf2/gltf2_filter.py
+++ b/scripts/addons/io_scene_gltf2/gltf2_filter.py
@@ -98,6 +98,7 @@ def filter_apply(export_settings):
                         blender_modifier = current_blender_object.modifiers.new('Temporary_Auto_Smooth', 'EDGE_SPLIT')

                         blender_modifier.split_angle = current_blender_mesh.auto_smooth_angle
+                        blender_modifier.use_edge_angle = current_blender_mesh.has_custom_normals == False

                     current_blender_mesh = current_blender_object.to_mesh(bpy.context.scene, True, 'PREVIEW')
                     temporary_meshes.append(current_blender_mesh)
```

Models to reproduce the issue: [cylinders.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1159596/cylinders.zip)

**Comment by UX3D-nopper** [comment]
I went through the forums and I believe, that auto smooth and edge split modifier do behave the same, if the correct settings are applied. If :-)
Tested with my engine and looks good.

Thank you very much!

Integrated here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/abf5058d8af99b3e3da5467b8abb5d92f84b1ec3
