### ISSUE TITLE
Over sized output when using sub-materials?

### ISSUE THREAD

**Issue by mrdoob** [KhronosGroup/glTF-Blender-Exporter#52]
While converting https://github.com/dataarts/3-dreams-of-black models to glTF I noticed that the exporter seems to be producing over sized files when using sub-materials.

[alligator.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1166787/alligator.zip) gltf file is 2.8MB
[alligator_subm.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1166788/alligator_subm.zip) gltf file is 11.4MB

Just want to double-check that this is correct.

**Comment by UX3D-nopper** [comment]
Problem is, that too many vertices are exported and some are not reused.

**Comment by UX3D-nopper** [comment]
Fixed here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/f6fcd55522a7ace96758839302cfb27eac5476c4

The export process does take now longer, but the output binary is now much smaller.

**Comment by UX3D-nopper** [comment]
An this one should speed up things:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/12a980eb7a7a8990ad357115197fdcb08aaf13ec

**Comment by mrdoob** [comment]
Much better! 11.4MB export is now 3MB 🎉

**Comment by UX3D-nopper** [comment]
Thx, the export now takes some more time but I think its worth it.

**Comment by mrdoob** [comment]
Seems like the materials no longer export with the latest version of the exporter 😕

[alligator.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1602155/alligator.blend.zip)

<img width="629" alt="screen shot 2018-01-03 at 5 05 09 pm" src="https://user-images.githubusercontent.com/97088/34546381-4dfbf548-f0a8-11e7-8c47-5da980496107.png">

[alligator_old.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1602159/alligator_old.gltf.zip)

<img width="698" alt="screen shot 2018-01-03 at 5 04 17 pm" src="https://user-images.githubusercontent.com/97088/34546361-3404912c-f0a8-11e7-8679-e963dfa84a9f.png">

[alligator_new.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1602160/alligator_new.gltf.zip)

<img width="677" alt="screen shot 2018-01-03 at 5 04 28 pm" src="https://user-images.githubusercontent.com/97088/34546367-3a8da060-f0a8-11e7-8221-6f49c7fe78a3.png">

**Comment by donmccurdy** [comment]
Thanks! Confirmed, and opened a new issue: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/148
