### ISSUE TITLE
Textures exported into a GLB are in the wrong color space

### ISSUE THREAD

**Issue by willswannackpluto** [KhronosGroup/glTF-Blender-Exporter#54]
When I exported an asset into the GLB format, it appeared significantly darker and redder. Exporting the same asset into the GLTF format did not have this issue. In both cases I had visualized the output in Unity using this importer: https://github.com/AltspaceVR/UnityGLTF

In Unity, I selected the texture that was being rendered to clarify that it was definitely the texture not the material that was the issue. The texture itself had the darker, orange tint. Here is an image of the expected correct output next to the mistaken output.

![intendedvsactual](https://user-images.githubusercontent.com/18352916/28800287-de077770-7600-11e7-9e7f-6a0593621c87.PNG)

Looking through the code, it appears the problem is in the create_png_data function in the gltf2_create function. The pixel values are read directly from the image into the png data blob. I believe the problem with this is Blender internally stores image pixels in a different color space than PNG. I think PNG is sRGB and Blender is Linear. So I believe the pixels are in the wrong color space as they are added under the PNG header, and then they get misinterpreted by the Unity loader. Blender doc on color management for reference https://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.64/Color_Management

I tried a simple conversion from gamma to linear by changing line 289 to include a pow function to 0.45 as below
`buf = bytearray([int(pow(channel,  0.45) * 255.0) for channel in blender_image.pixels])  `
And that seemed to make the output GLB work in the correct format.

**Comment by UX3D-nopper** [comment]
Have you checked, if the importer is correctly loading the images?
Below are three exports: GLB, glTF with and without embdded images:

![grafik](https://user-images.githubusercontent.com/27856744/28809907-ae0bd0e4-7686-11e7-8efb-96b0af574eed.png)
![grafik](https://user-images.githubusercontent.com/27856744/28809917-c5691468-7686-11e7-92d2-7c227538e353.png)
![grafik](https://user-images.githubusercontent.com/27856744/28809929-dd747a02-7686-11e7-83c7-4ce9dc44bf44.png)

**Comment by UX3D-nopper** [comment]
Can you please test the scene with your importer:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/27bb80d3acfdaa7885ad68be72ff2fac91580b82

**Comment by UX3D-nopper** [comment]
I think the importer is not correctly converting/loading the images, when they are embedded.
I close the ticket for now.

**Comment by willswannackpluto** [comment]
@UX3D-nopper Thanks for the test scene! It's very helpful. Interestingly, it works fine using the Unity importer so I'm going to keep digging and will post back if I find it's not an importer issue.

**Comment by UX3D-nopper** [comment]
Yes, please get back to us, if you find out an issue.
The point is, that the PNG encoding is taken - as mentioned in the code  - from the original Blender code:
`blender-thumbnailer.py`

**Comment by stevenvergenz** [comment]
@willswannackpluto This probably is an issue with the importer (importer author here). Unity does not allow you to specify the color space for a given texture at runtime, so all loaded textures are in gamma space (I think). You can verify this by extracting the texture from your GLB file using hex editor tools, then comparing that to Unity's preview window. I suspect they'll be different.

**Comment by Tshadow05** [comment]
I was having the same issue and I think you are right @stevenvergenz. I was able to fix it by changing the creation of the Texture2D (in GLTFSceneImporter) from
`texture = new Texture2D(0, 0);`
To
`texture = new Texture2D(2,2, TextureFormat.ARGB32, true, true);`
And now the objects are coming in with the correct color. Though its possible not that other objects may get imported with the wrong color if they are in gamma space.
