### ISSUE TITLE
cant enable add on in blender 2.78

### ISSUE THREAD

**Issue by PerspectivesLab** [KhronosGroup/glTF-Blender-Exporter#56]
the addon is greyed and cant be enabled

**Comment by UX3D-nopper** [comment]
Can you please send a screenshot?

**Comment by UX3D-nopper** [comment]
If it looks like this ...
![grafik](https://user-images.githubusercontent.com/27856744/28880126-5a86d936-77a4-11e7-97d1-8364d7ffc682.png)
... just click/tick the box ...
![grafik](https://user-images.githubusercontent.com/27856744/28880137-61c76a80-77a4-11e7-8201-3d32d31fa118.png)

**Comment by UX3D-nopper** [comment]
Hmm, seems to be fixed from your side. Closing for now.
