### ISSUE TITLE
Principled Node?

### ISSUE THREAD

**Issue by oparisy** [KhronosGroup/glTF-Blender-Exporter#57]
Hi,

the user documentation describes the [nodes group](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md#pbr-materials) you provide to model glTF 2.0 PBR materials and ensure proper export.

It also makes mention of a future compatibility with the 2.8 Eevee node, when available.

In this regard, what is the status of the existing [Blender 2.79 Principled Node](https://docs.blender.org/manual/en/dev/render/cycles/nodes/types/shaders/principled.html)? It seems to provide a large set of PBR features, and, similarly to the nodes group you provide, to strive for compatibility with texture conventions of Substance Painter or game engines.

So would it be conceivable to use the Principled node to design materials exportable to glTF 2.0? (This may understandably involve forbidding the use of some of the options it provides, such as SSS.)

I reckon PBR support in Blender is evolving from [ad-hoc node groups](https://www.blendermarket.com/products/pbr-uber-shader) to more integrated, standardized solutions such as the Principled Node and the future Eevee one.

Today glTF2.0 export seems somewhere in the middle, with convention-based materials such as your or [Sketchfab's one](https://help.sketchfab.com/hc/en-us/articles/209143886-Blender-Materials#blender-cycles).

Do you feel those approaches will converge, in the 2.8 branch at least?

Regards,
Olivier.

**Comment by UX3D-nopper** [comment]
After SIGGRAPH and @pjcozzi already made the connections, we plan to do a closer cooperation and integration of the glTF exporter with Blender.

From my point of view, the Eevee PBR material and the glTF 2.x PBR material should exactly match. Maybe we have to add something, maybe Blender has to add something but they have to match:
For a Blender user, in the future, an export to glTF 2.x has to be a no-brainer:
If I export using an Eevee node to glTF 2.x, it has to work. No linking to any external node group and/or taking care of any specific parameter settings.

The road to get there is a little bit tricky. The current node group works but a Blender user has quite something to do, that it finally works. It is good for now but this has to be changed.
For Blender 2.79, we keep the current node group, just for backward compatibility and not to break any work someone already did.

As soon as Blender 2.79 is final, we will add export support for the Blender Principled Node. I want to discuss this first with the glTF working group, but I think it is best, that we export every possible parameter/texture from the Principled Node, which exactly matches with the glTF 2.0 parameter. Any other parameter will be dropped and not exported. Advantage of this is, that any Principled Node based material can just be exported to glTF 2.0. This is much better compared to the current solution. If someone still wants to tweak any possible glTF 2.0 PBR material parameter, he/she can still use the current node group.

Hope this answers your question.
Norbert

**Comment by oparisy** [comment]
Those are great news, thanks for your detailed answer!

It confused me with respect to the Principled Node vs Eevee Node, though. In my mind they were two different beasts, the Principled Node existing already and being more of a Cycles beast, while the Eevee Node is still being designed and, as I understand it, is driven by the "realistic but responsive" viewport constraint.

Your answer left me with the impression that the Eevee and Principled node would end up being the same thing. Which would be great, mind you, considering your "just export to glTF 2.0, no tweaking needed" approach!

Regards,
Olivier.

**Comment by UX3D-nopper** [comment]
I do not know if this is the latest version of the Eevee node, but currently it is - regarding the material parameters - almost a subset of glTF 2.0:
![grafik](https://user-images.githubusercontent.com/27856744/28944815-40274f20-78a4-11e7-923a-866cd5046ab9.png)
World position offset is displacement, where we currently work on as an extension. Maybe we should call it World position offset as well.
The Specular - as far as I know - has the same meaning as described in the UE4 material:
https://docs.unrealengine.com/latest/INT/Engine/Rendering/Materials/MaterialInputs/index.html

You are right, Eevee and the Principled Node are two different things, as basically Eevee is for me real-time and the Principal Node Cycles based and more or less similar to the current glTF 2.0 node group.

We should definitelly target for Eevee and glTF 2.x similarity, as they are both for real-time. The Principled Node is for me just a better compromise as the current glTF node group we created.

**Comment by oparisy** [comment]
Thanks for your clarifications! Targeting Eevee->glTF2 export in the long run definitely makes sense due to their common goal. We'll have a very nice, integrated game/realtime 3D assets design environment then (same materials behavior in the viewport and the final glTF2 model when properly displayed).

It's great that in the meantime you plan on considering the Principled Node as an exportable glTF2 material specification, since we do not know when Blender 2.8/Eevee will be generally available.

Thanks for your time, regards!
Olivier.
