### ISSUE TITLE
Double Sided

### ISSUE THREAD

**Issue by mrdoob** [KhronosGroup/glTF-Blender-Exporter#58]
I think double sided is currently not being exported.

<img width="276" alt="screen shot 2017-08-03 at 3 00 27 pm" src="https://user-images.githubusercontent.com/97088/28945852-111a1cf4-785d-11e7-8e9b-6cb1a4117b1c.png">

Files:
[doublesided.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1198711/doublesided.zip)

**Comment by UX3D-nopper** [comment]
Correct, but it is not a bug.
It has been decided - in glTF 2.0 - that double sided is a material and not a mesh attribute:
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/material.schema.json
If you need double sided, please use the the glTF 2.0 PBR node groups.

**Comment by emackey** [comment]
Yep.  Also, Blender's use of "Double Sided" here refers to what OpenGL 1.0 calls `TWO_SIDED_LIGHTING`, which is a bit of fixed-function math that is replaced by programmable shaders in WebGL.  It was decided in glTF 2.0 that the double-sided flag refers specifically to backface culling, not two-sided lighting, and that glTF materials (when not culled) always use two-sided lighting.

Blender has a backface culling flag, but it refers to individual viewports, not individual materials, so doesn't translate to glTF.
