### ISSUE TITLE
Exported animation is 1 frame short.

### ISSUE THREAD

**Issue by mrdoob** [KhronosGroup/glTF-Blender-Exporter#59]
While working on https://mrdoob.github.io/rome-gltf/ I realised animations were not looping correctly.

You can see the issue by loading `quadruped_wolf.gltf` in http://gltf-viewer.donmccurdy.com and setting the animation speed to `0.25`.

<img width="948" alt="screen shot 2017-08-04 at 12 35 30 pm" src="https://user-images.githubusercontent.com/97088/28984312-37b91b16-7912-11e7-9cc8-b8499a0ee629.png">

You'll see that the last morphtarget doesn't crossfade with the first morphtarget. By changing the animation end to from 14 to 15 (`quadruped_wolf_fix.gltf`), the resulting gltf loops properly in the viewer, but the loop glitch then appears in blender because now the last frame and first frame are the same.

This is how the curves look like:

<img width="513" alt="screen shot 2017-08-04 at 12 36 48 pm" src="https://user-images.githubusercontent.com/97088/28984342-5c6414fc-7912-11e7-81a4-569d8d2b4247.png">

After talking about this with a few people during Siggraph and considering all the possible levels (Blender, Exporter, Loader, Engine) my believe is that the issue is simply that the exporter should export one more frame.

My rational is that... Right now the exporter is not taking in consideration that blender frames have a length. It's treating **the beginning of the last frame** as the end of the animation. So in the case of `quadruped_wolf.gltf` the engine is not able to reproduce frame 14, because the exporter skipped it. 

I think the exporter should treat **the end of the last frame** as the end of the animation. Exporting one more frame should virtually be the same.

With this change exported animations should then look exactly as they look in Blender.

[quadruped_wolf.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1201453/quadruped_wolf.zip)

**Comment by mrdoob** [comment]
Having said all that, I just created a simple test of a spinning cube and my suggestion would break it.

[cube_rotating.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1201535/cube_rotating.zip)

So it may be an issue of how Blender treats Shape Keys... 🤔

**Comment by UX3D-nopper** [comment]
Currently also looking at it.

**Comment by mrdoob** [comment]
Just learnt to do [time remapping](https://www.blendernation.com/2015/04/25/rendering-your-animation-in-slow-motion/) in Blender and then it behaves like in the engine.

I have spent way too long on this and at this point I would be happy to just modify the animations so they have one more frame even if they are slightly glitchy when reproducing in Blender.

Feel free to close this if you don't see anything wrong 😣

**Comment by UX3D-nopper** [comment]
The last frame (15) has no influence in Blender: Delete it or give it some extreme value. The animation does not change.
Hmmm ...

**Comment by UX3D-nopper** [comment]
Probably we need to ask someone from Blender, what exactly is happening here.

I have attached a sample Blender file, which lets you start thinking: "I have done my animations always wrong" :-)

[magic_blender.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1201667/magic_blender.zip)

Open and play the animation and check the values!
