### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-Exporter#60]
As far as possible, revisit code and improve Python code in regards of perfromance.

In specific cases e.g. image/buffer Base64 encoding, check possibility to use nativ functions in Blender.

**Comment by donmccurdy** [comment]
Code has been substantially refactored in glTF-Blender-IO, and it appears there have been some performance improvements. I think we can consider this closed, and open new issues if problems are found.
