### ISSUE TITLE
Implement current and outstanding glTF 2.0 extensions

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-Exporter#62]
glTF 2.0 will have several new extensions, which could be possbile exported by Blender as well.

**Comment by donmccurdy** [comment]
Let's file individual issues for each extension, when it's stable enough to implement.

- KHR_lights https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/179
- KHR_texture_transform https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/178
