### ISSUE TITLE
Organize export UI for artists and developers

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-Exporter#65]
At the moment, the glTF 2.0 exporter is organized from a developers point of view.
As Blender is mostly used by artists, the export should be organized in some basic, understandable and extended, advanced export options.

**Comment by donmccurdy** [comment]
There is still be some value in this, e.g. some of the animation export options feel like workarounds for bugs and could be organized in a way that is clearer. But that can be detailed in another issue I suppose, and https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/13 describes some more specific UI improvements already.
