### ISSUE TITLE
Exporter should not consider the armature as the root bone.

### ISSUE THREAD

**Issue by Nehon** [KhronosGroup/glTF-Blender-Exporter#66]
Hello, I'm writing a glTF importer for jMonkeyEngine, and I'm currently testing the blender -> glTF -> jME workflow. I found an issue that IMO is a misconception in the blender exporter.

According to specs, the "skeleton" attribute of a skin structure refers to the root joint of a joint hierarchy.
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#skins

Using the blender exporter, this attribute always refer to the Armature node, instead of the root joint.
here is a simple example to illustrate the issue
[simple.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1225164/simple.zip)

The scene is a mesh with an armature of 3 bones. The armature has been setup by parenting the mesh to it with automatic wight. (ctrl + p / with automatic weights), which is a pretty common setup.

If you look at the generated gltf the skins section looks like this : 
```
    "skins" : [
        {
            "inverseBindMatrices" : 5, 
            "joints" : [
                2, 
                3, 
                4
            ], 
            "skeleton" : 1
        }
    ]
```
and the nodes section
```
"nodes" : [
        {
            "mesh" : 0, 
            "name" : "Cube", 
            "skin" : 0
        }, 
        {
            "children" : [
                0, 
                2
            ], 
            "name" : "Armature"
        }, 
        {
            "children" : [
                3
            ], 
            "name" : "Armature_Bone"
        }, 
        {
            "children" : [
                4
            ], 
            "name" : "Armature_Bone.001", 
            "translation" : [
                0.0, 
                1.0, 
                0.0
            ]
        }, 
        {
            "name" : "Armature_Bone.002", 
            "translation" : [
                0.0, 
                0.9987609386444092, 
                0.0
            ]
        }
    ], 
```
As you can see the skin's "skeleton" attribute point to node 1 which is the Armature node.
Loader may consider this as the root bone of the armature which raises different issues: 
- It prevents root motion to work properly. Some engines like Unity have a feature called root motion that transforms the skinned spatial according to the root bone transforms. Wrapping it in a non animated additional bone prevent it from working.
- In this example you can see that the mesh node is actually attached to the armature. This means that importers will treat this mesh as attached to a bone (the root bone), and that's usually handled differently than skinning (in jMonkeyEngine we can attach a geometry to a bone and the geom will mirror the transforms of this bone without being actually skinned, common use case is attaching a scene object to a character's hand). 
- Well... the Armature is not the root bone.

In this example, in my humble opinion, the skeleton attribute should point to node 2 or be totally omitted as the spec allows. It's easy for a loader to find the root bone(s) anyway has they have, by definition no parent. 
The "Armature" node should be considered as a regular node and not as a joint.

**Comment by UX3D-nopper** [comment]
The model you provided has no vertex groups, so it is not properly exported.
Automatically generating vertex weights is currently not supported. So, for now, this is an enhancement.

Can you please provide me an example, where there are vertex groups? If the same problem occurs, then I rate this as a bug.

**Comment by Nehon** [comment]
Ha I'm sorry, I messed up with the file I linked, the blend file does not reflect the exported gltf.
Here is a proper file.
[simple.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1225344/simple.zip)
skin skeleton attribute refers to the node 0 which is the armature.

**Comment by UX3D-nopper** [comment]
Okay, fixed it here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/71bc6e29e827d7a97dbbbffae02449ebbc05f267

I changed your original "simple" scene, that the mesh has no parent and the armature is located "somewhere" else:

![grafik](https://user-images.githubusercontent.com/27856744/29322327-72a3a704-81dd-11e7-959f-a75abc8b126a.png)

[simple_modified.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1225490/simple_modified.zip)

**Comment by Nehon** [comment]
That was lightning fast, thanks a lot. I will test and report.
