### ISSUE TITLE
Export material which linked to object

### ISSUE THREAD

**Issue by proteamer** [KhronosGroup/glTF-Blender-Exporter#67]
Hello,

Is it possible to export a single geometry with different materials?

Blender provides opportunity to link material with `data` or `object` (see picture below), so you can override mesh material by material of particular object ([example scene](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1228540/materials.blend.zip)). 

Unfortunately it looks like blender exporter ignore `object` materials and export only mesh materials so I believe that it will good feature to export `object` materials too.

![screen shot 2017-08-16 at 17 40 34](https://user-images.githubusercontent.com/1376014/29369037-15f788cc-82aa-11e7-838a-4617a815b1f6.png)

**Comment by UX3D-nopper** [comment]
Basically, it is possible to assign multiple materials to a mesh/vertex groups.

Also, you are right, at the moment only mesh materials are exported.

**Comment by UX3D-nopper** [comment]
We have looked at it more closely and basically, it could be solved. But it does result in dublicating meshes, which I try to avoid.
@pjcozzi We need to discuss this next meeting, if we should add an extension for solving this.

**Comment by pjcozzi** [comment]
Will do @UX3D-nopper!

**Comment by UX3D-nopper** [comment]
Implemented here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/2395c7f83bb21a8ad577b3698d83650dc0c55c18
