### ISSUE TITLE
Minor typos on UI

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-Exporter#68]
Some of the UI options have what appear to be typos:

* `Export withing playback range` -> Should say "within", not "withing"

* `Export for all layers` -> I believe this is supposed to say `Export all layers`.

**Comment by UX3D-nopper** [comment]
Fixed:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/3f8f77aad31a8b66749e03d900b6b22383022722
Thx a lot.
