### ISSUE TITLE
Armatures are not exported in rest pose

### ISSUE THREAD

**Issue by Nehon** [KhronosGroup/glTF-Blender-Exporter#69]
I hit an issue when exporting rigged and animated models.
Consider this model (simple model with a 3 bones armature and an animation on the armature)
[simple.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1235360/simple.zip)

When I export the model with the armature in Pose Position
![blender e__jme_gltf blender issue_simple_simple blend 18_08_2017 21_00_50](https://user-images.githubusercontent.com/3286588/29473563-8ad696ce-8458-11e7-9a09-d6cc7c0eeb0a.png)
I get this files.
[SimpleAnimPose.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1235393/SimpleAnimPose.zip)
It's structurally fine, but when I load the model I get this
![jmonkeyengine 3 2-feature_gltf-loader-6291 18_08_2017 20_55_07](https://user-images.githubusercontent.com/3286588/29473857-a852c42e-8459-11e7-99dd-fb77b071eb2c.png)
As you can see, the skeleton seems to have been imported in the position it is at the first frame of the anim. If I play the anim I get this.
![jmonkeyengine 3 2-feature_gltf-loader-6291 18_08_2017 20_55_25](https://user-images.githubusercontent.com/3286588/29473889-c3fc68b0-8459-11e7-974f-51ab4aab0fbd.png)

If I set the armature position to Rest position in blender before exporting
![blender e__jme_gltf blender issue_simple_simple blend 18_08_2017 21_01_01](https://user-images.githubusercontent.com/3286588/29473917-dd1337de-8459-11e7-9303-3b06938fdfe3.png)
I get these files
[SimpleAnimRest.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1235400/SimpleAnimRest.zip)
Structurally fine too and I get this
![jmonkeyengine 3 2-feature_gltf-loader-6291 18_08_2017 20_56_14](https://user-images.githubusercontent.com/3286588/29474093-7ef02fb2-845a-11e7-9f7d-5ab52bffeccd.png)
However, when I try to run the animation, nothing happens. I dug it up, and find out that all animation transforms in the bin file are identity transforms.

To me the exporter should export the Armture as it is in rest position, and also exports animations even if the armature has been set in rest position.

**Comment by UX3D-nopper** [comment]
Which engine are u using? Export plus animation works fine on my side.

**Comment by UX3D-nopper** [comment]
Also the screenshot u made is not in pose mode.

**Comment by Nehon** [comment]
I use jMonkeyEngine, but I'm implementing the loader so, it might be an issue on my side.
What do you use?
How do you manage to find the bind pose if the skeleton is not aligned with the mesh?
about : "Also the screenshot u made is not in pose mode." which one?

**Comment by UX3D-nopper** [comment]
The object interaction mode is set to object mode in the Blender screen shots

Also, the exporter does export a scene - independent which current settings are active. If you want to export excatly one frame, you can disable animation export and select current frame.

The simple.zip works fine on my side. This is a screenshot during animation.
![grafik](https://user-images.githubusercontent.com/27856744/29475614-cf82f968-8460-11e7-959e-71f8a5ac66e4.png)

I am using our UX3D Engine.

Can you please check, if your loader and/or skinning animation system has an issue? I close for now.

**Comment by Nehon** [comment]
Alright, this one is on me... I found the issue in my code.
Thanks for your time.
