### ISSUE TITLE
No Materials in Threejs Test

### ISSUE THREAD

**Issue by mese79** [KhronosGroup/glTF-Blender-Exporter#7]
Hi
I just export the `04_common_materials.blend` file into gltf but when i've tried to open it with threejs `webgl_loader_gltf2.html` example i could not see any material at all, it just a gray model! (In `webgl_loader_gltf2.html` i just edited the model url to load.)
So do you have any idea?
Thanks.

**Comment by donmccurdy** [comment]
Hi @mese79 - the common materials support in THREE.GLTF2Loader is not done, as that extension to the glTF spec is not final. Metal-rough and spec-gloss PBR materials should work fine, if you can use those. Otherwise I will update this bug when we finish.

**Comment by donmccurdy** [comment]
Also, are you able to share your model (either the `.blend` or the `.gltf`)? This might help us to get things working more quickly. :)

**Comment by UX3D-nopper** [comment]
The common materials are currently in an experimental state, as they are not finally specified for glTF 2.0.
This implies, that most engines can not load the new syntax.

**Comment by mese79** [comment]
@donmccurdy here is a simple test model: [gltf_test.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1065080/gltf_test.zip)
I'm using `glTF Metal Roughness` material node, but still no materials. also i've checked the exported gltf file but there is no materials section in it!

**Comment by McNopper** [comment]
I changed the naming from 'glTF Metal Roughness' to correct 'glTF Metallic Roughness'.
As the old node group is used in the attached file, the exporter does not detect it anymore.
Please download latest version and link to the new node group again, as it is not automatically happening.

Sorry for this but it can happen during early stage development.
