### ISSUE TITLE
Alpha mode missing from default blender materials

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#72]
I realize the glTF PBR nodes are recommended, but as an FYI just noticed that I am not getting transparency exported with the default Blender materials:

[cubeTransparent.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1237386/cubeTransparent.zip)

| blender | glTF |
|--------|-----|
| ![screen shot 2017-08-20 at 3 03 10 pm](https://user-images.githubusercontent.com/1848368/29498836-b8d75fa2-85b8-11e7-848a-458c3d9cb0c8.png) | ![screen shot 2017-08-20 at 3 03 04 pm](https://user-images.githubusercontent.com/1848368/29498838-bafc02f6-85b8-11e7-998a-720f6b35175c.png) |

![screen shot 2017-08-20 at 2 59 52 pm](https://user-images.githubusercontent.com/1848368/29498842-d7f07766-85b8-11e7-8eb0-8a5ae7f791aa.png)

**Comment by UX3D-nopper** [comment]
Added and implemented here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/8a7e08c09c287b12e55dbd52c140d0da70e3d347

**Comment by donmccurdy** [comment]
So quick, thanks! 😀

**Comment by UX3D-nopper** [comment]
:-) Now going to office. Will mark this one as release and start with the enhancement features. Will later write an email to the glTF working group.
