### ISSUE TITLE
Material custom props is ignored

### ISSUE THREAD

**Issue by proteamer** [KhronosGroup/glTF-Blender-Exporter#73]
Hi,

I was surprised that custom props of PBR materials doesn't export to material `extras`. What is the reason of this behaviour? Is it bug?

**Comment by UX3D-nopper** [comment]
Can you provide a test scene, please?

**Comment by proteamer** [comment]
![screen shot 2017-08-23 at 12 04 22](https://user-images.githubusercontent.com/1376014/29607883-43a9045c-87fb-11e7-96ee-9a2b5813782f.png)
[mat_custom_props.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1244793/mat_custom_props.blend.zip)

**Comment by proteamer** [comment]
I guess we need to add something like this:

``` python
                if export_settings['gltf_extras']:
                    extras = create_custom_property(blender_material)
                    
                    if extras is not None:
                        material['extras'] = extras
```
To line https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scripts/addons/io_scene_gltf2/gltf2_generate.py#L2163

**Comment by UX3D-nopper** [comment]
Yes, was just missing and "forgotten".
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/7087207a1f7aa74179373cec712713730592d496
