### ISSUE TITLE
Remember previous export settings

### ISSUE THREAD

**Issue by andreasrosdal** [KhronosGroup/glTF-Blender-Exporter#77]
It would be nice if the exporter would remember my previous export settings,
since it can be quite boring to click the same export checkboxes every time I have to export a model, when exporting lots of 3d models.

Update: This could possibly be a duplicate of issue #13.

**Comment by UX3D-nopper** [comment]
Correct, so I close this one.
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/13
