### ISSUE TITLE
Negative keyframe times in animation

### ISSUE THREAD

**Issue by bengfarrell** [KhronosGroup/glTF-Blender-Exporter#78]
Bear in mind, that I'm relatively new to this space, so I may be mistaken and things are working as expected.

That said, I made an animation via Mixamo and exported as FBX. I imported the FBX to Blender just to do the export. Playback seems to work OK (via Don McCurdy's A-Frame-Extras, but the first part of the animation seems truncated. I've been nerding out a bit and looking into the file format, and the data I log into the browser console indicates negative playback times in the track. And indeed, even the accessor indicates a negative min value, with the max value matching the reported duration of the animation when parsed by GLTF2Loader in Three.js.

        {
            "bufferView" : 134, 
            "componentType" : 5126, 
            "count" : 96, 
            "max" : [
                2.2
            ], 
            "min" : [
                -0.9666666666666667
            ], 
            "type" : "SCALAR"
        }, 

Again, my understanding of things could be mistaken, but given whats happening with the first part of the animation not being seen coupled with these unexpected (to me) negative values, I think this might be an export bug

**Comment by UX3D-nopper** [comment]
Can you please provide the file?

**Comment by bengfarrell** [comment]
Sure, I just made a repo to share easy. https://github.com/bengfarrell/mixamo-blender-gltf-example
Included is the gltf + bin file, but also the original FBX from Mixamo that was then imported to Blender.

**Comment by UX3D-nopper** [comment]
During my subway ride, one important thing came in my mind: With glTF 2.0, negative keyframes are not allowed.
I think the current exporter is not checking this and the frames are just exported.
I will have a look at it.

**Comment by UX3D-nopper** [comment]
Okay, there is an option, where keyframes are moved to 0.
So, what i will do is, that if a negative keyframe exists, this does happen automatically.

**Comment by UX3D-nopper** [comment]
Hmm, negative keyframes are not possible in blender, so this cant be the problem. I will check the file.

**Comment by bengfarrell** [comment]
Great, thanks for looking! Hopefully I'm just wrong and I didn't find a real issue on your end, but I am looking forward to some good adoption on glTF and I'd feel bad if I didn't report

**Comment by UX3D-nopper** [comment]
I tried it out in several engines. The bevahiour in Blender is the same as in the engines. Let me have a look at the original file.

**Comment by UX3D-nopper** [comment]
Hmm, i do not see any negatove keyframes.

**Comment by UX3D-nopper** [comment]
There is always the possibility of a bug, and to get things mature, investigations are required.

But what i will add is a clamp, that negative frames are not possible at all.

**Comment by UX3D-nopper** [comment]
Okay, added it here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/4fdcdc0359e099912be27a47f407c1021d25ccb9

**Comment by bengfarrell** [comment]
Thanks much, I totally understand that blender doesn't support negative keyframe times. It looks like I need to look elsewhere in my pipeline to figure this out and get the animation fully playing

**Comment by McNopper** [comment]
Negative keyframes are supported in Blender, if they are explicitly enabled.
But glTF 2.0 does not support negative keyframes.

**Comment by bengfarrell** [comment]
Gotcha - I definitely don't have them enabled. And in fact, my animation starts on frame 0 when loading the animation/model into Blender from importing the FBX as indicated in my timeline. Playback in Blender is even fine, in that it doesn't cut the first part off.
<img width="750" alt="screen shot 2017-08-07 at 10 37 31 pm" src="https://user-images.githubusercontent.com/1298188/29856780-ec9d2634-8d09-11e7-9c95-ed6dde2e4ad8.png">

It's just that when the file is exported via the Blender exporter, I'm getting negative times. I know that UX3D-nopper said he didn't see any negative keyframes, but using GLTF2Loader and viewing the time values, they are definitely there. It's entirely possible that GLTF2Loader is erroneous, but the associated sampler input values when using the index to look up the accessor have min values that are negative - and that is taken directly from the human readable JSON glTF file.

So, I'm confused. I totally understand that I'm new to this space, so I will defer to this repo's owner that this isn't a bug with the glTF-Blender-Exporter, but I'm at a loss as to what is wrong here.

**Comment by UX3D-nopper** [comment]
Just not to confuse u: McNopper is my private account :-)

With the current master branch, all negative keyframes are explcitly removed.
Also, you can drag and drop the the golfer.bin and golfer.gltf file into the glTF validator:
http://github.khronos.org/glTF-Validator/

```
[
    {
        "uri": "golfer.gltf",
        "mimeType": "model/gltf+json",
        "resources": [
            {
                "id": "#/buffers/0",
                "mimeType": "application/octet-stream"
            }
        ],
        "info": {
            "version": "2.0",
            "generator": "Khronos Blender glTF 2.0 exporter",
            "externalResources": {
                "buffers": {
                    "#/buffers/0": "golfer.bin"
                }
            },
            "hasAnimations": true,
            "hasMaterials": true,
            "hasMorphTargets": false,
            "hasSkins": true,
            "hasTextures": false,
            "hasDefaultScene": true,
            "primitivesCount": 26,
            "maxAttributesUsed": 4
        }
    }
]
```

The glTF 2.0 file is fine, as negative keyframes would have been reported. If you think, there are still negative keyframes, please raise first an issue with the validator, as we depend on the correct validation.

**Comment by bengfarrell** [comment]
Hehe, was wondering why there were so many noppers :)
Ok, I'll look into the validator, thank you!

**Comment by lexaknyazev** [comment]
> Also, you can drag and drop the the golfer.bin and golfer.gltf file into the glTF validator:

Small correction: for now, you need to drag-n-drop GLB file to validate binary data. Folder support is coming.

**Comment by bengfarrell** [comment]
Hopefully I'm not beating a dead horse, and actually helping, but I did export as glb to test in the validator (also checked into https://github.com/bengfarrell/mixamo-blender-gltf-example). The validator reports that there are negative times:

"errors": {
            "ACCESSOR_ANIMATION_INPUT_NEGATIVE": [
                {
                    "type": "ACCESSOR_ANIMATION_INPUT_NEGATIVE",
                    "path": "#/accessors/132",
                    "message": "Animation input accessor element at index `0` is negative: `-0.9666666388511658`."
                },

I haven't pulled the latest from the repo, but if you remove all negative keyframes in the export as you just indicated, then I would assume that I'd still be missing keyframes. Prior to the change, they just wouldn't play in Three.js, after this change, I would assume that the data is just lost from the file correct?

Neither solves the problem, in that I want to play the full animation I export. Again, I know you closed this, and don't want to press the issue if not welcome, but I did want to provide relevant info.
Thanks

**Comment by McNopper** [comment]
Hmm, I think it could happen, if your animation has a keyframe ar 0 but the animation starts at 1,
I will fix this,

**Comment by sbtron** [comment]
If input assets and blender support negative keyframes then is the thinking that the exporter shifts the negative keyframes to 0 and shift the others correspondingly to make a valid glTF file?

**Comment by UX3D-nopper** [comment]
There is an option im the exporter, that all frames are shifter to 0. If disabled they are kept like they are.

Also, this should finally fix it:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/2236977e9cc4821b6fcb7741d9016c60ee503ade

**Comment by UX3D-nopper** [comment]
If the final of the keyframe - with or without shifting is negative - it is now correctly eliminated.

**Comment by bengfarrell** [comment]
Fantastic, thank you! I just downloaded the zip of the repo and updated my files. The glb file now validates, and in Don McCurdy's viewer plays all the way through. I'm so glad this works now. As I understand it, Blender is pretty much the ONLY way to convert to glTF 2.0 right now, so that's why I pushed so hard on this. Again thanks, crossing my fingers this is the only issue I'll encounter!

**Comment by UX3D-nopper** [comment]
No problem, and it was good that you pushed this. I was just wrong, as I debugged at the wrong position.

Sooner or later another issue will probably pop up. Provide an example and we will fix it.
