### ISSUE TITLE
User issue with skinning and common materials

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#8]
Hi, I'm cross-filing this from an issue opened on three.js by @densetsughem.

Original issue: https://github.com/mrdoob/three.js/issues/11460#issuecomment-307012216

There are [two skinned models](http://densetsughem.com/GLTF2-Blend-fIle.rar), and with default settings (for either model) export gives this error:

![screen shot 2017-06-08 at 7 06 39 pm](https://user-images.githubusercontent.com/1848368/26958499-f5dbc9f0-4c7f-11e7-9432-b558d87f4662.png)
> (not sure how to copy/paste the text from Blender, sorry...)

If I un-check skinning before exporting, the export succeeds. In the resulting `.gltf`, a material is present (I selected the "Phong" common material under experimental) but the material is not referenced by any nodes.

I understand this is still a work-in-progress of course, but hopefully these examples are helpful. :)

**Comment by UX3D-nopper** [comment]
Ok, I submitted a fix - for both models. I have not fully tested the fix but the export finishes in both cases.

The Alena model raised another issue, as the animation export takes way to long. Need to profile it, why this happens.

Also, the Alena model uses a custom Cycles node node tree, which cannot be exported at this point of time. Either use Blender Render material (for Common Material) or use the glTF 2.0 Metal Roughness node group for a PBR material.

I will discuss a custom Cycles node tree and how it should be exported in the next glTF working group meeting.

**Comment by UX3D-nopper** [comment]
Any example which helps me debugging are welcome!

**Comment by UX3D-nopper** [comment]
Okay, I have added some optimizations. The Alena model can now be exported in acceptable time.
I will do some final tests and close the ticket, if the dog and Alena can be rendered and animated properly.

**Comment by donmccurdy** [comment]
Thanks @UX3D-nopper! For animation, the output looks correct to me. It does not work in three.js yet, but that's an issue on three.js's end (we don't allow spaces in node names for animation, so our loader will need to sanitize those if they're coming from the exporter).

As for custom cycles node trees, I'll defer to you as to whether those are a priority now or not; we can suggest that the author use common materials or PBR.

**Comment by McNopper** [comment]
![grafik](https://user-images.githubusercontent.com/3677213/26985545-30c60b9c-4d44-11e7-8d31-6758fef98850.png)

Okay, dog works from my side.

**Comment by donmccurdy** [comment]
Thanks! I'm struggling to export the dog model, but I think that's my inexperience with Blender... I assume you are removing the extra objects from the scene, and then editing the materials somewhere before export? I don't see textures or vertex colors in my export...

After [this PR](https://github.com/mrdoob/three.js/pull/11485), three.js should support lights and common materials in the format used by your exporter.

**Comment by McNopper** [comment]
![grafik](https://user-images.githubusercontent.com/3677213/27010724-9596bcf2-4eab-11e7-9fac-9a230e2d88c7.png)
Okay, got Alena to work as well.

**Comment by McNopper** [comment]
Until now, 'Vertex Colors' needed to be named COLOR_0 and so on. Now, the index is gathered from the 'Vertex Colors'. Tradefoff is, that in the PBR preview node group the COLOR_0 must explicitly set.

Regarding Alena, I needed to do a fix: In Blender, a whole Mesh node can be assigned to a bone. This is now exported correctly.
Furthermore, Alena is using IK. So I baked the animations. Finally, I was changing the material for Alena to a Blender Render one.

To compare, I have added my changes:
[Working_Dog_Alena.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1066432/Working_Dog_Alena.zip)

**Comment by donmccurdy** [comment]
Great — The materials for both are now loading in three.js (with my PR above). Animations are not playing yet, but that's an issue on the THREE.GLTF2Loader side I think.

**Comment by donmccurdy** [comment]
Since the remaining issues are not with the blender exporter, I am closing this issue.

**Comment by McNopper** [comment]
Just uploaded a new version: Added an option, that the IK constraints are applied and baked.
