### ISSUE TITLE
Export NLA's as animations

### ISSUE THREAD

**Issue by mwmwmw** [KhronosGroup/glTF-Blender-Exporter#81]
I'm not sure what I'm doing wrong. 

What I'd like to do is export NLA's as AnimationClips (https://threejs.org/docs/#api/animation/AnimationClip) so that I can mix them together later using ThreeJs animation mixer. 

Using this file with the Blender Three JSON exporter, I am able to export each NLA as a separate AnimationClip that I can mix at runtime. 

[HoleCube5.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1267664/HoleCube5.zip)

The GLTF loader for Three will load all the animations as AnimationClips, but the exporter seems to only export the currently selected animation

Is there a way to export NLA's as AnimationClips?

**Comment by UX3D-nopper** [comment]
NLAs are currently not exported. We tried it, as we thought it is a quick implementation.
Using simple examples, it did work but using more complex ones did show us, that the NLA feature is too buggy.

Also, this relates to issue:
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/39

**Comment by mwmwmw** [comment]
If I could ask for the buggy NLA's you guys came up with, maybe it could be submitted as an issue to Blender?

**Comment by UX3D-nopper** [comment]
Let's see if we figured out something new, as it is already discussed.
