### ISSUE TITLE
Export Selection Has Different Results

### ISSUE THREAD

**Issue by PhilCK** [KhronosGroup/glTF-Blender-Exporter#84]
Exporting a selection gives me different results in two regards.
Firstly the light data doesn't come down in the export, secondly I get duplicate nodes.

If I have an object tree.

```
Warehouse
   - Lights
   - SpawnPoint
   - WarehouseMesh
```

Export selection gives me...

```
Warehouse
WarehouseMesh
Warehouse
   - Lights
   - SpawnPoint
   - WarehouseMesh
```

Export selection with the `KHR_lights_cmn` will return no lights at all. Without selection I get the lights as expected.

I haven't tested anything with animation yet.

Observed on latest master.

**Comment by PhilCK** [comment]
Part of the json

```json
        {
            "children" : [
                3, 
                12, 
                19
            ], 
            "name" : "Warehouse"
        }, 
        {
            "mesh" : 8, 
            "name" : "Struts", 
            "translation" : [
                0.0, 
                5.0, 
                6.0
            ]
        }, 
        {
            "children" : [
                0, 
                2, 
                4, 
                11, 
                13, 
                14, 
                15, 
                16, 
                18
            ], 
            "name" : "WarehouseMesh"
        }, 
        {
            "name" : "WarehouseMesh"
        }, 
        {
            "name" : "Warehouse"
        }
```

**Comment by UX3D-nopper** [comment]
Can you please provide the file, as I just tested the feature and it works on my side.

**Comment by PhilCK** [comment]
[Archive.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1284739/Archive.zip)

**Comment by UX3D-nopper** [comment]
Hmm, seems the selection feature is somehow screwed up.

**Comment by MichaelHazani** [comment]
I've noticed that as well - "export selected" yields markedly different results than exporting everything (even when everything is selected).
I'll get around to filing something after I finish repro'ing and reporting a more pressing issue:)

**Comment by donmccurdy** [comment]
Tracking plans for updates here in https://github.com/KhronosGroup/glTF-Blender-IO/issues/193.
