### ISSUE TITLE
Blender does not complete the export of a high poly object

### ISSUE THREAD

**Issue by rhokstar** [KhronosGroup/glTF-Blender-Exporter#85]
Assuming using OS X, glTF Blender Exporter is installed and using Blender 2.78c | Release date 2017-02-24 | Hash e9f235

Steps to reproduce the bug:

1. Open Blender 
2. Delete default camera and lights
3. Import FBX attached file (see below)
4. Export glTF 2.0

Result: Blender doesn't complete exporting high poly objects to gltf.
Workaround: Use OBJtoGLTF

Polycount: 840k
FBX Origination: Maya LT 2017 OS X

[fbx-export-to-gltf-2.0-with-blender-test.fbx.zip](https://github.com/KhronosGroup/glTF/files/1285375/fbx-export-to-gltf-2.0-with-blender-test.fbx.zip)

**Comment by UX3D-nopper** [comment]
I think I found the "needle":
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/5ffd6efa0bc1378fe681253ea397c3250b94f26c

Exports in around 75 seconds on my machine.

![grafik](https://user-images.githubusercontent.com/27856744/30179177-cb1133b2-940b-11e7-9ba4-50327532ef6b.png)
