### ISSUE TITLE
glTF-Blender-Exporter isn't compatible with Blender 2.8

### ISSUE THREAD

**Issue by Anth0rx** [KhronosGroup/glTF-Blender-Exporter#87]
```
Traceback (most recent call last):
  File "/home/anthorx/.config/blender/2.80/scripts/addons/io_scene_gltf2/__init__.py", line 328, in execute
    return gltf2_export.save(self, context, export_settings)
  File "/home/anthorx/.config/blender/2.80/scripts/addons/io_scene_gltf2/gltf2_export.py", line 78, in save
    prepare(export_settings)
  File "/home/anthorx/.config/blender/2.80/scripts/addons/io_scene_gltf2/gltf2_export.py", line 42, in prepare
    filter_apply(export_settings)
  File "/home/anthorx/.config/blender/2.80/scripts/addons/io_scene_gltf2/gltf2_filter.py", line 109, in filter_apply
    current_blender_mesh = current_blender_object.to_mesh(bpy.context.scene, True, 'PREVIEW')
TypeError: Object.to_mesh(): error with argument 2, "scene_layer" -  Function.scene_layer expected a SceneLayer type, not bool

location: <unknown location>:-1
```
Again, in Blender 2.78 it works fine

**Comment by UX3D-nopper** [comment]
Hmm, I thought we tested this but it seems this we need some changes for 2.80.

**Comment by UX3D-nopper** [comment]
We just tested the glTF node group with Blender 2.80. But as there are major changes with the Blender 2.80 Python interface, the exporter does not yet work with 2.80.

**Comment by emackey** [comment]
Blender 2.80 is still a year away from release, I wouldn't recommend trying to get the API lined up until things get a lot more stable there.

But... **Breaking news...** Blender 2.79 has been released today as the newest stable download of Blender.  The new version includes the "Principled BSDF" shader for the Cycles engine.  This means that users downloading the default stable release of Blender as of today get a package that includes a PBR shader node for Cycles.  I realize this node doesn't have feature-parity with the Khronos custom node, but, I think it would help this exporter gain more traction if it could be made to work for as many fields as possible on this node.

**Comment by oparisy** [comment]
Indeed @emackey! This was discussed on #57.

**Comment by emackey** [comment]
Yeah somehow #57 got closed.  I would think that core support for 2.79 would be a short-term goal now, meaning, support export from the Principled BSDF node out-of-the-box, without referencing any Khronos-supplied *.blend files or nodes.  Just like the OBJ and COLLADA and other exporters, it should "just work" directly from user-constructed scenes, without importing any assets.  I think that would go a long way towards marketing this exporter as general-purpose, enabled by default for all users.

**Comment by Anth0rx** [comment]
@emackey Thanks for the info.

**Comment by Ybalrid** [comment]
Sorry to jump in, I know that isn't the exact subject of the issue. Will the blender exporter export EEVEE PBR material directly, or will it use it's own node as it does for 2.7x ?

**Comment by oparisy** [comment]
You may wish to have a look at #101, @Ybalrid. My understanding is that the glTF-specific nodes group approach will disappear in 2.8.

**Comment by SurlyBird** [comment]
Noticed FBX and OBJ import/export now work in the latest experimental builds. Any chance the glTF importer/exporter could get updated (at least to test)?

**Comment by emackey** [comment]
@SurlyBird It's on the roadmap, but I can't promise a date.  Active development has moved to the [glTF-Blender-IO](https://github.com/KhronosGroup/glTF-Blender-IO) repo, which will replace this repo when it's ready for production use.

**Comment by donmccurdy** [comment]
Resolved in
