### ISSUE TITLE
Weird UV distortions - possibly in conjuction with the Texture Atlas addon

### ISSUE THREAD

**Issue by MichaelHazani** [KhronosGroup/glTF-Blender-Exporter#88]
Hi!
For some strange reason certain UV maps don't survive the exportation to glTF intact. This may be related to texture atlasing - and I was able to repro this problem multiple times while using that (official) addon. I realize this may be a question of jurisdiction, but it still strikes me as a glTF problem because at the end of the day a perfectly valid UV map in Blender gets distorted in the exported glTF file.

In Blender:
![screen shot 2017-09-13 at 5 42 06 pm](https://user-images.githubusercontent.com/10997806/30407069-f59f6c86-98aa-11e7-8b5b-2b5fb4d1d785.png)

In Browser:
  
![screen shot 2017-09-13 at 5 35 56 pm](https://user-images.githubusercontent.com/10997806/30406992-696d0520-98aa-11e7-92fd-05d2a90dc12f.png)

You're welcome to try this yourself with [the .blend file](https://www.dropbox.com/s/b4lexyy57bx0x2n/gltf_bug_test_scene.blend?dl=0).

(The original UVs are not perfect - this was done quickly for demonstration purposes - but the distortions in the glTF file are very visibly worse.)

Details:
Blender 2.79 (RC2)
The most recent exporter from this repo
export settings - although I've tried quite a few variations at this point:
![screen shot 2017-09-13 at 5 48 39 pm](https://user-images.githubusercontent.com/10997806/30407231-dc448496-98ab-11e7-9a05-d24b7d791200.png)

Thanks!

**Comment by UX3D-nopper** [comment]
Same output as in Blender:

![grafik](https://user-images.githubusercontent.com/27856744/30412112-9e4f05c0-9915-11e7-8154-8777587eaca4.png)

![grafik](https://user-images.githubusercontent.com/27856744/30412127-aca3910e-9915-11e7-9715-a412744f7c50.png)

**Comment by MichaelHazani** [comment]
Sorry, didn't get a chance to respond to this before it was closed - would it make a difference if I didn't use the glTF node? I'm applying materials programmatically because I'm not using PBR here. Why would avoiding the glTF node mess up the UVs though?

**Comment by UX3D-nopper** [comment]
The exporter is mainly exporting and converting the data, which is available.
Most features which are procedural and/or prgrammatical need to be baked before.

I am using the glTF node to investigate, if the Blender output is the same as in a viewer.

**Comment by MichaelHazani** [comment]
Thank you. So just to confirm beyond doubt, the glTF node does not affect export at all? Just in-program presentation?

If that's the case, the only thing that comes to mind is to switch from RC2 (which I dl'd maybe four days ago) to the official build, although I still can't understand how it happened.

**Comment by UX3D-nopper** [comment]
In regards of the material, it does affect the export. In regards of the mesh and node tree, not.

**Comment by MichaelHazani** [comment]
Thank you again for clarifying!
Just one more question that may resolve the issue - after seeing [other threads](https://github.com/KhronosGroup/glTF/issues/1044) I realized that that could very well have been my problem - is the only current way to retain UV maps is to use a *UV map* node? I typically use a Texture Coordinate node's UV output - but sounds like it's incompatible with glTF even though it's basically performing the same function as the UV Map node!

**Comment by UX3D-nopper** [comment]
Yes, only possibility. See also:
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md

**Comment by MichaelHazani** [comment]
Fantastic, thank you for your help.
