### ISSUE TITLE
UVs seems wrong

### ISSUE THREAD

**Issue by jean-noelp** [KhronosGroup/glTF-Blender-Exporter#89]
Hello,

I'm trying to load **glTF a cube** file with Three.js, but the **UVs maps seems wrong**.
(the concerned texture is a [lightmap](https://ibb.co/c34TUQ))

The **wrong** result with glTF [HERE](https://ibb.co/hut59Q).
The **good** result with an .obj export [HERE](https://ibb.co/ngEqb5).

I tryed a different viewer than Three.js, and the result is the same. So it's look like an issue from this exporter only.

**Comment by UX3D-nopper** [comment]
Can you please provide the .obj file, otherwise we can not investigate this.

**Comment by jean-noelp** [comment]
Sure !

`# Blender v2.78 (sub 0) OBJ File: 'cubes.blend'
# www.blender.org
mtllib cubes.mtl
o Plane
v -1.361756 0.146278 -0.600864
v -1.361756 0.146278 1.399136
v -3.361756 0.146278 1.399136
v -3.361755 0.146278 -0.600864
v -1.361755 2.146278 -0.600863
v -1.361756 2.146278 1.399137
v -3.361756 2.146278 1.399136
v -3.361755 2.146278 -0.600864
v -10.693610 0.064778 9.197472
v 10.693610 0.064778 9.197472
v -10.693610 0.064778 -9.197472
v 10.693610 0.064778 -9.197472
v -10.693610 5.064778 9.197472
v -10.693610 5.064778 -9.197472
v 10.693610 5.064778 -9.197472
v -0.930726 1.220638 -3.211711
v -0.930726 1.220638 -1.211711
v -2.930726 1.220638 -1.211711
v -2.930725 1.220638 -3.211711
v -0.930725 3.220638 -3.211710
v -0.930726 3.220638 -1.211710
v -2.930726 3.220638 -1.211711
v -2.930725 3.220638 -3.211711
vt 0.8990 0.6677
vt 0.8010 0.6677
vt 0.8010 0.7490
vt 0.8990 0.7490
vt 0.9990 0.6677
vt 0.9010 0.6677
vt 0.9010 0.7490
vt 0.9990 0.7490
vt 0.8990 0.6657
vt 0.8990 0.3343
vt 0.8010 0.3343
vt 0.8010 0.6657
vt 0.4010 0.9157
vt 0.7990 0.9157
vt 0.7990 0.8343
vt 0.4010 0.8343
vt 0.8990 0.3323
vt 0.8990 0.0010
vt 0.8010 0.0010
vt 0.8010 0.3323
vt 0.4010 0.7490
vt 0.7990 0.7490
vt 0.7990 0.6677
vt 0.4010 0.6677
vt 0.7990 0.3343
vt 0.4010 0.3343
vt 0.4010 0.6657
vt 0.7990 0.6657
vt 0.3990 0.3343
vt 0.0010 0.3343
vt 0.0010 0.9990
vt 0.3990 0.9990
vt 0.7990 0.3323
vt 0.7990 0.0010
vt 0.0010 0.0010
vt 0.0010 0.3323
vt 0.8990 0.7510
vt 0.8010 0.7510
vt 0.8010 0.8323
vt 0.8990 0.8323
vt 0.9990 0.7510
vt 0.9010 0.7510
vt 0.9010 0.8323
vt 0.9990 0.8323
vt 0.9990 0.3323
vt 0.9990 0.0010
vt 0.9010 0.0010
vt 0.9010 0.3323
vt 0.4010 0.9990
vt 0.7990 0.9990
vt 0.7990 0.9177
vt 0.4010 0.9177
vt 0.9990 0.6657
vt 0.9990 0.3343
vt 0.9010 0.3343
vt 0.9010 0.6657
vt 0.4010 0.8323
vt 0.7990 0.8323
vt 0.7990 0.7510
vt 0.4010 0.7510
vn 0.0000 -1.0000 -0.0000
vn 0.0000 1.0000 0.0000
vn 1.0000 -0.0000 0.0000
vn -0.0000 -0.0000 1.0000
vn -1.0000 0.0000 -0.0000
vn 0.0000 0.0000 -1.0000
usemtl Material
s off
f 1/1/1 2/2/1 3/3/1 4/4/1
f 5/5/2 8/6/2 7/7/2 6/8/2
f 1/9/3 5/10/3 6/11/3 2/12/3
f 2/13/4 6/14/4 7/15/4 3/16/4
f 3/17/5 7/18/5 8/19/5 4/20/5
f 5/21/6 1/22/6 4/23/6 8/24/6
f 9/25/2 10/26/2 12/27/2 11/28/2
f 11/29/4 12/30/4 15/31/4 14/32/4
f 9/33/3 11/34/3 14/35/3 13/36/3
f 16/37/1 17/38/1 18/39/1 19/40/1
f 20/41/2 23/42/2 22/43/2 21/44/2
f 16/45/3 20/46/3 21/47/3 17/48/3
f 17/49/4 21/50/4 22/51/4 18/52/4
f 18/53/5 22/54/5 23/55/5 19/56/5
f 20/57/6 16/58/6 19/59/6 23/60/6
`

and the attached mtl :
`# Blender MTL File: 'cubes.blend'
# Material Count: 1

newmtl Material
Ns 96.078431
Ka 1.000000 1.000000 1.000000
Kd 0.640000 0.640000 0.640000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 1
map_Kd CubesLightmap.png`

**Comment by UX3D-nopper** [comment]
UV export works as expected. Please read the exporter documentation and check, what u did wrong during export:

![grafik](https://user-images.githubusercontent.com/27856744/30476409-33faedce-9a0a-11e7-99c9-28a1f77b4cba.png)
