### ISSUE TITLE
Spline interpolation parameters seem wrong.

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glTF-Blender-Exporter#90]
I've been trying to export some animations from the exporter with cubic spline transforms, but the tangents m0 and m1 seem to be wrong.

For example, in 01_cs_translate.blend, I tried to add a change of 8 units of change in X / second, yet the exported value is something like m0 = 0.4, which leads to a very jumpy and weird motion.

[Test image](https://imgur.com/a/Ac8ke)

The test case does not have any tangent at their control points, and in that case it does work, but m0/m1 tangent parameters do not seem to be tested currently.

**Comment by UX3D-nopper** [comment]
Yes, seems there is something wrong.

**Comment by UX3D-nopper** [comment]
Can you try out this one:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/0eb365d38e1049f1c0117f5b236cbbfb519414f9
Please reopen, if not fixed.

**Comment by Themaister** [comment]
Struggling to test this due to https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/91.

But I wonder if the formula needs to take the delta time into account. Looking at the glTF specification, you have to multiply m0 and m1 by the delta time of the control points, so the exporter should probably do the inverse, to essentially get tangents which are derivatives of time and not control point interpolation phase?

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#cubic-spline

**Comment by UX3D-nopper** [comment]
Fixed #91.
Please try out.

**Comment by UX3D-nopper** [comment]
But the given scene file will be sampled/converted.

**Comment by UX3D-nopper** [comment]
Made another fix and the tests I have done do look good:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/42c46350f06e7401b941474c81bae60837a86ade
