### ISSUE TITLE
Error generated when exporting animations

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glTF-Blender-Exporter#91]
[untitled.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1308668/untitled.zip)
I tend to get an error when trying to export animations: https://imgur.com/a/MlRD5
Attached the blend file.
I baked a path animation from a path, and that's about it from a stock blend file.

**Comment by UX3D-nopper** [comment]
Fixed here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/75ded9bb50743d6d51989d37e897d2a6f76e68dc
