### ISSUE TITLE
Export Texture to DDS to support Windows 10 Mixed Reality Portal

### ISSUE THREAD

**Issue by hridpath** [KhronosGroup/glTF-Blender-Exporter#92]
Microsoft has indicated that the textures that are to be used in the Windows 10 Creators Update Mixed Reality Portal need to be in DDS format.

**Comment by donmccurdy** [comment]
I think I'd recommend using [glTF-Toolkit](https://github.com/Microsoft/glTF-Toolkit) to prepare assets for MR Portal. When there is a texture compression format in broader/multi-vendor use we can add support for it here.
