### ISSUE TITLE
Provide MSFT extensions to support Windoww 10 Mixed Reality Portal

### ISSUE THREAD

**Issue by hridpath** [KhronosGroup/glTF-Blender-Exporter#93]
In order to use materials in the Windows 10 Creators Update Mixed Reality Portal, textures and materials need to be defined with specified extentions:
https://github.com/sbtron/glTF/tree/MSFT_lod/extensions/Vendor/MSFT_texture_dds
https://github.com/sbtron/glTF/tree/MSFT_lod/extensions/Vendor/MSFT_packing_occlusionRoughnessMetallic
https://github.com/sbtron/glTF/tree/MSFT_lod/extensions/Vendor/MSFT_lod

**Comment by oparisy** [comment]
Would this mean that textures and materials will be exported multiple times, using different extensions in the same file? Or would checkboxes/options in the exporter UI be used?

**Comment by donmccurdy** [comment]
Also (not sure where to ask this) what is the reason for two variants of occlusionRoughnessMetallicTexture and roughnessMetallicOcclusion texture? It isn't obvious to me how either improves performance, compared to the default glTF PBR material, which is already packed in occlusion=R roughness=G metallic=B order (or can be, if the exporter chooses).

**Comment by McNopper** [comment]
For a later glTF version, I would prefer that it is possible to define which texture and channel should be used. One could better pack assets in this case.
The DDS extension looks fine to me.
Regarding the lod, I need to think about.

But in general, any extension, if a KHR_* or  MSFT_*, has to be enabled and is idsabled by default.

**Comment by hridpath** [comment]
@McNopper  I would see this as an checkbox option in the exporter screen.
@oparisy If the extensions are optional then the location of the texture images would be internal to the binary or external in relative path.

**Comment by hridpath** [comment]
@McNopper The textures and channels are defined in the glTF shader node, are they not?

**Comment by McNopper** [comment]
Currently, it is defined, that e.g. occlusion is in the R channel, metallic in the B and roughness in the G channel. It is the same for other data e.g. alpha value is A of baseColor.

Most materials are not required to utilize all textures. For instance, only the base color (without alpha) and metallic channel are required. Today, two minimal RGB textures are required. But one could define, that the metallic information is stored in the alpha channel of base Color, resulting in one RGBA texture.

This approach would allow to pack textures depending on the required data.

**Comment by hridpath** [comment]
@McNopper This is part of the current specs for use of materials for Windows Mixed Reality models.
**glTF Implementation notes**

**The following material properties are used from core glTF 2.0 spec but not required:**
baseColorFactor, metallicFactor, roughnessFactor
baseColorTexture: Must point to a texture stored in dds.
emissiveTexture: Must point to a texture stored in dds.
emissiveFactor
alphaMode
**The following material properties are ignored from core spec:**
All Multi-UVs
metalRoughnessTexture: Must instead use Microsoft optimized texture packing defined below
normalTexture: Must instead use Microsoft optimized texture packing defined below
normalScale
occlusionTexture: Must instead use Microsoft optimized texture packing defined below
occlusionStrength

Windows Mixed Reality home requires a series of optimizations on top of the core glTF spec. These are defined using custom extensions. The following packing formats and extensions are required otherwise the model won’t render successfully.

Windows MR only supports rendering DDS textures packed according to the texture packing scheme defined in this section. DDS textures are referenced using the MSFT_texture_dds extension. Compressing textures is highly recommended. PC based Mixed Reality experiences expect textures to be packed using a 3-texture setup using the following packing specification:

glTF Property | Texture | Packing Scheme
-- | -- | --
pbrMetallicRoughness | baseColorTexture | Red (R), Green (G), Blue (B)
MSFT_packing_occlusionRoughnessMetallic | roughnessMetallicOcclusionTexture | Roughness (R), Metallic (G), Occlusion (B)
MSFT_packing_occlusionRoughnessMetallic | normalTexture | Normal (RG)

When compressing the DDS textures the following compression is expected on each map:

Map	                                                                            Expected Compression
Normal	                                                                        BC5
Base Color, Occlusion, MetallicRoughness, Emissive	BC7

**Comment by hridpath** [comment]
I think that the inclusion of the Windows Mixed Reality glTF extensions and export packaging will allow for more artists and developers to create more content quicker and efficiently for the next version of Windows 10 being released on October 17th, 2017

**Comment by McNopper** [comment]
Well, the approach I usggested would be more generic, but let's see what others think.

**Comment by donmccurdy** [comment]
I don't follow why the current glTF Occlusion (R), Roughness (G), Metallic (B) should be changed to Roughness (R), Metallic (G), Occlusion (B) ... according to the `MSFT_packing_occlusionRoughnessMetallic` spec, the new extension allows the same order as glTF already uses, so why support a new packing order at all?

**Comment by hridpath** [comment]
@donmccurdy I am not sure. MSFT has defined this for their implementation of "Mixed Reality Portal" which is part of their core. In order for a developer to utilize 3D object inside the portal, these are the spec they define.

**Comment by donmccurdy** [comment]
Ok, thanks. It looks like the MSFT spec can be implemented without changing packing order (e.g. by setting `occlusionRoughnessMetallicTexture` instead of `roughnessMetallicOcclusionTexture` on the `MSFT_packing_occlusionRoughnessMetallic` extension) so there is no urgent need to support arbitrary texture packing orders in the extension.

**Comment by donmccurdy** [comment]
Closing for now. At the moment I think it would be better for these to be implemented within Microsoft's tools, until they become official extensions.
