### ISSUE TITLE
Export works only from the first layer

### ISSUE THREAD

**Issue by navFooh** [KhronosGroup/glTF-Blender-Exporter#95]
I'm experiencing this issue for my workflow from `.obj` to `.glb` for use in Three.js

I've imported all of my `.obj` files in a Blender scene and then I've sorted them in different layers for different scenes.

When I select everything in the second layer, then export to `.glb` with these settings:
- check `Export selected only`
- uncheck `Export all layers`
- uncheck everything else except `Export normals`

The exported .`glb` does have the correct file size, so it seems to contain the data. But when importing in Three.js, it does not create a Mesh in the GLTFLoader. It does create the whole scene and object structure though so I do see containers for the objects with the correct object names, but no mesh.

I'm aware that this could be an issue in the Three.js loader, but I'm wondering why the exporter does something different when exporting from layer 2 only. This does not occur when exporting layer 1.

You can test this easily by dragging exported .`glb` files in this viewer:
https://gltf-viewer.donmccurdy.com/

Some notes:
- The same happens when exporting to `.gltf`
- My blender version is `2.78`
- I'm using the latest state of the master branch for exporting, commit: 862a53fd4c5852a39fe02f7fea57332f78361f86

**Comment by UX3D-nopper** [comment]
Hmm, for some reason, the mesh is not referenced in the node.

**Comment by shakesoda** [comment]
this bug just sent me on a wild goose chase for half the day (the other half being that skeletal animation seems to be totally broken...), any update?

**Comment by donmccurdy** [comment]
If I'm reading correctly, the `Export all layers` option is designed to behave as follows:

1. When enabled, objects in any layer may be exported if they meet other criteria (e.g. selection).
2. When disabled, objects in layers 2–N are never exported, and objects in layer 1 are only exported if they meet other criteria (e.g. selection).

If that behavior is correct, we should perhaps rename the option to `Export layer 1 only`, disabled by default, to make it clear that selections in other layers are ignored.

**Comment by shakesoda** [comment]
I feel like what it should actually do is export all scene visible layers. As a user this is always how things act in Blender, since there's nothing otherwise special about any particular layer. Export all would just ignore layer visibility.

**Comment by UX3D-nopper** [comment]
Basically, the feature is in, as we discovered some general Blender approach:
In some cases, Some artists put the main scene in layer 1, instances in the remaining layers. But these instances are used in layer 1.

Best solution would be, to have the layer grid in the export, where the layers can be selected.

**Comment by emackey** [comment]
> Best solution would be, to have the layer grid in the export, where the layers can be selected.

Let's not ask that much of the user.  Really there are only two common options:  Export from visible layers, or export from all layers.  In both cases the selection can be further reduced to just export selected object(s) from the above-chosen layers, via the existing "export selection" option.

**Comment by shakesoda** [comment]
Further, artists who want the special layer 1 workflow can set it visible, unlink scene visible layers from the viewport and proceed as usual (& it will work the same everywhere)

**Comment by donmccurdy** [comment]
We'll be adjusting how this works in the new import/exporter, https://github.com/KhronosGroup/glTF-Blender-IO.

**Comment by emackey** [comment]
Anyone who was following this issue should instead follow https://github.com/KhronosGroup/glTF-Blender-IO/issues/193, thanks.
