### ISSUE TITLE
Crossed planes are not correctly exported

### ISSUE THREAD

**Issue by akaSpy** [KhronosGroup/glTF-Blender-Exporter#97]
I have a model of grass made of several crossed planes. When I import this model in Blender everyrhing is ok, but when I export it to the GLTF format it is not shown in the following engines: A-Frame, three.js, and BabylonJS.

Overall I use the following procedure for export: 
1. Export from 3ds Max in Collada format. 
2. Import to Blender and export in GLTF.

You can download the model in Collada and GLTF formats [here](https://yadi.sk/d/8Vef9-1Q3NCFe9)

Can you debug it please.

Thank you in advance.

**Comment by UX3D-nopper** [comment]
The material created is not possible to be represented in glTF, as mix is used.
Set Alpha: 1.0 in Blender Transparency. It will look wrong in Blender, but correct in glTF:
![grafik](https://user-images.githubusercontent.com/27856744/30827384-3b2bbd16-a23a-11e7-9fd8-b728e68a58c4.png)

**Comment by akaSpy** [comment]
@UX3D-nopper Sorry for bothering you. Thank you very much for being attentive to my problem.
