### ISSUE TITLE
baseColorFactor-parameter isn't exported

### ISSUE THREAD

**Issue by akaSpy** [KhronosGroup/glTF-Blender-Exporter#98]
When I set the baseColorFactor-parameter in Blender, it isn't exported.

Nodes in Blender — https://yadi.sk/i/aIuzNlej3NNgKL

Exported material:

`
{
            "name" : "Metal", 
            "normalTexture" : {
                "index" : 5
            }, 
            "occlusionTexture" : {
                "index" : 6
            }, 
            "pbrMetallicRoughness" : {
                "metallicFactor" : 0.6000000238418579, 
                "roughnessFactor" : 0.6000000238418579
            }
        }
`

**Comment by UX3D-nopper** [comment]
baseColorFactor is only exported, when directly manipulated in the node.

**Comment by thoced** [comment]
Hello,

BaseColorFactor is actually exported when a texture is associated with the node but no material is created in the Json file. Is this normal?

Thank you
