### ISSUE TITLE
Fix for extras not being exported if custom properties are IDPropertyGroup

### ISSUE THREAD

**Issue by jacobo3d** [KhronosGroup/glTF-Blender-Exporter#99]
When adding custom properties through the API, as a group of properties in a dictionary (IDPropertyGroup), it won't get included in extras when exporting.

In **gltf2_create.py**, inside the **create_custom_property** function, I've added the following and it works correctly (after line 339):

```
        if hasattr(value, "to_dict"):
            value = value.to_dict()
            add_value = True
```

**Comment by jacobo3d** [comment]
```
import json
def is_json(data):
    try:
        json.dumps(data)
        return True
    except:
        return False
```

**Comment by UX3D-nopper** [comment]
Implemented here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/2bdcb26351c16fd6d732198100913f973332518c
Thank you!
